function adc_16g_asnt_init(blk, varargin)

port_names = {...
    'clk',...
    'data_a0',...
    'data_a1',...
    'data_a2',...
    'data_a3',...
    'data_b0',...
    'data_b1',...
    'data_b2',...
    'data_b3',...
    'data_c0',...
    'data_c1',...
    'data_c2',...
    'data_c3',...
    'data_d0',...
    'data_d1',...
    'data_d2',...
    'data_d3',...
    'sync'};

% find out all the blocks in the design
gateway_ins     = find_system(blk, 'FollowLinks', 'on', 'LookUnderMasks', 'all',     'MaskType', 'Xilinx Gateway In Block');

%we only need to change the 'Name' here.
for i = 1 : length(gateway_ins)
    port_name = clear_name([gcb, '_', port_names{i}]);
    set_param(gateway_ins{i},'Name', port_name);
end
    
end