function adc_16g_asnt_init(blk, varargin)

port_names = {...
    'data_a0',...    
    'data_a1',...
    'data_a10',...
    'data_a11',...
    'data_a12',...
    'data_a13',...
    'data_a14',...
    'data_a15',...
    'data_a16',...
    'data_a17',...
    'data_a18',...
    'data_a19',...
    'data_a2',...
    'data_a20',...
    'data_a21',...
    'data_a22',...
    'data_a23',...
    'data_a24',...
    'data_a25',...
    'data_a26',...
    'data_a27',...
    'data_a28',...
    'data_a29',...
    'data_a3',...
    'data_a30',...
    'data_a31',...
    'data_a32',...
    'data_a33',...
    'data_a34',...
    'data_a35',...
    'data_a36',...
    'data_a37',...
    'data_a38',...
    'data_a39',...
    'data_a4',...
    'data_a40',...
    'data_a41',...
    'data_a42',...
    'data_a43',...
    'data_a44',...
    'data_a45',...
    'data_a46',...
    'data_a47',...
    'data_a48',...
    'data_a49',...
    'data_a5',...
    'data_a50',...
    'data_a51',...
    'data_a52',...
    'data_a53',...
    'data_a54',...
    'data_a55',...
    'data_a56',...
    'data_a57',...
    'data_a58',...
    'data_a59',...
    'data_a6',...
    'data_a60',...
    'data_a61',...
    'data_a62',...
    'data_a63',...
    'data_a7',...
    'data_a8',...
    'data_a9',...
    'sync'};

% find out all the blocks in the design
gateway_ins     = find_system(blk, 'FollowLinks', 'on', 'LookUnderMasks', 'all',     'MaskType', 'Xilinx Gateway In Block');

%we only need to change the 'Name' here.
for i = 1 : length(gateway_ins)
    port_name = clear_name([gcb, '_', port_names{i}]);
    set_param(gateway_ins{i},'Name', port_name);
end
    
end