set_false_path -from [get_pins {snap_fengine_eth_sw/rx_stretch_reg[25]/C}] -to [get_pins snap_fengine_eth_sw/led_rx_reg_reg/D]
set_false_path -from [get_pins {snap_fengine_eth_sw/tx_stretch_reg[25]/C}] -to [get_pins snap_fengine_eth_sw/led_tx_reg_reg/D]
set_false_path -from [get_pins {snap_fengine_eth_sw/down_stretch_reg[25]/C}] -to [get_pins snap_fengine_eth_sw/led_up_reg_reg/D]
set_false_path -from [get_pins snap_fengine_eth_sw/mac_resetRR_reg/C] -to [get_pins snap_fengine_eth_sw/app_rst_reg/D]
set_false_path -from [get_pins snap_fengine_eth_sw/tge_rx_inst/app_overrun_ack_reg/C] -to [get_pins snap_fengine_eth_sw/tge_rx_inst/overrun_ackR_reg/D]
set_false_path -from [get_pins snap_fengine_eth_sw/tge_tx_inst/tx_overflow_latch_reg/C] -to [get_pins snap_fengine_eth_sw/tge_tx_inst/app_overflowR_reg/D]
set_false_path -from [get_pins {snap_fengine_eth_sw/tge_rx_inst/app_state_reg[0]/C}] -to [get_pins snap_fengine_eth_sw/tge_rx_inst/overrunR_reg/D]
set_false_path -from [get_pins snap_fengine_eth_sw/macr_state_reg/C] -to [get_pins snap_fengine_eth_sw/app_rst_reg/D]
set_false_path -from [get_pins {snap_fengine_eth_sw/tge_rx_inst/app_state_reg[1]/C}] -to [get_pins snap_fengine_eth_sw/tge_rx_inst/overrunR_reg/D]

