  sysgen_dut : entity xil_defaultlib.test_vcu128 
  port map (
    test_vcu128_gbe_app_dbg_data => test_vcu128_gbe_app_dbg_data,
    test_vcu128_gbe_app_dbg_dvld => test_vcu128_gbe_app_dbg_dvld,
    test_vcu128_gbe_app_rx_badframe => test_vcu128_gbe_app_rx_badframe,
    test_vcu128_gbe_app_rx_data => test_vcu128_gbe_app_rx_data,
    test_vcu128_gbe_app_rx_dvld => test_vcu128_gbe_app_rx_dvld,
    test_vcu128_gbe_app_rx_eof => test_vcu128_gbe_app_rx_eof,
    test_vcu128_gbe_app_rx_overrun => test_vcu128_gbe_app_rx_overrun,
    test_vcu128_gbe_app_rx_srcip => test_vcu128_gbe_app_rx_srcip,
    test_vcu128_gbe_app_rx_srcport => test_vcu128_gbe_app_rx_srcport,
    test_vcu128_gbe_app_tx_afull => test_vcu128_gbe_app_tx_afull,
    test_vcu128_gbe_app_tx_overflow => test_vcu128_gbe_app_tx_overflow,
    test_vcu128_rst_user_data_out => test_vcu128_rst_user_data_out,
    clk => clk,
    test_vcu128_gbe_app_rx_ack => test_vcu128_gbe_app_rx_ack,
    test_vcu128_gbe_app_rx_rst => test_vcu128_gbe_app_rx_rst,
    test_vcu128_gbe_app_tx_data => test_vcu128_gbe_app_tx_data,
    test_vcu128_gbe_app_tx_destip => test_vcu128_gbe_app_tx_destip,
    test_vcu128_gbe_app_tx_destport => test_vcu128_gbe_app_tx_destport,
    test_vcu128_gbe_app_tx_dvld => test_vcu128_gbe_app_tx_dvld,
    test_vcu128_gbe_app_tx_eof => test_vcu128_gbe_app_tx_eof,
    test_vcu128_gbe_app_tx_rst => test_vcu128_gbe_app_tx_rst,
    test_vcu128_led_gateway => test_vcu128_led_gateway
  );
