# Auto Generated by Xilinx generate_app. Modify at your own risk

CC := mb-gcc
CC_FLAGS := -MMD -MP -mlittle-endian -mxl-soft-mul -mcpu=v10.0
CFLAGS := -ffunction-sections -fdata-sections
LN_FLAGS := -Wl,--start-group,-lxil,-lgcc,-lc,--end-group \
            -Wl,--gc-sections \
            -Wl,-Map=map \
            -Wl,--strip-debug \
            -Wl,--defsym=_HEAP_SIZE=0x10000

c_SOURCES := $(wildcard *.c)
S_SOURCES := $(wildcard *.S)
s_SOURCES := $(wildcard *.s)
INCLUDES := $(wildcard *.h)
OBJS := $(patsubst %.c, %.o, $(c_SOURCES))
OBJS += $(patsubst %.S, %.o, $(S_SOURCES))
OBJS += $(patsubst %.s, %.o, $(s_SOURCES))
LSCRIPT := -Tlscript.ld

CURRENT_DIR = $(shell pwd)
DEPFILES := $(patsubst %.o, %.d, $(OBJS))
LIBS := bsp/microblaze_0/lib/libxil.a
EXEC := executable.elf

INCLUDEPATH := -Ibsp/microblaze_0/include -I.
LIBPATH := -Lbsp/microblaze_0/lib

export CFLAGS

all: symbols

$(EXEC): $(LIBS) $(OBJS) $(INCLUDES)
	$(CC) -o $@ $(OBJS) $(CC_FLAGS) $(CFLAGS) $(LN_FLAGS) $(LIBPATH) $(LSCRIPT)

$(LIBS):
	$(MAKE) -C bsp

%.o:%.c
	$(CC) $(CC_FLAGS) $(CFLAGS) -c $< -o $@ $(INCLUDEPATH)

%.o:%.S
	$(CC) $(CC_FLAGS) $(CFLAGS) -c $< -o $@ $(INCLUDEPATH)

%.o:%.s
	$(CC) $(CC_FLAGS) $(CFLAGS) -c $< -o $@ $(INCLUDEPATH)

symbols: $(EXEC)
	mb-readelf -s $< | sort -rnk3 > $@

tags:
	ctags -R

clean:
	$(MAKE) -C bsp clean
	rm -rf $(OBJS) $(LIBS) $(EXEC) *.o tags

.PHONY: clean tags

-include $(DEPFILES)
