#!/bin/bash
####### User to edit these accordingly ######
export MATLAB_PATH=/usr/local/MATLAB/R2013a
PLATFORM=lin64
export XILINX_PATH=/opt/Xilinx/Vivado/2014.4
export MLIB_DEVEL_PATH=/home/jack/github/jack-h/jasper/mlib_devel
#export USE_VIVADO_RUNTIME_FOR_MATLAB=1
##############################################
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR
#source $XILINX_PATH/settings64.sh
#export PATH=${PATH}:${XILINX}/ISE/bin/${PLATFORM}:${XILINX_PATH}/ISE/sysgen/bin/${PLATFORM}:${MATLAB_PATH}/bin
export PATH=${MATLAB_PATH}/bin:$PATH
echo $PATH
export XPS_BASE_PATH=$MLIB_DEVEL_PATH/xps_base
#export MATLAB=$MATLAB_PATH
#$MATLAB/bin/matlab
echo "EXECUTING: ${XILINX_PATH}/bin/sysgen $@"
${XILINX_PATH}/bin/sysgen $@
