#!/bin/bash
##############################################
source $MLIB_DEVEL_PATH/ise_config.sh
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR
export PATH=${PATH}:${XILINX}/ISE/bin/${PLATFORM}:${XILINX_PATH}/ISE/sysgen/bin/${PLATFORM}
export PATH=${MATLAB_PATH}/bin:$PATH
echo $PATH
echo "EXECUTING: ${MATLAB_PATH}/bin/matlab $@"
${MATLAB_PATH}/bin/matlab $@
