function pfb_coeff_gen_new_init(PFBSize, CoeffBitWidth, TotalTaps, CoeffDistMem, WindowType, bram_latency, n_inputs, nput, fwidth)

alltaps = TotalTaps*2^PFBSize;
windowval = transpose(window(WindowType, alltaps));
total_coeffs = windowval .* sinc(fwidth*([0:alltaps-1]/(2^PFBSize)-TotalTaps/2));
for i=1:alltaps/2^n_inputs,
    buf(i)=total_coeffs((i-1)*2^n_inputs + nput + 1);
end

%% inports
xlsub3_din = xInport('din');
xlsub3_sync = xInport('sync');

%% outports
xlsub3_dout = xOutport('dout');
xlsub3_sync_out = xOutport('sync_out');

%% diagram

% block: dsp48e_pfb_test2/pfb_row/pfb_coeff_gen_new/Counter
xlsub3_Counter_out1 = xSignal;
xlsub3_Counter = xBlock(struct('source', 'Counter', 'name', 'Counter'), ...
                        struct('n_bits', PFBSize-n_inputs, ...
                               'rst', 'on', ...
                               'use_rpm', 'on'), ...
                        {xlsub3_sync}, ...
                        {xlsub3_Counter_out1});

% block: dsp48e_pfb_test2/pfb_row/pfb_coeff_gen_new/Delay
xlsub3_Delay = xBlock(struct('source', 'Delay', 'name', 'Delay'), ...
                      struct('latency', bram_latency+1), ...
                      {xlsub3_sync}, ...
                      {xlsub3_sync_out});

% block: dsp48e_pfb_test2/pfb_row/pfb_coeff_gen_new/Delay1
xlsub3_Delay1 = xBlock(struct('source', 'Delay', 'name', 'Delay1'), ...
                       struct('latency', 3), ...
                       {xlsub3_din}, ...
                       {xlsub3_dout});

% block: dsp48e_pfb_test2/pfb_row/pfb_coeff_gen_new/ROM1
ROM_blocks = [];
for k=TotalTaps:-1:1,
    xlsub3_ROM1_out1 = xSignal;
    xlsub3_ROM1 = xBlock(struct('source', 'ROM', 'name', ['ROM', num2str(k)]), ...
                         struct('depth', 2^(PFBSize-n_inputs), ...
                                'initVector', pfb_coeff_gen_calc(PFBSize,TotalTaps,WindowType,n_inputs,nput,fwidth, k), ...
                                'latency', 2, ...
                                'n_bits', CoeffBitWidth, ...
                                'bin_pt', CoeffBitWidth-1), ...
                         {xlsub3_Counter_out1}, ...
                         {xlsub3_ROM1_out1});
    ROM_blocks = [ROM_blocks, xlsub3_ROM1];

    coeff_outport = xOutport(['coeffs', num2str(TotalTaps-k+1)]);
    xlsub3_Register = xBlock(struct('source', 'Register', 'name', ['Register', num2str(k)]), ...
                             [], ...
                             {xlsub3_ROM1_out1}, ...
                             {coeff_outport });
    
end


end

