function power_dsp48e(bitwidth)

%% inports
c = xInport('c');

%% outports
p = xOutport('p');

%% diagram

% block: single_pol/spect_power/power_dsp48e/Constant1
Constant1_out1 = xSignal;
Constant1 = xBlock(struct('source', 'Constant', 'name', 'Constant1'), ...
                          struct('arith_type', 'Unsigned', ...
                                 'const', 0, ...
                                 'n_bits', 4, ...
                                 'bin_pt', 0), ...
                          {}, ...
                          {Constant1_out1});

% block: single_pol/spect_power/power_dsp48e/Constant2
Constant2_out1 = xSignal;
Constant2 = xBlock(struct('source', 'Constant', 'name', 'Constant2'), ...
                          struct('arith_type', 'Unsigned', ...
                                 'const', 0, ...
                                 'n_bits', 4, ...
                                 'bin_pt', 0), ...
                          {}, ...
                          {Constant2_out1});

% block: single_pol/spect_power/power_dsp48e/Constant3
Constant3_out1 = xSignal;
Constant3 = xBlock(struct('source', 'Constant', 'name', 'Constant3'), ...
                          struct('arith_type', 'Unsigned', ...
                                 'const', 21, ...
                                 'n_bits', 7, ...
                                 'bin_pt', 0), ...
                          {}, ...
                          {Constant3_out1});

% block: single_pol/spect_power/power_dsp48e/Constant4
Constant4_out1 = xSignal;
Constant4 = xBlock(struct('source', 'Constant', 'name', 'Constant4'), ...
                          struct('arith_type', 'Unsigned', ...
                                 'const', 0, ...
                                 'n_bits', 3, ...
                                 'bin_pt', 0), ...
                          {}, ...
                          {Constant4_out1});

% block: single_pol/spect_power/power_dsp48e/Constant5
Constant5_out1 = xSignal;
Constant5 = xBlock(struct('source', 'Constant', 'name', 'Constant5'), ...
                          struct('arith_type', 'Unsigned', ...
                                 'const', 0, ...
                                 'n_bits', 1, ...
                                 'bin_pt', 0), ...
                          {}, ...
                          {Constant5_out1});

% block: single_pol/spect_power/power_dsp48e/Constant6
Constant6_out1 = xSignal;
Constant6 = xBlock(struct('source', 'Constant', 'name', 'Constant6'), ...
                          struct('arith_type', 'Unsigned', ...
                                 'const', 5, ...
                                 'n_bits', 7, ...
                                 'bin_pt', 0), ...
                          {}, ...
                          {Constant6_out1});

% block: single_pol/spect_power/power_dsp48e/Constant7
Constant7_out1 = xSignal;
Constant7 = xBlock(struct('source', 'Constant', 'name', 'Constant7'), ...
                          struct('arith_type', 'Unsigned', ...
                                 'const', 0, ...
                                 'n_bits', 3, ...
                                 'bin_pt', 0), ...
                          {}, ...
                          {Constant7_out1});

% block: single_pol/spect_power/power_dsp48e/Constant8
Constant8_out1 = xSignal;
Constant8 = xBlock(struct('source', 'Constant', 'name', 'Constant8'), ...
                          struct('arith_type', 'Unsigned', ...
                                 'const', 0, ...
                                 'n_bits', 1, ...
                                 'bin_pt', 0), ...
                          {}, ...
                          {Constant8_out1});

% block: single_pol/spect_power/power_dsp48e/Convert
reinterp_real_out1 = xSignal;
Convert_out1 = xSignal;
Convert = xBlock(struct('source', 'Convert', 'name', 'Convert'), ...
                        struct('n_bits', 30, ...
                               'bin_pt', 0), ...
                        {reinterp_real_out1}, ...
                        {Convert_out1});

% block: single_pol/spect_power/power_dsp48e/Convert2
reinterp_imag_out1 = xSignal;
Convert2_out1 = xSignal;
Convert2 = xBlock(struct('source', 'Convert', 'name', 'Convert2'), ...
                         struct('n_bits', 30, ...
                                'bin_pt', 0), ...
                         {reinterp_imag_out1}, ...
                         {Convert2_out1});

% block: single_pol/spect_power/power_dsp48e/Convert3
Convert3_out1 = xSignal;
Convert3 = xBlock(struct('source', 'Convert', 'name', 'Convert3'), ...
                         struct('n_bits', 18, ...
                                'bin_pt', 0), ...
                         {reinterp_real_out1}, ...
                         {Convert3_out1});

% block: single_pol/spect_power/power_dsp48e/Convert4
Convert4_out1 = xSignal;
Convert4 = xBlock(struct('source', 'Convert', 'name', 'Convert4'), ...
                         struct('n_bits', 18, ...
                                'bin_pt', 0), ...
                         {reinterp_imag_out1}, ...
                         {Convert4_out1});

% block: single_pol/spect_power/power_dsp48e/DSP48E_0
DSP48E_0_out1 = xSignal;
DSP48E_0_out2 = xSignal;
DSP48E_0 = xBlock(struct('source', 'DSP48E', 'name', 'DSP48E_0'), ...
                         struct('use_pcout', 'on'), ...
                         {Convert2_out1, Convert4_out1, Constant6_out1, Constant1_out1, Constant8_out1, Constant7_out1}, ...
                         {DSP48E_0_out1, DSP48E_0_out2});

% block: single_pol/spect_power/power_dsp48e/DSP48E_1
DSP48E_1_out1 = xSignal;
DSP48E_1 = xBlock(struct('source', 'DSP48E', 'name', 'DSP48E_1'), ...
                         struct('use_pcin', 'on', ...
                                'pipeline_a', '2', ...
                                'pipeline_b', '2'), ...
                         {Convert_out1, Convert3_out1, DSP48E_0_out2, Constant3_out1, Constant2_out1, Constant5_out1, Constant4_out1}, ...
                         {DSP48E_1_out1});


% block: single_pol/spect_power/power_dsp48e/reinterp_imag
slice_imag_out1 = xSignal;
reinterp_imag = xBlock(struct('source', 'Reinterpret', 'name', 'reinterp_imag'), ...
                              struct('force_arith_type', 'on', ...
                                     'arith_type', 'Signed  (2''s comp)'), ...
                              {slice_imag_out1}, ...
                              {reinterp_imag_out1});

% block: single_pol/spect_power/power_dsp48e/reinterp_power
slice_power_out1 = xSignal;
reinterp_power = xBlock(struct('source', 'Reinterpret', 'name', 'reinterp_power'), ...
                               struct('force_arith_type', 'on', ...
                                      'force_bin_pt', 'on', ...
                                      'bin_pt', 2 * (bitwidth - 1)), ...
                               {slice_power_out1}, ...
                               {p});

% block: single_pol/spect_power/power_dsp48e/reinterp_real
slice_real_out1 = xSignal;
reinterp_real = xBlock(struct('source', 'Reinterpret', 'name', 'reinterp_real'), ...
                              struct('force_arith_type', 'on', ...
                                     'arith_type', 'Signed  (2''s comp)'), ...
                              {slice_real_out1}, ...
                              {reinterp_real_out1});

% block: single_pol/spect_power/power_dsp48e/slice_imag
slice_imag = xBlock(struct('source', 'Slice', 'name', 'slice_imag'), ...
                           struct('nbits', bitwidth, ...
                                  'mode', 'Lower Bit Location + Width'), ...
                           {c}, ...
                           {slice_imag_out1});

% block: single_pol/spect_power/power_dsp48e/slice_power
slice_power = xBlock(struct('source', 'Slice', 'name', 'slice_power'), ...
                            struct('nbits', 2 * bitwidth, ...
                                   'mode', 'Lower Bit Location + Width'), ...
                            {DSP48E_1_out1}, ...
                            {slice_power_out1});

% block: single_pol/spect_power/power_dsp48e/slice_real
slice_real = xBlock(struct('source', 'Slice', 'name', 'slice_real'), ...
                           struct('nbits', bitwidth), ...
                           {c}, ...
                           {slice_real_out1});



end

