set output_file [open "mem_tester_sim/ddr2_controller_v1_00_a/hdl/vhdl/controller_iobs.vhd" w ]
set line_num 1; puts $output_file "--******************************************************************************"
set line_num 2; puts $output_file "--"
set line_num 3; puts $output_file "--  Xilinx, Inc. 2002                 www.xilinx.com"
set line_num 4; puts $output_file "--"
set line_num 5; puts $output_file "--  XAPP 253 - Synthesizable DDR SDRAM Controller"
set line_num 6; puts $output_file "--"
set line_num 7; puts $output_file "--*******************************************************************************"
set line_num 8; puts $output_file "--"
set line_num 9; puts $output_file "--  File name :       controller_iobs.vhd"
set line_num 10; puts $output_file "--"
set line_num 11; puts $output_file "--  Description :     "
set line_num 12; puts $output_file "--                  All the IO's related to controller module are declared as"
set line_num 13; puts $output_file "--                  IOBUF's in this module"
set line_num 14; puts $output_file "--"
set line_num 15; puts $output_file "--  Date - revision : 05/01/2002"
set line_num 16; puts $output_file "--"
set line_num 17; puts $output_file "--  Author :          Lakshmi Gopalakrishnan ( Modified by Sailaja)"
set line_num 18; puts $output_file "--"
set line_num 19; puts $output_file "--  Contact : e-mail  hotline@xilinx.com"
set line_num 20; puts $output_file "--            phone   + 1 800 255 7778 "
set line_num 21; puts $output_file "--"
set line_num 22; puts $output_file "--  Disclaimer: LIMITED WARRANTY AND DISCLAMER. These designs are "
set line_num 23; puts $output_file "--              provided to you \"as is\". Xilinx and its licensors make and you "
set line_num 24; puts $output_file "--              receive no warranties or conditions, express, implied, "
set line_num 25; puts $output_file "--              statutory or otherwise, and Xilinx specifically disclaims any "
set line_num 26; puts $output_file "--              implied warranties of merchantability, non-infringement, or "
set line_num 27; puts $output_file "--              fitness for a particular purpose. Xilinx does not warrant that "
set line_num 28; puts $output_file "--              the functions contained in these designs will meet your "
set line_num 29; puts $output_file "--              requirements, or that the operation of these designs will be "
set line_num 30; puts $output_file "--              uninterrupted or error free, or that defects in the Designs "
set line_num 31; puts $output_file "--              will be corrected. Furthermore, Xilinx does not warrant or "
set line_num 32; puts $output_file "--              make any representations regarding use or the results of the "
set line_num 33; puts $output_file "--              use of the designs in terms of correctness, accuracy, "
set line_num 34; puts $output_file "--              reliability, or otherwise. "
set line_num 35; puts $output_file "--"
set line_num 36; puts $output_file "--              LIMITATION OF LIABILITY. In no event will Xilinx or its "
set line_num 37; puts $output_file "--              licensors be liable for any loss of data, lost profits, cost "
set line_num 38; puts $output_file "--              or procurement of substitute goods or services, or for any "
set line_num 39; puts $output_file "--              special, incidental, consequential, or indirect damages "
set line_num 40; puts $output_file "--              arising from the use or operation of the designs or "
set line_num 41; puts $output_file "--              accompanying documentation, however caused and on any theory "
set line_num 42; puts $output_file "--              of liability. This limitation will apply even if Xilinx "
set line_num 43; puts $output_file "--              has been advised of the possibility of such damage. This "
set line_num 44; puts $output_file "--              limitation shall apply not-withstanding the failure of the "
set line_num 45; puts $output_file "--              essential purpose of any limited remedies herein. "
set line_num 46; puts $output_file "--"
set line_num 47; puts $output_file "--  Copyright © 2002 Xilinx, Inc."
set line_num 48; puts $output_file "--  All rights reserved "
set line_num 49; puts $output_file "-- "
set line_num 50; puts $output_file "--*****************************************************************************"
set line_num 51; puts $output_file "library ieee;"
set line_num 52; puts $output_file "use ieee.std_logic_1164.all;"
set line_num 53; puts $output_file "use ieee.std_logic_unsigned.all;"
set line_num 54; puts $output_file "use work.parameter.all;"
set line_num 55; puts $output_file "--"
set line_num 56; puts $output_file "-- pragma translate_off"
set line_num 57; puts $output_file "library UNISIM;"
set line_num 58; puts $output_file "use UNISIM.VCOMPONENTS.ALL;"
set line_num 59; puts $output_file "-- pragma translate_on"
set line_num 60; puts $output_file "--"
set line_num 61; puts $output_file "entity controller_iobs is"
set line_num 62; puts $output_file "port("
set line_num 63; puts $output_file "	clk0                : in std_logic;"
set line_num 64; puts $output_file "	clk90               : in std_logic;"
set line_num 65; puts $output_file "	ddr_rasb            : in std_logic;"
set line_num 66; puts $output_file "	ddr_casb            : in std_logic;"
set line_num 67; puts $output_file "	ddr_web             : in std_logic;"
set line_num 68; puts $output_file "	ddr_cke             : in std_logic;"
set line_num 69; puts $output_file "	ddr_csb             : in std_logic_vector(1 downto 0);"
set line_num 70; puts $output_file "	ddr_ODT             : in std_logic_vector(1 downto 0);"
set line_num 71; puts $output_file "	ddr_address         : in std_logic_vector((row_address_p -1) downto 0);"
set line_num 72; puts $output_file "	ddr_ba              : in std_logic_vector((bank_address_p -1) downto 0);"
set line_num 73; puts $output_file "	ddr_rst_dqs_div_out : in std_logic;"
set line_num 74; puts $output_file "	ddr_rst_dqs_div_in  : out std_logic;"
set line_num 75; puts $output_file "	ddr_force_nop       : in std_logic_vector(1 downto 0);"
set line_num 76; puts $output_file "	pad_rasb            : out std_logic;"
set line_num 77; puts $output_file "	pad_casb            : out std_logic;"
set line_num 78; puts $output_file "	pad_web             : out std_logic;"
set line_num 79; puts $output_file "	pad_ba              : out std_logic_vector((bank_address_p -1) downto 0);"
set line_num 80; puts $output_file "	pad_address         : out std_logic_vector((row_address_p -1) downto 0);"
set line_num 81; puts $output_file "	pad_cke             : out std_logic;"
set line_num 82; puts $output_file "	pad_csb             : out std_logic_vector(1 downto 0);"
set line_num 83; puts $output_file "	pad_ODT             : out std_logic_vector(1 downto 0);"
set line_num 84; puts $output_file "	pad_rst_dqs_div_out : out std_logic;"
set line_num 85; puts $output_file "	pad_rst_dqs_div_in  : in std_logic"
set line_num 86; puts $output_file "   "
set line_num 87; puts $output_file ");"
set line_num 88; puts $output_file "end controller_iobs;"
set line_num 89; puts $output_file ""
set line_num 90; puts $output_file ""
set line_num 91; puts $output_file "architecture arc_controller_iobs of controller_iobs is"
set line_num 92; puts $output_file ""
set line_num 93; puts $output_file "attribute xc_props : string;"
set line_num 94; puts $output_file "attribute syn_keep : boolean;"
set line_num 95; puts $output_file ""
set line_num 96; puts $output_file "component FD"
set line_num 97; puts $output_file "   port("
set line_num 98; puts $output_file "      Q                              :  out   STD_LOGIC;"
set line_num 99; puts $output_file "      D                              :  in    STD_LOGIC;"
set line_num 100; puts $output_file "      C                              :  in    STD_LOGIC);"
set line_num 101; puts $output_file "end component;"
set line_num 102; puts $output_file ""
set line_num 103; puts $output_file "component FDS"
set line_num 104; puts $output_file "   port("
set line_num 105; puts $output_file "      Q                              :  out   STD_LOGIC;"
set line_num 106; puts $output_file "      D                              :  in    STD_LOGIC;"
set line_num 107; puts $output_file "      C                              :  in    STD_LOGIC;"
set line_num 108; puts $output_file "      S                              :  in    STD_LOGIC);"
set line_num 109; puts $output_file "end component;"
set line_num 110; puts $output_file ""
set line_num 111; puts $output_file "component IBUF"
set line_num 112; puts $output_file " port ("
set line_num 113; puts $output_file "   I : in std_logic;"
set line_num 114; puts $output_file "   O : out std_logic);"
set line_num 115; puts $output_file " end component;"
set line_num 116; puts $output_file ""
set line_num 117; puts $output_file "component OBUF"
set line_num 118; puts $output_file " port ("
set line_num 119; puts $output_file "   O : out std_logic;"
set line_num 120; puts $output_file "   I : in std_logic);"
set line_num 121; puts $output_file " end component;"
set line_num 122; puts $output_file ""
set line_num 123; puts $output_file ""
set line_num 124; puts $output_file "---- **************************************************"
set line_num 125; puts $output_file "---- iob attributes for instantiated FD components"
set line_num 126; puts $output_file "---- **************************************************"
set line_num 127; puts $output_file ""
set line_num 128; puts $output_file "signal clk180              : std_logic;"
set line_num 129; puts $output_file "signal clk270              : std_logic;"
set line_num 130; puts $output_file "signal GND                 : std_logic;"
set line_num 131; puts $output_file "signal buf_rasb            : std_logic;"
set line_num 132; puts $output_file "signal buf_casb            : std_logic;"
set line_num 133; puts $output_file "signal buf_web             : std_logic;"
set line_num 134; puts $output_file "signal buf_ba              : std_logic_vector((bank_address_p -1) downto 0);"
set line_num 135; puts $output_file "signal buf_address         : std_logic_vector((row_address_p -1) downto 0);"
set line_num 136; puts $output_file "signal buf_cke             : std_logic;"
set line_num 137; puts $output_file "signal buf_csb             : std_logic_vector(1 downto 0);"
set line_num 138; puts $output_file "signal buf_ODT             : std_logic_vector(1 downto 0);"
set line_num 139; puts $output_file "signal buf_rst_dqs_div_out : std_logic;"
set line_num 140; puts $output_file "signal buf_rst_dqs_div_in  : std_logic;"
set line_num 141; puts $output_file ""
set line_num 142; puts $output_file "attribute xc_props of iob_web              : label is \"IOB=TRUE\";"
set line_num 143; puts $output_file "attribute syn_keep of iob_web              : label is true; "
set line_num 144; puts $output_file "attribute xc_props of iob_rasb             : label is \"IOB=TRUE\";"
set line_num 145; puts $output_file "attribute syn_keep of iob_rasb             : label is true; "
set line_num 146; puts $output_file "attribute xc_props of iob_casb             : label is \"IOB=TRUE\";"
set line_num 147; puts $output_file "attribute syn_keep of iob_casb             : label is true; "
set line_num 148; puts $output_file "attribute xc_props of iob_csb0             : label is \"IOB=TRUE\";"
set line_num 149; puts $output_file "attribute syn_keep of iob_csb0             : label is true; "
set line_num 150; puts $output_file "attribute xc_props of iob_csb1             : label is \"IOB=TRUE\";"
set line_num 151; puts $output_file "attribute syn_keep of iob_csb1             : label is true; "
set line_num 152; puts $output_file "attribute xc_props of iob_cke              : label is \"IOB=TRUE\";"
set line_num 153; puts $output_file "attribute syn_keep of iob_cke              : label is true; "
set line_num 154; puts $output_file "attribute xc_props of iob_ODT0             : label is \"IOB=TRUE\";"
set line_num 155; puts $output_file "attribute syn_keep of iob_ODT0             : label is true; "
set line_num 156; puts $output_file "attribute xc_props of iob_ODT1             : label is \"IOB=TRUE\";"
set line_num 157; puts $output_file "attribute syn_keep of iob_ODT1             : label is true; "
set line_num 158; puts $output_file "attribute xc_props of iob_rst_dqs_div_out  : label is \"IOB=TRUE\";"
set line_num 159; puts $output_file "attribute syn_keep of iob_rst_dqs_div_out  : label is true; "
set line_num 160; puts $output_file "attribute syn_keep of clk180 : signal is true; "
set line_num 161; puts $output_file "attribute syn_keep of clk270 : signal is true; "
set line_num 162; puts $output_file ""
set line_num 163; puts $output_file "begin"
set line_num 164; puts $output_file ""
set line_num 165; puts $output_file "clk180 <= not clk0;"
set line_num 166; puts $output_file "clk270 <= not clk90;"
set line_num 167; puts $output_file "GND <= '0';"
set line_num 168; puts $output_file "  "
set line_num 169; puts $output_file ""
set line_num 170; puts $output_file "---- ******************************************* ----"
set line_num 171; puts $output_file "----            FD for control signals           ----"
set line_num 172; puts $output_file "---- ******************************************* ----"
set line_num 173; puts $output_file "           "
set line_num 174; puts $output_file "iob_web : FD port map ("
set line_num 175; puts $output_file "                         Q    => buf_web,"
set line_num 176; puts $output_file "                         D    => ddr_web,"
set line_num 177; puts $output_file "                         C    => clk180);"
set line_num 178; puts $output_file "                         "
set line_num 179; puts $output_file "iob_rasb : FD port map ("
set line_num 180; puts $output_file "                         Q    => buf_rasb,"
set line_num 181; puts $output_file "                         D    => ddr_rasb,"
set line_num 182; puts $output_file "                         C    => clk180);"
set line_num 183; puts $output_file "                         "
set line_num 184; puts $output_file "iob_casb : FD port map ("
set line_num 185; puts $output_file "                         Q    => buf_casb,"
set line_num 186; puts $output_file "                         D    => ddr_casb,"
set line_num 187; puts $output_file "                         C    => clk180);"
set line_num 188; puts $output_file ""
set line_num 189; puts $output_file "iob_csb0 : FDS port map ("
set line_num 190; puts $output_file "                         Q    => buf_csb(0),"
set line_num 191; puts $output_file "                         D    => ddr_csb(0),"
set line_num 192; puts $output_file "                         S    => ddr_force_nop(0),"
set line_num 193; puts $output_file "                         C    => clk180);"
set line_num 194; puts $output_file ""
set line_num 195; puts $output_file "iob_csb1 : FDS port map ("
set line_num 196; puts $output_file "                         Q    => buf_csb(1),"
set line_num 197; puts $output_file "                         D    => ddr_csb(1),"
set line_num 198; puts $output_file "                         S    => ddr_force_nop(1),"
set line_num 199; puts $output_file "                         C    => clk180);"
set line_num 200; puts $output_file ""
set line_num 201; puts $output_file "iob_cke : FD port map ("
set line_num 202; puts $output_file "                         Q    => buf_cke,"
set line_num 203; puts $output_file "                         D    => ddr_cke,"
set line_num 204; puts $output_file "                         C    => clk180);"
set line_num 205; puts $output_file ""
set line_num 206; puts $output_file "iob_ODT0 : FD port map ("
set line_num 207; puts $output_file "                         Q    => buf_ODT(0),"
set line_num 208; puts $output_file "                         D    => ddr_ODT(0),"
set line_num 209; puts $output_file "                         C    => clk180);"
set line_num 210; puts $output_file ""
set line_num 211; puts $output_file "iob_ODT1 : FD port map ("
set line_num 212; puts $output_file "                         Q    => buf_ODT(1),"
set line_num 213; puts $output_file "                         D    => ddr_ODT(1),"
set line_num 214; puts $output_file "                         C    => clk180);"
set line_num 215; puts $output_file ""
set line_num 216; puts $output_file "iob_rst_dqs_div_out : FD port map ("
set line_num 217; puts $output_file "                         Q    => buf_rst_dqs_div_out,"
set line_num 218; puts $output_file "                         D    => ddr_rst_dqs_div_out,"
set line_num 219; puts $output_file "                         C    => clk180);"
set line_num 220; puts $output_file ""
set line_num 221; puts $output_file "---- ******************************************* ----"
set line_num 222; puts $output_file "----            FD for addresses                 ----"
set line_num 223; puts $output_file "---- ******************************************* ----"
set line_num 224; puts $output_file ""
set line_num 225; puts $output_file "gen_iob_address: for bit_index in 0 to (row_address_p-1) generate"
set line_num 226; puts $output_file "		attribute xc_props of iob_address: label is \"IOB=TRUE\";"
set line_num 227; puts $output_file "	begin"
set line_num 228; puts $output_file "		iob_address: FD port map ( "
set line_num 229; puts $output_file "               Q => buf_address(bit_index),"
set line_num 230; puts $output_file "               D => ddr_address(bit_index),"
set line_num 231; puts $output_file "               C => clk180"
set line_num 232; puts $output_file "                );"
set line_num 233; puts $output_file "    end generate;"
set line_num 234; puts $output_file ""
set line_num 235; puts $output_file "gen_iob_ba: for bit_index in 0 to (bank_address_p-1) generate"
set line_num 236; puts $output_file "		attribute xc_props of iob_ba: label is \"IOB=TRUE\";"
set line_num 237; puts $output_file "	begin"
set line_num 238; puts $output_file "		iob_ba: FD port map ( "
set line_num 239; puts $output_file "               Q => buf_ba(bit_index),"
set line_num 240; puts $output_file "               D => ddr_ba(bit_index),"
set line_num 241; puts $output_file "               C => clk180"
set line_num 242; puts $output_file "                );"
set line_num 243; puts $output_file "    end generate;"
set line_num 244; puts $output_file "                                                        "
set line_num 245; puts $output_file "---- ************************************* ----"
set line_num 246; puts $output_file "----  Output buffers for control signals   ----"
set line_num 247; puts $output_file "---- ************************************* ----"
set line_num 248; puts $output_file ""
set line_num 249; puts $output_file "iobuf_web : OBUF port map ("
set line_num 250; puts $output_file "                     I => buf_web,"
set line_num 251; puts $output_file "                     O => pad_web);"
set line_num 252; puts $output_file ""
set line_num 253; puts $output_file "iobuf_rasb : OBUF port map ("
set line_num 254; puts $output_file "                     I => buf_rasb,"
set line_num 255; puts $output_file "                     O => pad_rasb);"
set line_num 256; puts $output_file ""
set line_num 257; puts $output_file "iobuf_casb : OBUF port map ("
set line_num 258; puts $output_file "                     I => buf_casb,"
set line_num 259; puts $output_file "                     O => pad_casb);"
set line_num 260; puts $output_file ""
set line_num 261; puts $output_file "iobuf_cke : OBUF port map ("
set line_num 262; puts $output_file "                     I => buf_cke,"
set line_num 263; puts $output_file "                     O => pad_cke);"
set line_num 264; puts $output_file ""
set line_num 265; puts $output_file "iobuf_csb0 : OBUF port map ("
set line_num 266; puts $output_file "                     I => buf_csb(0),"
set line_num 267; puts $output_file "                     O => pad_csb(0));"
set line_num 268; puts $output_file ""
set line_num 269; puts $output_file "iobuf_csb1 : OBUF port map ("
set line_num 270; puts $output_file "                     I => buf_csb(1),"
set line_num 271; puts $output_file "                     O => pad_csb(1));"
set line_num 272; puts $output_file ""
set line_num 273; puts $output_file "iobuf_ODT0 : OBUF port map ("
set line_num 274; puts $output_file "                     I => buf_ODT(0),"
set line_num 275; puts $output_file "                     O => pad_ODT(0));"
set line_num 276; puts $output_file ""
set line_num 277; puts $output_file "iobuf_ODT1 : OBUF port map ("
set line_num 278; puts $output_file "                     I => buf_ODT(1),"
set line_num 279; puts $output_file "                     O => pad_ODT(1));"
set line_num 280; puts $output_file ""
set line_num 281; puts $output_file "iobuf_rst_dqs_div_out : OBUF port map ("
set line_num 282; puts $output_file "                     I => buf_rst_dqs_div_out,"
set line_num 283; puts $output_file "                     O => pad_rst_dqs_div_out);"
set line_num 284; puts $output_file ""
set line_num 285; puts $output_file "iobuf_rst_dqs_div_in : IBUF port map ("
set line_num 286; puts $output_file "                     I => pad_rst_dqs_div_in,"
set line_num 287; puts $output_file "                     O => buf_rst_dqs_div_in);"
set line_num 288; puts $output_file ""
set line_num 289; puts $output_file "ddr_rst_dqs_div_in <= buf_rst_dqs_div_in;"
set line_num 290; puts $output_file ""
set line_num 291; puts $output_file "---- ************************************* ----"
set line_num 292; puts $output_file "----  Output buffers for address signals   ----"
set line_num 293; puts $output_file "---- ************************************* ----"
set line_num 294; puts $output_file ""
set line_num 295; puts $output_file "gen_iobuf_address: for i in (row_address_p -1) downto 0 generate"
set line_num 296; puts $output_file "		iobuf_address:OBUF port map ("
set line_num 297; puts $output_file "                     I => buf_address(i),"
set line_num 298; puts $output_file "                     O => pad_address(i));"
set line_num 299; puts $output_file "end generate;"
set line_num 300; puts $output_file ""
set line_num 301; puts $output_file "gen_iobuf_ba: for i in (bank_address_p -1) downto 0 generate"
set line_num 302; puts $output_file "		iobuf_ba:OBUF port map ("
set line_num 303; puts $output_file "                     I => buf_ba(i),"
set line_num 304; puts $output_file "                     O => pad_ba(i));"
set line_num 305; puts $output_file "end generate;                     "
set line_num 306; puts $output_file ""
set line_num 307; puts $output_file ""
set line_num 308; puts $output_file ""
set line_num 309; puts $output_file "end arc_controller_iobs;                "
set line_num 310; puts $output_file "         "
set line_num 311; puts $output_file " "
set line_num 312; puts $output_file ""
set line_num 313; puts $output_file ""
set line_num 314; puts $output_file ""
set line_num 315; puts $output_file ""
set line_num 316; puts $output_file "   "
set line_num 317; puts $output_file ""
close $output_file
