webtalk_init -webtalk_dir C:/XilinxProjects/ip_repo/adc16G4X_datarx/simproj/simproj.sim/sim_1/behav/xsim/xsim.dir/gty_wrapper_t_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Jan  9 10:50:54 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2708876" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "668b0e7b-1639-483c-b430-47469e60b02d" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "fb5fe3bdc0624741b3a2ce8fec952afd" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "18" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1992 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "10 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "4" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "39.03_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "214536_KB" -context "xsim\\usage"
webtalk_transmit -clientid 574034459 -regid "" -xml C:/XilinxProjects/ip_repo/adc16G4X_datarx/simproj/simproj.sim/sim_1/behav/xsim/xsim.dir/gty_wrapper_t_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/XilinxProjects/ip_repo/adc16G4X_datarx/simproj/simproj.sim/sim_1/behav/xsim/xsim.dir/gty_wrapper_t_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/XilinxProjects/ip_repo/adc16G4X_datarx/simproj/simproj.sim/sim_1/behav/xsim/xsim.dir/gty_wrapper_t_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
