#!/bin/bash

# Generate PROM programming files for an iBob using Impact to ensure correct
# config clocking options.

# DEST is the leading part (i.e. all but extension) of the output filenames.
# If not given, the names will be derived from the "gen_prog_files" script.
DEST="$1"

if [ -z "${DEST}" ]
then
  DEST="$(awk 'NR==2{print $3}' "$(dirname $0)/gen_prog_files")"
fi

DIR=$(dirname $DEST)
FILE=$(basename $DEST .bit)

impact -batch <<-EOF
setMode -pff
setSubmode -pffserial
addDesign -version 0 -name "00"
addDeviceChain -index 0
addPromDevice -p 1 -name xcf32p
addDevice -p 1 -file "implementation/download.bit"
setAttribute -configdevice -attr fillValue -value "FF"
setAttribute -configdevice -attr fileFormat -value "mcs"
setAttribute -configdevice -attr dir -value "UP"
setAttribute -configdevice -attr path -value "${DIR}"
setAttribute -configdevice -attr name -value "${FILE}"
generate
exit
EOF
echo
