set output_file [open "mem_tester_sim/ddr2_controller_v1_00_a/data/ddr2_controller_v2_1_0.mpd" w ]
set line_num 1; puts $output_file "###################################################################"
set line_num 2; puts $output_file "##"
set line_num 3; puts $output_file "## Name     : ddr2_controller"
set line_num 4; puts $output_file "## Desc     : BEE2 DDR2 Memory controller"
set line_num 5; puts $output_file "##            User ports : ${USER_IFS}"
set line_num 6; puts $output_file "##            DIMM ports : ${DIMM_NUMS}"
set line_num 7; puts $output_file "##"
set line_num 8; puts $output_file "###################################################################"
set line_num 9; puts $output_file ""
set line_num 10; puts $output_file "BEGIN ddr2_controller"
set line_num 11; puts $output_file ""
set line_num 12; puts $output_file "## Peripheral Options"
set line_num 13; puts $output_file "OPTION IPTYPE = IP"
set line_num 14; puts $output_file "OPTION IMP_NETLIST = TRUE"
set line_num 15; puts $output_file "OPTION HDL = VHDL"
set line_num 16; puts $output_file "OPTION IP_GROUP = MICROBLAZE:PPC:USER"
set line_num 17; puts $output_file "OPTION CORE_STATE = ACTIVE"
set line_num 18; puts $output_file "OPTION STYLE = BLACKBOX"
set line_num 19; puts $output_file ""
set line_num 20; puts $output_file "## Ports"
set line_num 21; puts $output_file ""
set line_num 22; puts $output_file "	## USER interfaces"
set line_num 23; puts $output_file ""
set line_num 24;  foreach i $DIMM_NUMS {
set line_num 25;  set user_name [lindex $USER_IFS [expr $i-1]]
set line_num 26; puts $output_file "	## USER ${user_name} interface"
set line_num 27; puts $output_file "	PORT ${user_name}_input_data          = \"\", DIR = I, VEC = \[143:0\]"
set line_num 28; puts $output_file "	PORT ${user_name}_byte_enable         = \"\", DIR = I, VEC = \[17:0\]"
set line_num 29; puts $output_file "	PORT ${user_name}_get_data            = \"\", DIR = O"
set line_num 30; puts $output_file "	PORT ${user_name}_output_data         = \"\", DIR = O, VEC = \[143:0\]"
set line_num 31; puts $output_file "	PORT ${user_name}_data_valid          = \"\", DIR = O"
set line_num 32; puts $output_file "	PORT ${user_name}_address             = \"\", DIR = I, VEC = \[31:0\]"
set line_num 33; puts $output_file "	PORT ${user_name}_read                = \"\", DIR = I"
set line_num 34; puts $output_file "	PORT ${user_name}_write               = \"\", DIR = I"
set line_num 35; puts $output_file "	PORT ${user_name}_ready               = \"\", DIR = O"
set line_num 36; puts $output_file ""
set line_num 37;  }
set line_num 38; puts $output_file ""
set line_num 39; puts $output_file "	## DIMM modules"
set line_num 40; puts $output_file ""
set line_num 41;  foreach i $DIMM_NUMS {
set line_num 42; puts $output_file "	## DIMM ${i} pads"
set line_num 43; puts $output_file "	PORT dimm${i}_rst_dqs_div_in  = \"\", IOB_STATE=BUF, THREE_STATE=FALSE, DIR = I"
set line_num 44; puts $output_file "	PORT dimm${i}_rst_dqs_div_out = \"\", IOB_STATE=BUF, THREE_STATE=FALSE, DIR = O"
set line_num 45; puts $output_file "	PORT dimm${i}_cke             = \"\", IOB_STATE=BUF, THREE_STATE=FALSE, DIR = O"
set line_num 46; puts $output_file "	PORT dimm${i}_clk0            = \"\", IOB_STATE=BUF, THREE_STATE=FALSE, DIR = O"
set line_num 47; puts $output_file "	PORT dimm${i}_clk0b           = \"\", IOB_STATE=BUF, THREE_STATE=FALSE, DIR = O"
set line_num 48; puts $output_file "	PORT dimm${i}_clk1            = \"\", IOB_STATE=BUF, THREE_STATE=FALSE, DIR = O"
set line_num 49; puts $output_file "	PORT dimm${i}_clk1b           = \"\", IOB_STATE=BUF, THREE_STATE=FALSE, DIR = O"
set line_num 50; puts $output_file "	PORT dimm${i}_clk2            = \"\", IOB_STATE=BUF, THREE_STATE=FALSE, DIR = O"
set line_num 51; puts $output_file "	PORT dimm${i}_clk2b           = \"\", IOB_STATE=BUF, THREE_STATE=FALSE, DIR = O"
set line_num 52; puts $output_file "	PORT dimm${i}_csb             = \"\", IOB_STATE=BUF, THREE_STATE=FALSE, DIR = O, VEC = \[1:0\]"
set line_num 53; puts $output_file "	PORT dimm${i}_casb            = \"\", IOB_STATE=BUF, THREE_STATE=FALSE, DIR = O"
set line_num 54; puts $output_file "	PORT dimm${i}_rasb            = \"\", IOB_STATE=BUF, THREE_STATE=FALSE, DIR = O"
set line_num 55; puts $output_file "	PORT dimm${i}_web             = \"\", IOB_STATE=BUF, THREE_STATE=FALSE, DIR = O"
set line_num 56; puts $output_file "	PORT dimm${i}_ODT             = \"\", IOB_STATE=BUF, THREE_STATE=FALSE, DIR = O, VEC = \[1:0\]"
set line_num 57; puts $output_file "	PORT dimm${i}_address         = \"\", IOB_STATE=BUF, THREE_STATE=FALSE, DIR = O, VEC = \[13:0\]"
set line_num 58; puts $output_file "	PORT dimm${i}_ba              = \"\", IOB_STATE=BUF, THREE_STATE=FALSE, DIR = O, VEC = \[1:0\]"
set line_num 59; puts $output_file "	PORT dimm${i}_dm              = \"\", IOB_STATE=BUF, THREE_STATE=FALSE, DIR = O, VEC = \[8:0\]"
set line_num 60; puts $output_file "	PORT dimm${i}_dqs             = \"\", IOB_STATE=BUF, THREE_STATE=FALSE, DIR = IO, VEC = \[8:0\]"
set line_num 61; puts $output_file "	PORT dimm${i}_dq              = \"\", IOB_STATE=BUF, THREE_STATE=FALSE, DIR = IO, VEC = \[71:0\]"
set line_num 62; puts $output_file ""
set line_num 63;  }
set line_num 64; puts $output_file ""
set line_num 65; puts $output_file "	## System interface"
set line_num 66; puts $output_file "	PORT clk_in                   = \"\", DIR = I"
set line_num 67; puts $output_file "	PORT reset_in                 = \"\", DIR = I"
set line_num 68; puts $output_file ""
set line_num 69; puts $output_file "END"
set line_num 70; puts $output_file ""
close $output_file
