set output_file [open "mem_tester_sim/ddr2_controller_v1_00_a/hdl/vhdl/ddr2_cntrl_72bit_rl.vhd" w ]
set line_num 1; puts $output_file "--******************************************************************************"
set line_num 2; puts $output_file "--"
set line_num 3; puts $output_file "--  Xilinx, Inc. 2002                 www.xilinx.com"
set line_num 4; puts $output_file "--"
set line_num 5; puts $output_file "--  XAPP 253 - Synthesizable DDR SDRAM Controller"
set line_num 6; puts $output_file "--"
set line_num 7; puts $output_file "--*******************************************************************************"
set line_num 8; puts $output_file "--"
set line_num 9; puts $output_file "--  File name :       ddr2_cntrl_72bit_rl"
set line_num 10; puts $output_file "--"
set line_num 11; puts $output_file "--  Description :     "
set line_num 12; puts $output_file "--                    Main DDR SDRAM controller block. This includes the following"
set line_num 13; puts $output_file "--                    features:"
set line_num 14; puts $output_file "--                    - The main controller state machine that controlls the "
set line_num 15; puts $output_file "--                    initialization process upon power up, as well as the "
set line_num 16; puts $output_file "--                    read, write, and refresh commands. "
set line_num 17; puts $output_file "--                    - handles the data path during READ and WRITEs."
set line_num 18; puts $output_file "--                    - Generates control signals for other modules, including the"
set line_num 19; puts $output_file "--                      data strobe(DQS) signal"
set line_num 20; puts $output_file "--"
set line_num 21; puts $output_file "--  Date - revision : 05/01/2002"
set line_num 22; puts $output_file "--"
set line_num 23; puts $output_file "--  Author :          Lakshmi Gopalakrishnan ( Modified by Sailaja)"
set line_num 24; puts $output_file "--"
set line_num 25; puts $output_file "--  Contact : e-mail  hotline@xilinx.com"
set line_num 26; puts $output_file "--            phone   + 1 800 255 7778 "
set line_num 27; puts $output_file "--"
set line_num 28; puts $output_file "--  Disclaimer: LIMITED WARRANTY AND DISCLAMER. These designs are "
set line_num 29; puts $output_file "--              provided to you \"as is\". Xilinx and its licensors make and you "
set line_num 30; puts $output_file "--              receive no warranties or conditions, express, implied, "
set line_num 31; puts $output_file "--              statutory or otherwise, and Xilinx specifically disclaims any "
set line_num 32; puts $output_file "--              implied warranties of merchantability, non-infringement, or "
set line_num 33; puts $output_file "--              fitness for a particular purpose. Xilinx does not warrant that "
set line_num 34; puts $output_file "--              the functions contained in these designs will meet your "
set line_num 35; puts $output_file "--              requirements, or that the operation of these designs will be "
set line_num 36; puts $output_file "--              uninterrupted or error free, or that defects in the Designs "
set line_num 37; puts $output_file "--              will be corrected. Furthermore, Xilinx does not warrant or "
set line_num 38; puts $output_file "--              make any representations regarding use or the results of the "
set line_num 39; puts $output_file "--              use of the designs in terms of correctness, accuracy, "
set line_num 40; puts $output_file "--              reliability, or otherwise. "
set line_num 41; puts $output_file "--"
set line_num 42; puts $output_file "--              LIMITATION OF LIABILITY. In no event will Xilinx or its "
set line_num 43; puts $output_file "--              licensors be liable for any loss of data, lost profits, cost "
set line_num 44; puts $output_file "--              or procurement of substitute goods or services, or for any "
set line_num 45; puts $output_file "--              special, incidental, consequential, or indirect damages "
set line_num 46; puts $output_file "--              arising from the use or operation of the designs or "
set line_num 47; puts $output_file "--              accompanying documentation, however caused and on any theory "
set line_num 48; puts $output_file "--              of liability. This limitation will apply even if Xilinx "
set line_num 49; puts $output_file "--              has been advised of the possibility of such damage. This "
set line_num 50; puts $output_file "--              limitation shall apply not-withstanding the failure of the "
set line_num 51; puts $output_file "--              essential purpose of any limited remedies herein. "
set line_num 52; puts $output_file "--"
set line_num 53; puts $output_file "--  Copyright © 2002 Xilinx, Inc."
set line_num 54; puts $output_file "--  All rights reserved "
set line_num 55; puts $output_file "-- "
set line_num 56; puts $output_file "--*****************************************************************************"
set line_num 57; puts $output_file "library ieee;"
set line_num 58; puts $output_file "use ieee.std_logic_1164.all;"
set line_num 59; puts $output_file "use ieee.std_logic_unsigned.all;"
set line_num 60; puts $output_file "use work.parameter.all;"
set line_num 61; puts $output_file "--library synplify; "
set line_num 62; puts $output_file "--use synplify.attributes.all;"
set line_num 63; puts $output_file "--"
set line_num 64; puts $output_file "-- pragma translate_off"
set line_num 65; puts $output_file "library UNISIM;"
set line_num 66; puts $output_file "use UNISIM.VCOMPONENTS.ALL;"
set line_num 67; puts $output_file "-- pragma translate_on"
set line_num 68; puts $output_file "--"
set line_num 69; puts $output_file "----------------------------------------"
set line_num 70; puts $output_file "-- ENTITY DECLARATION"
set line_num 71; puts $output_file "----------------------------------------"
set line_num 72; puts $output_file "entity   ddr2_cntrl_72bit_rl  is"
set line_num 73; puts $output_file "port("
set line_num 74; puts $output_file "	-- system interface"
set line_num 75; puts $output_file "	sys_clk_int            : in std_logic; "
set line_num 76; puts $output_file "	sys_clk90_int          : in std_logic; "
set line_num 77; puts $output_file "	sys_delay_sel_val      : in std_logic_vector(4 downto 0); "
set line_num 78; puts $output_file "	sys_rst                : in std_logic; "
set line_num 79; puts $output_file "	sys_rst90              : in std_logic; "
set line_num 80; puts $output_file "	sys_rst180             : in std_logic; "
set line_num 81; puts $output_file "	sys_rst270             : in std_logic; "
set line_num 82; puts $output_file ""
set line_num 83; puts $output_file "	-- user interface"
set line_num 84; puts $output_file "	user_input_data        : in  STD_LOGIC_VECTOR(143 downto 0);"
set line_num 85; puts $output_file "	user_byte_enable       : in  STD_LOGIC_VECTOR(17 downto 0);"
set line_num 86; puts $output_file "	user_get_data          : out STD_LOGIC;"
set line_num 87; puts $output_file "	user_output_data       : out STD_LOGIC_VECTOR(143 downto 0):=(OTHERS => 'Z');"
set line_num 88; puts $output_file "	user_data_valid        : out STD_LOGIC;"
set line_num 89; puts $output_file "	user_col_address       : in  STD_LOGIC_VECTOR((column_address_p - 1) downto 0);"
set line_num 90; puts $output_file "	user_row_address       : in  STD_LOGIC_VECTOR((row_address_p - 1) downto 0);"
set line_num 91; puts $output_file "	user_bank_address      : in  STD_LOGIC_VECTOR((bank_address_p - 1) downto 0);"
set line_num 92; puts $output_file "	user_rank_address      : in  STD_LOGIC;"
set line_num 93; puts $output_file "	user_read              : in  STD_LOGIC;"
set line_num 94; puts $output_file "	user_write             : in  STD_LOGIC;"
set line_num 95; puts $output_file "	user_ready             : out  STD_LOGIC;"
set line_num 96; puts $output_file ""
set line_num 97; puts $output_file "	-- pads"
set line_num 98; puts $output_file "	pad_rst_dqs_div_in     : in std_logic;"
set line_num 99; puts $output_file "	pad_rst_dqs_div_out    : out std_logic;"
set line_num 100; puts $output_file "	pad_dqs                : inout std_logic_vector(8 downto 0);"
set line_num 101; puts $output_file "	pad_dq                 : inout std_logic_vector(71 downto 0):= (OTHERS => 'Z');"
set line_num 102; puts $output_file "	pad_cke                : out std_logic;"
set line_num 103; puts $output_file "	pad_csb                : out std_logic_vector(1 downto 0);"
set line_num 104; puts $output_file "	pad_rasb               : out std_logic;"
set line_num 105; puts $output_file "	pad_casb               : out std_logic;"
set line_num 106; puts $output_file "	pad_web                : out std_logic;"
set line_num 107; puts $output_file "	pad_dm                 : out std_logic_vector(8 downto 0);  "
set line_num 108; puts $output_file "	pad_ba                 : out std_logic_vector((bank_address_p-1) downto 0);"
set line_num 109; puts $output_file "	pad_address            : out std_logic_vector((row_address_p-1) downto 0);"
set line_num 110; puts $output_file "	pad_ODT                : out std_logic_vector(1 downto 0);"
set line_num 111; puts $output_file "	pad_clk0               : out std_logic;"
set line_num 112; puts $output_file "	pad_clk0b              : out std_logic;"
set line_num 113; puts $output_file "	pad_clk1               : out std_logic;"
set line_num 114; puts $output_file "	pad_clk1b              : out std_logic;"
set line_num 115; puts $output_file "	pad_clk2               : out std_logic;"
set line_num 116; puts $output_file "	pad_clk2b              : out std_logic"
set line_num 117; puts $output_file ""
set line_num 118; puts $output_file ");"
set line_num 119; puts $output_file "end   ddr2_cntrl_72bit_rl;  "
set line_num 120; puts $output_file ""
set line_num 121; puts $output_file "----------------------------------------"
set line_num 122; puts $output_file "-- ARCHITECTURE DECLARATION"
set line_num 123; puts $output_file "----------------------------------------"
set line_num 124; puts $output_file ""
set line_num 125; puts $output_file "architecture   arc_ddr2_cntrl_72bit_rl of   ddr2_cntrl_72bit_rl    is"
set line_num 126; puts $output_file ""
set line_num 127; puts $output_file "----------------------------------------"
set line_num 128; puts $output_file "-- state machine controller declaration"
set line_num 129; puts $output_file "----------------------------------------"
set line_num 130; puts $output_file "component controller "
set line_num 131; puts $output_file "port("
set line_num 132; puts $output_file "	-- system signals"
set line_num 133; puts $output_file "	clk                    : in std_logic;"
set line_num 134; puts $output_file "	reset                  : in std_logic;"
set line_num 135; puts $output_file ""
set line_num 136; puts $output_file "	-- user interface"
set line_num 137; puts $output_file "	user_get_data          : out STD_LOGIC;"
set line_num 138; puts $output_file "	user_col_address       : in  STD_LOGIC_VECTOR((column_address_p - 1) downto 0);"
set line_num 139; puts $output_file "	user_row_address       : in  STD_LOGIC_VECTOR((row_address_p - 1) downto 0);"
set line_num 140; puts $output_file "	user_bank_address      : in  STD_LOGIC_VECTOR((bank_address_p - 1) downto 0);"
set line_num 141; puts $output_file "	user_rank_address      : in  STD_LOGIC;"
set line_num 142; puts $output_file "	user_read              : in  STD_LOGIC;"
set line_num 143; puts $output_file "	user_write             : in  STD_LOGIC;"
set line_num 144; puts $output_file "	user_ready             : out STD_LOGIC;"
set line_num 145; puts $output_file ""
set line_num 146; puts $output_file "	-- pads"
set line_num 147; puts $output_file "	ddr_rasb               : out std_logic;"
set line_num 148; puts $output_file "	ddr_casb               : out std_logic;"
set line_num 149; puts $output_file "	ddr_ODT                : out std_logic_vector(1 downto 0);"
set line_num 150; puts $output_file "	ddr_web                : out std_logic;"
set line_num 151; puts $output_file "	ddr_ba                 : out std_logic_vector((bank_address_p-1) downto 0);"
set line_num 152; puts $output_file "	ddr_address            : out std_logic_vector((row_address_p-1) downto 0);"
set line_num 153; puts $output_file "	ddr_cke                : out std_logic;"
set line_num 154; puts $output_file "	ddr_csb                : out std_logic_vector(1 downto 0);"
set line_num 155; puts $output_file "	ddr_rst_dqs_div_out    : out std_logic;"
set line_num 156; puts $output_file "	ddr_force_nop          : out std_logic_vector(1 downto 0);"
set line_num 157; puts $output_file "	"
set line_num 158; puts $output_file "	-- data path control"
set line_num 159; puts $output_file "	dqs_enable             : out std_logic;"
set line_num 160; puts $output_file "	dqs_reset              : out std_logic;"
set line_num 161; puts $output_file "	write_enable           : out std_logic;"
set line_num 162; puts $output_file "	input_data_valid       : out std_logic;"
set line_num 163; puts $output_file ""
set line_num 164; puts $output_file "	-- infrastructure control"
set line_num 165; puts $output_file "	rst_calib              : out std_logic"
set line_num 166; puts $output_file ");"
set line_num 167; puts $output_file "end component;                                    "
set line_num 168; puts $output_file ""
set line_num 169; puts $output_file "----------------------------------------"
set line_num 170; puts $output_file "-- data path declaration"
set line_num 171; puts $output_file "----------------------------------------"
set line_num 172; puts $output_file "component	data_path_72bit_rl "
set line_num 173; puts $output_file "port("
set line_num 174; puts $output_file "	-- system ports"
set line_num 175; puts $output_file "	clk                    : in std_logic;"
set line_num 176; puts $output_file "	clk90                  : in std_logic;"
set line_num 177; puts $output_file "	reset                  : in std_logic;"
set line_num 178; puts $output_file "	reset90                : in std_logic;"
set line_num 179; puts $output_file "	reset180               : in std_logic;"
set line_num 180; puts $output_file "	reset270               : in std_logic;"
set line_num 181; puts $output_file "	delay_sel              : in std_logic_vector(4 downto 0);   "
set line_num 182; puts $output_file ""
set line_num 183; puts $output_file "	-- data ports (on clk0)"
set line_num 184; puts $output_file "	input_data             : in std_logic_vector(143 downto 0);"
set line_num 185; puts $output_file "	write_enable           : in std_logic;"
set line_num 186; puts $output_file "	input_data_valid       : in std_logic;"
set line_num 187; puts $output_file "	byte_enable            : in std_logic_vector(17 downto 0);"
set line_num 188; puts $output_file "	output_data_valid      : out std_logic;"
set line_num 189; puts $output_file "	output_data            : out std_logic_vector(143 downto 0);"
set line_num 190; puts $output_file ""
set line_num 191; puts $output_file "	-- iobs ports"
set line_num 192; puts $output_file "	ddr_dqs_int_delay_in0  : in std_logic;"
set line_num 193; puts $output_file "	ddr_dqs_int_delay_in1  : in std_logic;"
set line_num 194; puts $output_file "	ddr_dqs_int_delay_in2  : in std_logic;"
set line_num 195; puts $output_file "	ddr_dqs_int_delay_in3  : in std_logic;"
set line_num 196; puts $output_file "	ddr_dqs_int_delay_in4  : in std_logic;"
set line_num 197; puts $output_file "	ddr_dqs_int_delay_in5  : in std_logic;"
set line_num 198; puts $output_file "	ddr_dqs_int_delay_in6  : in std_logic;"
set line_num 199; puts $output_file "	ddr_dqs_int_delay_in7  : in std_logic;"
set line_num 200; puts $output_file "	ddr_dqs_int_delay_in8  : in std_logic;  "
set line_num 201; puts $output_file "	ddr_dq                 : in std_logic_vector(71 downto 0);       "
set line_num 202; puts $output_file "	ddr_rst_dqs_div_in     : in std_logic;"
set line_num 203; puts $output_file "	ddr_write_en           : out std_logic;"
set line_num 204; puts $output_file "	ddr_data_mask_falling  : out std_logic_vector(8 downto 0);"
set line_num 205; puts $output_file "	ddr_data_mask_rising   : out std_logic_vector(8 downto 0);"
set line_num 206; puts $output_file "	ddr_write_data_falling : out std_logic_vector(71 downto 0);"
set line_num 207; puts $output_file "	ddr_write_data_rising  : out std_logic_vector(71 downto 0)"
set line_num 208; puts $output_file ");"
set line_num 209; puts $output_file "end component;"
set line_num 210; puts $output_file ""
set line_num 211; puts $output_file "----------------------------------------"
set line_num 212; puts $output_file "-- infrastructure declaration"
set line_num 213; puts $output_file "----------------------------------------"
set line_num 214; puts $output_file "component infrastructure"
set line_num 215; puts $output_file "port("
set line_num 216; puts $output_file "	sys_rst                : in std_logic;"
set line_num 217; puts $output_file "	clk_int                : in std_logic;"
set line_num 218; puts $output_file "	rst_calib1             : in std_logic;"
set line_num 219; puts $output_file "	delay_sel_val          : in std_logic_vector(4 downto 0);"
set line_num 220; puts $output_file "	delay_sel_val1_val     : out std_logic_vector(4 downto 0)"
set line_num 221; puts $output_file ");"
set line_num 222; puts $output_file "end component;"
set line_num 223; puts $output_file ""
set line_num 224; puts $output_file "----------------------------------------"
set line_num 225; puts $output_file "-- IO pads declaration"
set line_num 226; puts $output_file "----------------------------------------"
set line_num 227; puts $output_file "component	iobs_72bit "
set line_num 228; puts $output_file "port("
set line_num 229; puts $output_file "	-- system ports"
set line_num 230; puts $output_file "	clk                    : in std_logic;"
set line_num 231; puts $output_file "	clk90                  : in std_logic;"
set line_num 232; puts $output_file "	reset                  : in std_logic;"
set line_num 233; puts $output_file "	reset90                : in std_logic;"
set line_num 234; puts $output_file "	reset180               : in std_logic;"
set line_num 235; puts $output_file "	reset270               : in std_logic;"
set line_num 236; puts $output_file ""
set line_num 237; puts $output_file "	-- signals from/to the fabric  "
set line_num 238; puts $output_file "	ddr_rasb               : in std_logic;"
set line_num 239; puts $output_file "	ddr_casb               : in std_logic;"
set line_num 240; puts $output_file "	ddr_web                : in std_logic;"
set line_num 241; puts $output_file "	ddr_cke                : in std_logic;"
set line_num 242; puts $output_file "	ddr_csb                : in std_logic_vector(1 downto 0);"
set line_num 243; puts $output_file "	ddr_ODT                : in std_logic_vector(1 downto 0);"
set line_num 244; puts $output_file "	ddr_address            : in std_logic_vector((row_address_p-1) downto 0);"
set line_num 245; puts $output_file "	ddr_ba                 : in std_logic_vector((bank_address_p-1) downto 0);"
set line_num 246; puts $output_file "	ddr_write_data_falling : in std_logic_vector(71 downto 0);"
set line_num 247; puts $output_file "	ddr_write_data_rising  : in std_logic_vector(71 downto 0);"
set line_num 248; puts $output_file "	ddr_data_mask_falling  : in std_logic_vector(8 downto 0);"
set line_num 249; puts $output_file "	ddr_data_mask_rising   : in std_logic_vector(8 downto 0);                                                                           "
set line_num 250; puts $output_file "	ddr_rst_dqs_div_out    : in std_logic;"
set line_num 251; puts $output_file "	ddr_rst_dqs_div_in     : out std_logic;"
set line_num 252; puts $output_file "	ddr_dqs_int_delay_in0  : out std_logic;"
set line_num 253; puts $output_file "	ddr_dqs_int_delay_in1  : out std_logic;"
set line_num 254; puts $output_file "	ddr_dqs_int_delay_in2  : out std_logic;"
set line_num 255; puts $output_file "	ddr_dqs_int_delay_in3  : out std_logic;"
set line_num 256; puts $output_file "	ddr_dqs_int_delay_in4  : out std_logic;"
set line_num 257; puts $output_file "	ddr_dqs_int_delay_in5  : out std_logic;"
set line_num 258; puts $output_file "	ddr_dqs_int_delay_in6  : out std_logic;"
set line_num 259; puts $output_file "	ddr_dqs_int_delay_in7  : out std_logic;"
set line_num 260; puts $output_file "	ddr_dqs_int_delay_in8  : out std_logic;"
set line_num 261; puts $output_file "	ddr_dq                 : out std_logic_vector(71 downto 0);"
set line_num 262; puts $output_file "	ddr_force_nop          : in  std_logic_vector(1 downto 0);"
set line_num 263; puts $output_file ""
set line_num 264; puts $output_file "	-- I/O pads"
set line_num 265; puts $output_file "	pad_dqs                : inout std_logic_vector(8 downto 0);                                                                                        "
set line_num 266; puts $output_file "	pad_dq                 : inout std_logic_vector(71 downto 0);"
set line_num 267; puts $output_file "	pad_dm                 : out std_logic_vector(8 downto 0);"
set line_num 268; puts $output_file "	pad_clk0               : out std_logic;"
set line_num 269; puts $output_file "	pad_clk0b              : out std_logic;"
set line_num 270; puts $output_file "	pad_clk1               : out std_logic;"
set line_num 271; puts $output_file "	pad_clk1b              : out std_logic;"
set line_num 272; puts $output_file "	pad_clk2               : out std_logic;"
set line_num 273; puts $output_file "	pad_clk2b              : out std_logic;"
set line_num 274; puts $output_file "	pad_rasb               : out std_logic;"
set line_num 275; puts $output_file "	pad_casb               : out std_logic;"
set line_num 276; puts $output_file "	pad_web                : out std_logic;"
set line_num 277; puts $output_file "	pad_ba                 : out std_logic_vector((bank_address_p-1) downto 0);"
set line_num 278; puts $output_file "	pad_address            : out std_logic_vector((row_address_p-1) downto 0);"
set line_num 279; puts $output_file "	pad_cke                : out std_logic;"
set line_num 280; puts $output_file "	pad_csb                : out std_logic_vector(1 downto 0);"
set line_num 281; puts $output_file "	pad_ODT                : out std_logic_vector(1 downto 0);"
set line_num 282; puts $output_file "	pad_rst_dqs_div_in     : in std_logic;"
set line_num 283; puts $output_file "	pad_rst_dqs_div_out    : out std_logic;"
set line_num 284; puts $output_file ""
set line_num 285; puts $output_file "	-- control signals"
set line_num 286; puts $output_file "	ctrl_dqs_reset         : in std_logic;"
set line_num 287; puts $output_file "	ctrl_dqs_enable        : in std_logic;   "
set line_num 288; puts $output_file "	ctrl_write_en          : in std_logic"
set line_num 289; puts $output_file ""
set line_num 290; puts $output_file ");"
set line_num 291; puts $output_file "end component;"
set line_num 292; puts $output_file ""
set line_num 293; puts $output_file "                                 "
set line_num 294; puts $output_file "----------------------------------------"
set line_num 295; puts $output_file "-- signals declaration"
set line_num 296; puts $output_file "----------------------------------------"
set line_num 297; puts $output_file ""
set line_num 298; puts $output_file "	-- infrastructure signals"
set line_num 299; puts $output_file "	signal rst_calib              : std_logic;"
set line_num 300; puts $output_file "	signal rst_calib_180          : std_logic;"
set line_num 301; puts $output_file "	signal delay_sel              : std_logic_vector(4 downto 0);"
set line_num 302; puts $output_file ""
set line_num 303; puts $output_file "	-- controller local resets"
set line_num 304; puts $output_file "	signal local_rst              : std_logic := '1';"
set line_num 305; puts $output_file "	signal local_rst90            : std_logic := '1';"
set line_num 306; puts $output_file "	signal local_rst180           : std_logic := '1';"
set line_num 307; puts $output_file "	signal local_rst270           : std_logic := '1';"
set line_num 308; puts $output_file ""
set line_num 309; puts $output_file "	-- state machine controller signals"
set line_num 310; puts $output_file "	signal ddr_rasb               :  std_logic;"
set line_num 311; puts $output_file "	signal ddr_casb               :  std_logic;"
set line_num 312; puts $output_file "	signal ddr_web                :  std_logic;"
set line_num 313; puts $output_file "	signal ddr_ba                 :  std_logic_vector((bank_address_p-1) downto 0);"
set line_num 314; puts $output_file "	signal ddr_address            :  std_logic_vector((row_address_p-1) downto 0);"
set line_num 315; puts $output_file "	signal ddr_cke                :  std_logic;"
set line_num 316; puts $output_file "	signal ddr_csb                :  std_logic_vector(1 downto 0);"
set line_num 317; puts $output_file "	signal ddr_ODT                :  std_logic_vector(1 downto 0);"
set line_num 318; puts $output_file "	signal ddr_force_nop          :  std_logic_vector(1 downto 0);"
set line_num 319; puts $output_file ""
set line_num 320; puts $output_file "	-- data path signals"
set line_num 321; puts $output_file "	-- control"
set line_num 322; puts $output_file "	signal write_enable           : std_logic;"
set line_num 323; puts $output_file "	signal dqs_enable             : std_logic;"
set line_num 324; puts $output_file "	signal dqs_reset              : std_logic;"
set line_num 325; puts $output_file "	signal input_data_valid       : std_logic;"
set line_num 326; puts $output_file "	-- active signals"
set line_num 327; puts $output_file "	signal ddr_rst_dqs_div_in     : std_logic;"
set line_num 328; puts $output_file "	signal ddr_rst_dqs_div_out    : std_logic;"
set line_num 329; puts $output_file "	signal ddr_dqs_int_delay_in0  : std_logic;"
set line_num 330; puts $output_file "	signal ddr_dqs_int_delay_in1  : std_logic;"
set line_num 331; puts $output_file "	signal ddr_dqs_int_delay_in2  : std_logic;"
set line_num 332; puts $output_file "	signal ddr_dqs_int_delay_in3  : std_logic;"
set line_num 333; puts $output_file "	signal ddr_dqs_int_delay_in4  : std_logic;"
set line_num 334; puts $output_file "	signal ddr_dqs_int_delay_in5  : std_logic;"
set line_num 335; puts $output_file "	signal ddr_dqs_int_delay_in6  : std_logic;"
set line_num 336; puts $output_file "	signal ddr_dqs_int_delay_in7  : std_logic;"
set line_num 337; puts $output_file "	signal ddr_dqs_int_delay_in8  : std_logic;"
set line_num 338; puts $output_file "	signal ddr_dq                 : std_logic_vector(71 downto 0);"
set line_num 339; puts $output_file "	signal ddr_write_en           : std_logic;"
set line_num 340; puts $output_file "	signal ddr_data_mask_falling  : std_logic_vector(8 downto 0);"
set line_num 341; puts $output_file "	signal ddr_data_mask_rising   : std_logic_vector(8 downto 0);"
set line_num 342; puts $output_file "	signal ddr_write_data_falling : std_logic_vector(71 downto 0);"
set line_num 343; puts $output_file "	signal ddr_write_data_rising  : std_logic_vector(71 downto 0);"
set line_num 344; puts $output_file ""
set line_num 345; puts $output_file "begin"
set line_num 346; puts $output_file ""
set line_num 347; puts $output_file "----------------------------------------"
set line_num 348; puts $output_file "-- state machine controller signals mapping"
set line_num 349; puts $output_file "----------------------------------------"
set line_num 350; puts $output_file "controller0 : controller port map ("
set line_num 351; puts $output_file "	-- system signals"
set line_num 352; puts $output_file "	clk                    => sys_clk_int        ,"
set line_num 353; puts $output_file "	reset                  => local_rst          ,"
set line_num 354; puts $output_file ""
set line_num 355; puts $output_file "	-- user interface"
set line_num 356; puts $output_file "	user_get_data          => user_get_data      ,"
set line_num 357; puts $output_file "	user_col_address       => user_col_address   ,"
set line_num 358; puts $output_file "	user_row_address       => user_row_address   ,"
set line_num 359; puts $output_file "	user_bank_address      => user_bank_address  ,"
set line_num 360; puts $output_file "	user_rank_address      => user_rank_address  ,"
set line_num 361; puts $output_file "	user_read              => user_read          ,"
set line_num 362; puts $output_file "	user_write             => user_write         ,"
set line_num 363; puts $output_file "	user_ready             => user_ready         ,"
set line_num 364; puts $output_file ""
set line_num 365; puts $output_file "	-- pads"
set line_num 366; puts $output_file "	ddr_rasb               => ddr_rasb           , "
set line_num 367; puts $output_file "	ddr_casb               => ddr_casb           , "
set line_num 368; puts $output_file "	ddr_ODT                => ddr_ODT            , "
set line_num 369; puts $output_file "	ddr_web                => ddr_web            , "
set line_num 370; puts $output_file "	ddr_ba                 => ddr_ba             , "
set line_num 371; puts $output_file "	ddr_address            => ddr_address        , "
set line_num 372; puts $output_file "	ddr_cke                => ddr_cke            , "
set line_num 373; puts $output_file "	ddr_csb                => ddr_csb            , "
set line_num 374; puts $output_file "	ddr_rst_dqs_div_out    => ddr_rst_dqs_div_out, "
set line_num 375; puts $output_file "	ddr_force_nop          => ddr_force_nop      ,"
set line_num 376; puts $output_file "	"
set line_num 377; puts $output_file "	-- data path control"
set line_num 378; puts $output_file "	dqs_enable             => dqs_enable         ,"
set line_num 379; puts $output_file "	dqs_reset              => dqs_reset          ,"
set line_num 380; puts $output_file "	write_enable           => write_enable       ,"
set line_num 381; puts $output_file "	input_data_valid       => input_data_valid   ,"
set line_num 382; puts $output_file ""
set line_num 383; puts $output_file "	-- infrastructure control"
set line_num 384; puts $output_file "	rst_calib              => rst_calib         "
set line_num 385; puts $output_file ");"
set line_num 386; puts $output_file ""
set line_num 387; puts $output_file "----------------------------------------"
set line_num 388; puts $output_file "-- data path signals mapping"
set line_num 389; puts $output_file "----------------------------------------"
set line_num 390; puts $output_file "data_path0	:	data_path_72bit_rl"
set line_num 391; puts $output_file "port	map	( "
set line_num 392; puts $output_file "	-- system ports"
set line_num 393; puts $output_file "	clk                    => sys_clk_int           ,"
set line_num 394; puts $output_file "	clk90                  => sys_clk90_int         ,"
set line_num 395; puts $output_file "	reset                  => local_rst             ,  "
set line_num 396; puts $output_file "	reset90                => local_rst90           ,"
set line_num 397; puts $output_file "	reset180               => local_rst180          ,"
set line_num 398; puts $output_file "	reset270               => local_rst270          ,"
set line_num 399; puts $output_file "	delay_sel              => delay_sel             ,   "
set line_num 400; puts $output_file ""
set line_num 401; puts $output_file "	-- data ports (on clk0)"
set line_num 402; puts $output_file "	input_data             => user_input_data       ,"
set line_num 403; puts $output_file "	write_enable           => write_enable          ,"
set line_num 404; puts $output_file "	byte_enable            => user_byte_enable      ,"
set line_num 405; puts $output_file "	output_data_valid      => user_data_valid       ,"
set line_num 406; puts $output_file "	output_data            => user_output_data      ,"
set line_num 407; puts $output_file "	input_data_valid       => input_data_valid      ,"
set line_num 408; puts $output_file ""
set line_num 409; puts $output_file "	-- iobs ports"
set line_num 410; puts $output_file "	ddr_dqs_int_delay_in0  => ddr_dqs_int_delay_in0 ,"
set line_num 411; puts $output_file "	ddr_dqs_int_delay_in1  => ddr_dqs_int_delay_in1 ,"
set line_num 412; puts $output_file "	ddr_dqs_int_delay_in2  => ddr_dqs_int_delay_in2 ,"
set line_num 413; puts $output_file "	ddr_dqs_int_delay_in3  => ddr_dqs_int_delay_in3 ,"
set line_num 414; puts $output_file "	ddr_dqs_int_delay_in4  => ddr_dqs_int_delay_in4 ,"
set line_num 415; puts $output_file "	ddr_dqs_int_delay_in5  => ddr_dqs_int_delay_in5 ,"
set line_num 416; puts $output_file "	ddr_dqs_int_delay_in6  => ddr_dqs_int_delay_in6 ,"
set line_num 417; puts $output_file "	ddr_dqs_int_delay_in7  => ddr_dqs_int_delay_in7 ,"
set line_num 418; puts $output_file "	ddr_dqs_int_delay_in8  => ddr_dqs_int_delay_in8 ,  "
set line_num 419; puts $output_file "	ddr_dq                 => ddr_dq                ,       "
set line_num 420; puts $output_file "	ddr_rst_dqs_div_in     => ddr_rst_dqs_div_in    ,"
set line_num 421; puts $output_file "	ddr_write_en           => ddr_write_en          ,"
set line_num 422; puts $output_file "	ddr_data_mask_falling  => ddr_data_mask_falling ,"
set line_num 423; puts $output_file "	ddr_data_mask_rising   => ddr_data_mask_rising  ,"
set line_num 424; puts $output_file "	ddr_write_data_falling => ddr_write_data_falling,"
set line_num 425; puts $output_file "	ddr_write_data_rising  => ddr_write_data_rising"
set line_num 426; puts $output_file ");                           "
set line_num 427; puts $output_file ""
set line_num 428; puts $output_file "----------------------------------------"
set line_num 429; puts $output_file "-- infrastructure signals mapping"
set line_num 430; puts $output_file "----------------------------------------"
set line_num 431; puts $output_file "infrastructure0 : infrastructure port map"
set line_num 432; puts $output_file "("
set line_num 433; puts $output_file "	sys_rst                => local_rst,"
set line_num 434; puts $output_file "	clk_int                => sys_clk_int,"
set line_num 435; puts $output_file "	rst_calib1             => rst_calib_180,"
set line_num 436; puts $output_file "	delay_sel_val          => sys_delay_sel_val,"
set line_num 437; puts $output_file "	delay_sel_val1_val     => delay_sel"
set line_num 438; puts $output_file "); "
set line_num 439; puts $output_file ""
set line_num 440; puts $output_file "----------------------------------------"
set line_num 441; puts $output_file "-- IO pads signals mapping"
set line_num 442; puts $output_file "----------------------------------------"
set line_num 443; puts $output_file "iobs0	:	iobs_72bit	port	map "
set line_num 444; puts $output_file "("
set line_num 445; puts $output_file "	-- system ports"
set line_num 446; puts $output_file "	clk                    => sys_clk_int           ,"
set line_num 447; puts $output_file "	clk90                  => sys_clk90_int         ,"
set line_num 448; puts $output_file "	reset                  => local_rst             ,  "
set line_num 449; puts $output_file "	reset90                => local_rst90           ,"
set line_num 450; puts $output_file "	reset180               => local_rst180          ,"
set line_num 451; puts $output_file "	reset270               => local_rst270          ,"
set line_num 452; puts $output_file ""
set line_num 453; puts $output_file "	-- signals from/to the fabric  "
set line_num 454; puts $output_file "	ddr_rasb               => ddr_rasb              , "
set line_num 455; puts $output_file "	ddr_casb               => ddr_casb              , "
set line_num 456; puts $output_file "	ddr_web                => ddr_web               , "
set line_num 457; puts $output_file "	ddr_cke                => ddr_cke               , "
set line_num 458; puts $output_file "	ddr_csb                => ddr_csb               , "
set line_num 459; puts $output_file "	ddr_ODT                => ddr_ODT               , "
set line_num 460; puts $output_file "	ddr_address            => ddr_address           , "
set line_num 461; puts $output_file "	ddr_ba                 => ddr_ba                , "
set line_num 462; puts $output_file "	ddr_write_data_falling => ddr_write_data_falling, "
set line_num 463; puts $output_file "	ddr_write_data_rising  => ddr_write_data_rising , "
set line_num 464; puts $output_file "	ddr_data_mask_falling  => ddr_data_mask_falling , "
set line_num 465; puts $output_file "	ddr_data_mask_rising   => ddr_data_mask_rising  ,                                                      "
set line_num 466; puts $output_file "	ddr_rst_dqs_div_out    => ddr_rst_dqs_div_out   , "
set line_num 467; puts $output_file "	ddr_rst_dqs_div_in     => ddr_rst_dqs_div_in    , "
set line_num 468; puts $output_file "	ddr_dqs_int_delay_in0  => ddr_dqs_int_delay_in0 , "
set line_num 469; puts $output_file "	ddr_dqs_int_delay_in1  => ddr_dqs_int_delay_in1 , "
set line_num 470; puts $output_file "	ddr_dqs_int_delay_in2  => ddr_dqs_int_delay_in2 , "
set line_num 471; puts $output_file "	ddr_dqs_int_delay_in3  => ddr_dqs_int_delay_in3 , "
set line_num 472; puts $output_file "	ddr_dqs_int_delay_in4  => ddr_dqs_int_delay_in4 , "
set line_num 473; puts $output_file "	ddr_dqs_int_delay_in5  => ddr_dqs_int_delay_in5 , "
set line_num 474; puts $output_file "	ddr_dqs_int_delay_in6  => ddr_dqs_int_delay_in6 , "
set line_num 475; puts $output_file "	ddr_dqs_int_delay_in7  => ddr_dqs_int_delay_in7 , "
set line_num 476; puts $output_file "	ddr_dqs_int_delay_in8  => ddr_dqs_int_delay_in8 , "
set line_num 477; puts $output_file "	ddr_dq                 => ddr_dq                , "
set line_num 478; puts $output_file "	ddr_force_nop          => ddr_force_nop         ,"
set line_num 479; puts $output_file "	"
set line_num 480; puts $output_file "	-- I/O pads"
set line_num 481; puts $output_file "	pad_dqs                => pad_dqs               ,                                                                     "
set line_num 482; puts $output_file "	pad_dq                 => pad_dq                ,"
set line_num 483; puts $output_file "	pad_dm                 => pad_dm                ,"
set line_num 484; puts $output_file "	pad_clk0               => pad_clk0              ,"
set line_num 485; puts $output_file "	pad_clk0b              => pad_clk0b             ,"
set line_num 486; puts $output_file "	pad_clk1               => pad_clk1              ,"
set line_num 487; puts $output_file "	pad_clk1b              => pad_clk1b             ,"
set line_num 488; puts $output_file "	pad_clk2               => pad_clk2              ,"
set line_num 489; puts $output_file "	pad_clk2b              => pad_clk2b             ,"
set line_num 490; puts $output_file "	pad_rasb               => pad_rasb              ,"
set line_num 491; puts $output_file "	pad_casb               => pad_casb              ,"
set line_num 492; puts $output_file "	pad_web                => pad_web               ,"
set line_num 493; puts $output_file "	pad_ba                 => pad_ba                ,"
set line_num 494; puts $output_file "	pad_address            => pad_address           ,"
set line_num 495; puts $output_file "	pad_cke                => pad_cke               ,"
set line_num 496; puts $output_file "	pad_csb                => pad_csb               ,"
set line_num 497; puts $output_file "	pad_ODT                => pad_ODT               ,"
set line_num 498; puts $output_file "	pad_rst_dqs_div_in     => pad_rst_dqs_div_in    ,"
set line_num 499; puts $output_file "	pad_rst_dqs_div_out    => pad_rst_dqs_div_out   ,"
set line_num 500; puts $output_file ""
set line_num 501; puts $output_file "	-- control signals"
set line_num 502; puts $output_file "	ctrl_dqs_reset         => dqs_reset             ,"
set line_num 503; puts $output_file "	ctrl_dqs_enable        => dqs_enable            ,   "
set line_num 504; puts $output_file "	ctrl_write_en          => ddr_write_en"
set line_num 505; puts $output_file ""
set line_num 506; puts $output_file ");"
set line_num 507; puts $output_file ""
set line_num 508; puts $output_file ""
set line_num 509; puts $output_file "-- delay the calibration reset by half a cycle"
set line_num 510; puts $output_file "calib_reset_delay: process(sys_clk_int)"
set line_num 511; puts $output_file "begin"
set line_num 512; puts $output_file "	if sys_clk_int'event and sys_clk_int = '0' then"
set line_num 513; puts $output_file "		if local_rst180 = '1' then"
set line_num 514; puts $output_file "			rst_calib_180 <= '0';"
set line_num 515; puts $output_file "		else"
set line_num 516; puts $output_file "			rst_calib_180 <= rst_calib;"
set line_num 517; puts $output_file "		end if;"
set line_num 518; puts $output_file "	end if;"
set line_num 519; puts $output_file "end process  calib_reset_delay;"
set line_num 520; puts $output_file "					"
set line_num 521; puts $output_file "-- controller local resets"
set line_num 522; puts $output_file "local_rst_proc: process(sys_clk_int)"
set line_num 523; puts $output_file "begin"
set line_num 524; puts $output_file "	if sys_clk_int'event and sys_clk_int = '1' then"
set line_num 525; puts $output_file "		local_rst <= sys_rst;"
set line_num 526; puts $output_file "	end if;"
set line_num 527; puts $output_file "end process local_rst_proc;"
set line_num 528; puts $output_file ""
set line_num 529; puts $output_file "local_rst90_proc: process(sys_clk90_int)"
set line_num 530; puts $output_file "begin"
set line_num 531; puts $output_file "	if sys_clk90_int'event and sys_clk90_int = '1' then"
set line_num 532; puts $output_file "		local_rst90 <= sys_rst90;"
set line_num 533; puts $output_file "	end if;"
set line_num 534; puts $output_file "end process local_rst90_proc;"
set line_num 535; puts $output_file ""
set line_num 536; puts $output_file "local_rst180_proc: process(sys_clk_int)"
set line_num 537; puts $output_file "begin"
set line_num 538; puts $output_file "	if sys_clk_int'event and sys_clk_int = '0' then"
set line_num 539; puts $output_file "		local_rst180 <= sys_rst180;"
set line_num 540; puts $output_file "	end if;"
set line_num 541; puts $output_file "end process local_rst180_proc;"
set line_num 542; puts $output_file ""
set line_num 543; puts $output_file "local_rst270_proc: process(sys_clk90_int)"
set line_num 544; puts $output_file "begin"
set line_num 545; puts $output_file "	if sys_clk90_int'event and sys_clk90_int = '0' then"
set line_num 546; puts $output_file "		local_rst270 <= sys_rst270;"
set line_num 547; puts $output_file "	end if;"
set line_num 548; puts $output_file "end process local_rst270_proc;"
set line_num 549; puts $output_file ""
set line_num 550; puts $output_file "end   arc_ddr2_cntrl_72bit_rl;  "
set line_num 551; puts $output_file ""
set line_num 552; puts $output_file ""
close $output_file
