set output_file [open "mem_tester_sim/ddr2_controller_v1_00_a/hdl/vhdl/ddr2_dqbit.vhd" w ]
set line_num 1; puts $output_file "library ieee;"
set line_num 2; puts $output_file "use ieee.std_logic_1164.all;"
set line_num 3; puts $output_file "use ieee.std_logic_unsigned.all;"
set line_num 4; puts $output_file "--library synplify; "
set line_num 5; puts $output_file "--use synplify.attributes.all; "
set line_num 6; puts $output_file ""
set line_num 7; puts $output_file "-- pragma translate_off"
set line_num 8; puts $output_file "library UNISIM;"
set line_num 9; puts $output_file "use UNISIM.VCOMPONENTS.ALL;"
set line_num 10; puts $output_file "-- pragma translate_on"
set line_num 11; puts $output_file ""
set line_num 12; puts $output_file "entity ddr2_dqbit is"
set line_num 13; puts $output_file ""
set line_num 14; puts $output_file "  port ("
set line_num 15; puts $output_file "        reset                : in std_logic;         "
set line_num 16; puts $output_file "        dqs                  : in std_logic;"
set line_num 17; puts $output_file "        dqs1                 : in std_logic;        "
set line_num 18; puts $output_file "        dqs_div_1            : in std_logic;"
set line_num 19; puts $output_file "        dqs_div_2            : in std_logic;"
set line_num 20; puts $output_file "        dq                   : in std_logic;"
set line_num 21; puts $output_file "        fbit_0               : out std_logic;"
set line_num 22; puts $output_file "        fbit_1               : out std_logic;"
set line_num 23; puts $output_file "        fbit_2               : out std_logic;"
set line_num 24; puts $output_file "        fbit_3               : out std_logic"
set line_num 25; puts $output_file "       );"
set line_num 26; puts $output_file "--attribute syn_noclockbuf : boolean;       "
set line_num 27; puts $output_file "--attribute syn_noclockbuf of dqs : signal is true;                   "
set line_num 28; puts $output_file "--attribute syn_noclockbuf of dqs1 : signal is true;                   "
set line_num 29; puts $output_file "end ddr2_dqbit;"
set line_num 30; puts $output_file ""
set line_num 31; puts $output_file "architecture ddr2_dqbit_arch of ddr2_dqbit is       "
set line_num 32; puts $output_file ""
set line_num 33; puts $output_file "  component FDCE"
set line_num 34; puts $output_file "    port("
set line_num 35; puts $output_file "      Q                              :	out   STD_ULOGIC;"
set line_num 36; puts $output_file "      C                              :	in    STD_ULOGIC;"
set line_num 37; puts $output_file "      CE                             :	in    STD_ULOGIC;"
set line_num 38; puts $output_file "      CLR                            :	in    STD_ULOGIC;"
set line_num 39; puts $output_file "      D                              :	in    STD_ULOGIC     "
set line_num 40; puts $output_file "      );"
set line_num 41; puts $output_file "  end component;"
set line_num 42; puts $output_file ""
set line_num 43; puts $output_file ""
set line_num 44; puts $output_file ""
set line_num 45; puts $output_file ""
set line_num 46; puts $output_file "signal fbit      : std_logic_vector(3 downto 0);"
set line_num 47; puts $output_file "signal async_clr : std_logic;"
set line_num 48; puts $output_file "signal dqsn      : std_logic;"
set line_num 49; puts $output_file "signal dqs_div2n : std_logic;"
set line_num 50; puts $output_file "signal dqs_div1n : std_logic; "
set line_num 51; puts $output_file ""
set line_num 52; puts $output_file "begin"
set line_num 53; puts $output_file ""
set line_num 54; puts $output_file "--resetn    <= not reset; "
set line_num 55; puts $output_file "async_clr  <= reset;  --(not resetn); --  or (not rd_cmd)   "
set line_num 56; puts $output_file "dqsn       <= not dqs;"
set line_num 57; puts $output_file "dqs_div2n  <= not dqs_div_2;"
set line_num 58; puts $output_file "dqs_div1n  <= not dqs_div_1;"
set line_num 59; puts $output_file "fbit_0     <= fbit(0);"
set line_num 60; puts $output_file "fbit_1     <= fbit(1);"
set line_num 61; puts $output_file "fbit_2     <= fbit(2);"
set line_num 62; puts $output_file "fbit_3     <= fbit(3);"
set line_num 63; puts $output_file ""
set line_num 64; puts $output_file ""
set line_num 65; puts $output_file "-- Read data from memory is first registered in CLB ff using delayed strobe from memory"
set line_num 66; puts $output_file "-- A data bit from data words 0, 1, 2, and 3"
set line_num 67; puts $output_file ""
set line_num 68; puts $output_file "fbit0 : FDCE port map ("
set line_num 69; puts $output_file "                      Q   => fbit(0),"
set line_num 70; puts $output_file "                      C   => dqs1,"
set line_num 71; puts $output_file "                      CE  => dqs_div2n,"
set line_num 72; puts $output_file "                      CLR => async_clr,"
set line_num 73; puts $output_file "                      D   => dq"
set line_num 74; puts $output_file "                     );"
set line_num 75; puts $output_file ""
set line_num 76; puts $output_file "fbit1 : FDCE port map ("
set line_num 77; puts $output_file "                      Q   => fbit(1),"
set line_num 78; puts $output_file "                      C   => dqsn,"
set line_num 79; puts $output_file "                      CE  => dqs_div_2,"
set line_num 80; puts $output_file "                      CLR => async_clr,"
set line_num 81; puts $output_file "                      D   => dq"
set line_num 82; puts $output_file "                     );"
set line_num 83; puts $output_file "                     "
set line_num 84; puts $output_file "fbit2 : FDCE port map ("
set line_num 85; puts $output_file "                       Q   => fbit(2),"
set line_num 86; puts $output_file "                       C   => dqs1,"
set line_num 87; puts $output_file "                       CE  => dqs_div_2,"
set line_num 88; puts $output_file "                       CLR => async_clr,"
set line_num 89; puts $output_file "                       D   => dq"
set line_num 90; puts $output_file "                      );"
set line_num 91; puts $output_file "                      "
set line_num 92; puts $output_file "fbit3 : FDCE port map ("
set line_num 93; puts $output_file "                       Q   => fbit(3),"
set line_num 94; puts $output_file "                       C   => dqsn,"
set line_num 95; puts $output_file "                       CE  => dqs_div_1,"
set line_num 96; puts $output_file "                       CLR => async_clr,"
set line_num 97; puts $output_file "                       D   => dq"
set line_num 98; puts $output_file "                      );                                            "
set line_num 99; puts $output_file "  "
set line_num 100; puts $output_file ""
set line_num 101; puts $output_file "end ddr2_dqbit_arch;"
set line_num 102; puts $output_file ""
close $output_file
