set output_file [open "mem_tester_sim/ddr2_controller_v1_00_a/hdl/vhdl/ddr2_dqs_div.vhd" w ]
set line_num 1; puts $output_file "library ieee;"
set line_num 2; puts $output_file "use ieee.std_logic_1164.all;"
set line_num 3; puts $output_file "use ieee.std_logic_unsigned.all;"
set line_num 4; puts $output_file "--library synplify; "
set line_num 5; puts $output_file "--use synplify.attributes.all; "
set line_num 6; puts $output_file ""
set line_num 7; puts $output_file "-- pragma translate_off"
set line_num 8; puts $output_file "library UNISIM;"
set line_num 9; puts $output_file "use UNISIM.VCOMPONENTS.ALL;"
set line_num 10; puts $output_file "-- pragma translate_on"
set line_num 11; puts $output_file ""
set line_num 12; puts $output_file "entity ddr2_dqs_div is"
set line_num 13; puts $output_file "  port (        "
set line_num 14; puts $output_file "        dqs                 : in std_logic;  -- first column (col0) for negative edge data"
set line_num 15; puts $output_file "        dqs1                : in std_logic;  -- second column (col1) for positive edge data"
set line_num 16; puts $output_file "        reset               : in std_logic; "
set line_num 17; puts $output_file "        rst_dqs_div_delayed : in std_logic; "
set line_num 18; puts $output_file "        dqs_divn            : out std_logic; -- col0"
set line_num 19; puts $output_file "        dqs_divp            : out std_logic  -- col1"
set line_num 20; puts $output_file "       );"
set line_num 21; puts $output_file "end ddr2_dqs_div;"
set line_num 22; puts $output_file ""
set line_num 23; puts $output_file "architecture ddr2_dqs_div_arch of ddr2_dqs_div is"
set line_num 24; puts $output_file ""
set line_num 25; puts $output_file "  component FDC"
set line_num 26; puts $output_file "    port("
set line_num 27; puts $output_file "      Q                              :	out   STD_ULOGIC;"
set line_num 28; puts $output_file "      C                              :	in    STD_ULOGIC;"
set line_num 29; puts $output_file "      CLR                            :	in    STD_ULOGIC;"
set line_num 30; puts $output_file "      D                              :	in    STD_ULOGIC     "
set line_num 31; puts $output_file "      );"
set line_num 32; puts $output_file "  end component;"
set line_num 33; puts $output_file ""
set line_num 34; puts $output_file "signal dqs_div1_int  : std_logic;  "
set line_num 35; puts $output_file "signal dqs_div0_int  : std_logic;"
set line_num 36; puts $output_file "signal dqs_div0n     : std_logic;"
set line_num 37; puts $output_file "signal dqs_div1n     : std_logic;"
set line_num 38; puts $output_file "signal async_clr     : std_logic; "
set line_num 39; puts $output_file "signal dqs1_n        : std_logic; "
set line_num 40; puts $output_file "signal dqs_n         : std_logic; "
set line_num 41; puts $output_file ""
set line_num 42; puts $output_file "begin"
set line_num 43; puts $output_file ""
set line_num 44; puts $output_file "dqs_divn  <= dqs_div1_int;"
set line_num 45; puts $output_file "dqs_divp  <= dqs_div0_int;"
set line_num 46; puts $output_file "dqs_div0n <= not dqs_div0_int; "
set line_num 47; puts $output_file "dqs_div1n <= not dqs_div1_int;"
set line_num 48; puts $output_file "dqs1_n    <= not dqs1;"
set line_num 49; puts $output_file "dqs_n     <= not dqs;"
set line_num 50; puts $output_file ""
set line_num 51; puts $output_file ""
set line_num 52; puts $output_file "col1 :   FDC"
set line_num 53; puts $output_file "    port map("
set line_num 54; puts $output_file "             Q   => dqs_div0_int, "
set line_num 55; puts $output_file "             C   => dqs1,"
set line_num 56; puts $output_file "             CLR => rst_dqs_div_delayed,"
set line_num 57; puts $output_file "             D   => dqs_div0n"
set line_num 58; puts $output_file "            );"
set line_num 59; puts $output_file ""
set line_num 60; puts $output_file "col0 :   FDC"
set line_num 61; puts $output_file "    port map("
set line_num 62; puts $output_file "             Q   => dqs_div1_int, "
set line_num 63; puts $output_file "             C   => dqs_n,"
set line_num 64; puts $output_file "             CLR => reset,"
set line_num 65; puts $output_file "             D   => dqs_div0_int"
set line_num 66; puts $output_file "            );"
set line_num 67; puts $output_file "            "
set line_num 68; puts $output_file "end ddr2_dqs_div_arch;"
close $output_file
