set output_file [open "mem_tester_sim/ddr2_controller_v1_00_a/hdl/vhdl/r_w_dly.vhd" w ]
set line_num 1; puts $output_file "library ieee;"
set line_num 2; puts $output_file "use ieee.std_logic_1164.all;"
set line_num 3; puts $output_file "use ieee.std_logic_unsigned.all;"
set line_num 4; puts $output_file "--"
set line_num 5; puts $output_file "-- pragma translate_off"
set line_num 6; puts $output_file "library UNISIM;"
set line_num 7; puts $output_file "use UNISIM.VCOMPONENTS.ALL;"
set line_num 8; puts $output_file "-- pragma translate_on"
set line_num 9; puts $output_file "--"
set line_num 10; puts $output_file "entity r_w_dly is"
set line_num 11; puts $output_file " port("
set line_num 12; puts $output_file "      clk     : in std_logic;"
set line_num 13; puts $output_file "      rst     : in std_logic;"
set line_num 14; puts $output_file "      dly_inc : in std_logic;"
set line_num 15; puts $output_file "      dly_tc  : out std_logic;"
set line_num 16; puts $output_file "      r_w     : out std_logic"
set line_num 17; puts $output_file "      );"
set line_num 18; puts $output_file "end r_w_dly;"
set line_num 19; puts $output_file ""
set line_num 20; puts $output_file "architecture arc_r_w_dly of r_w_dly is "
set line_num 21; puts $output_file ""
set line_num 22; puts $output_file "signal delay_count : std_logic_vector(4 downto 0);"
set line_num 23; puts $output_file "signal delay_tc    : std_logic;"
set line_num 24; puts $output_file "signal read_write  : std_logic;"
set line_num 25; puts $output_file ""
set line_num 26; puts $output_file "begin"
set line_num 27; puts $output_file ""
set line_num 28; puts $output_file "       read_write_proc : process(clk)"
set line_num 29; puts $output_file "	begin"
set line_num 30; puts $output_file "	     if falling_edge(clk) then"
set line_num 31; puts $output_file "		if (rst='1') then"
set line_num 32; puts $output_file "		  read_write <= '0';"
set line_num 33; puts $output_file "		else"
set line_num 34; puts $output_file "		  if (delay_tc = '1') then"
set line_num 35; puts $output_file "		    read_write <= not(read_write);"
set line_num 36; puts $output_file "		  end if;"
set line_num 37; puts $output_file "		end if;"
set line_num 38; puts $output_file "	     end if;"
set line_num 39; puts $output_file "	end process read_write_proc;"
set line_num 40; puts $output_file "	"
set line_num 41; puts $output_file "	delay_counter : process(clk)"
set line_num 42; puts $output_file "	begin"
set line_num 43; puts $output_file "	     if falling_edge(clk) then	 "
set line_num 44; puts $output_file "		if (rst='1') then"
set line_num 45; puts $output_file "		    delay_count <= \"00000\";"
set line_num 46; puts $output_file "		else"
set line_num 47; puts $output_file "		        if dly_inc = '1' then"
set line_num 48; puts $output_file "			   delay_count <= delay_count + \"0001\" ;"
set line_num 49; puts $output_file "                 	end if;"
set line_num 50; puts $output_file "		end if;"
set line_num 51; puts $output_file "	     end if;"
set line_num 52; puts $output_file "	end process delay_counter;	"
set line_num 53; puts $output_file "	"
set line_num 54; puts $output_file "	delay_tc_proc : process(clk)"
set line_num 55; puts $output_file "	begin"
set line_num 56; puts $output_file "	     if falling_edge(clk) then"
set line_num 57; puts $output_file "		if (rst='1') then"
set line_num 58; puts $output_file "			delay_tc <= '0';"
set line_num 59; puts $output_file "		else"
set line_num 60; puts $output_file "			if (delay_count=\"11000\") then -- decimal 28??"
set line_num 61; puts $output_file "				delay_tc <= '1';"
set line_num 62; puts $output_file "			else "
set line_num 63; puts $output_file "				delay_tc <= '0';"
set line_num 64; puts $output_file "			end if;"
set line_num 65; puts $output_file "		end if;"
set line_num 66; puts $output_file "	     end if;"
set line_num 67; puts $output_file "	end process delay_tc_proc;"
set line_num 68; puts $output_file ""
set line_num 69; puts $output_file "dly_tc <= delay_tc;"
set line_num 70; puts $output_file "r_w    <= read_write;"
set line_num 71; puts $output_file ""
set line_num 72; puts $output_file "end arc_r_w_dly;"
close $output_file
