set output_file [open "mem_tester_sim/ddr2_controller_v1_00_a/hdl/vhdl/cal_div2f.vhd" w ]
set line_num 1; puts $output_file "library ieee;"
set line_num 2; puts $output_file "use ieee.std_logic_1164.all;"
set line_num 3; puts $output_file "use ieee.std_logic_unsigned.all;"
set line_num 4; puts $output_file "--"
set line_num 5; puts $output_file "-- pragma translate_off"
set line_num 6; puts $output_file "library UNISIM;"
set line_num 7; puts $output_file "use UNISIM.VCOMPONENTS.ALL;"
set line_num 8; puts $output_file "-- pragma translate_on"
set line_num 9; puts $output_file ""
set line_num 10; puts $output_file "entity cal_div2f is"
set line_num 11; puts $output_file "port("
set line_num 12; puts $output_file "		reset : in std_logic;"
set line_num 13; puts $output_file "		iclk  : in std_logic;"
set line_num 14; puts $output_file "		oclk  : out std_logic"
set line_num 15; puts $output_file "		);"
set line_num 16; puts $output_file ""
set line_num 17; puts $output_file "end cal_div2f;"
set line_num 18; puts $output_file ""
set line_num 19; puts $output_file "architecture arc_cal_div2f of cal_div2f is"
set line_num 20; puts $output_file ""
set line_num 21; puts $output_file "signal  poclk        : std_logic;"
set line_num 22; puts $output_file "   "
set line_num 23; puts $output_file "begin"
set line_num 24; puts $output_file ""
set line_num 25; puts $output_file "process (iclk)"
set line_num 26; puts $output_file "begin"
set line_num 27; puts $output_file " if iclk'event and iclk = '0' then"
set line_num 28; puts $output_file "	if reset = '1' then"
set line_num 29; puts $output_file "		 poclk <= '0';"
set line_num 30; puts $output_file "		 oclk <= '0';"
set line_num 31; puts $output_file "	else "
set line_num 32; puts $output_file "		 poclk <= not poclk;"
set line_num 33; puts $output_file "		 oclk <= poclk;"
set line_num 34; puts $output_file "	end if;"
set line_num 35; puts $output_file " end if;"
set line_num 36; puts $output_file "end process;	"
set line_num 37; puts $output_file ""
set line_num 38; puts $output_file ""
set line_num 39; puts $output_file "end arc_cal_div2f;"
close $output_file
