set output_file [open "mem_tester_sim/ddr2_controller_v1_00_a/hdl/vhdl/cal_reg.vhd" w ]
set line_num 1; puts $output_file "library ieee;"
set line_num 2; puts $output_file "use ieee.std_logic_1164.all;"
set line_num 3; puts $output_file "use ieee.std_logic_unsigned.all;"
set line_num 4; puts $output_file "--"
set line_num 5; puts $output_file "-- pragma translate_off"
set line_num 6; puts $output_file "library UNISIM;"
set line_num 7; puts $output_file "use UNISIM.VCOMPONENTS.ALL;"
set line_num 8; puts $output_file "-- pragma translate_on"
set line_num 9; puts $output_file ""
set line_num 10; puts $output_file "entity cal_reg is"
set line_num 11; puts $output_file "port("
set line_num 12; puts $output_file "     clk            : in  std_logic;"
set line_num 13; puts $output_file "     dInp           : in  std_logic;"
set line_num 14; puts $output_file "     iReg           : out std_logic;"
set line_num 15; puts $output_file "     dReg           : out std_logic"
set line_num 16; puts $output_file "     );"
set line_num 17; puts $output_file "end cal_reg;"
set line_num 18; puts $output_file ""
set line_num 19; puts $output_file ""
set line_num 20; puts $output_file "architecture arc_cal_reg of cal_reg is"
set line_num 21; puts $output_file ""
set line_num 22; puts $output_file "component FD"
set line_num 23; puts $output_file "   port("
set line_num 24; puts $output_file "      Q                              :  out   STD_LOGIC;"
set line_num 25; puts $output_file "      D                              :  in    STD_LOGIC;"
set line_num 26; puts $output_file "      C                              :  in    STD_LOGIC);"
set line_num 27; puts $output_file "end component;"
set line_num 28; puts $output_file ""
set line_num 29; puts $output_file ""
set line_num 30; puts $output_file "signal iReg_val  : std_logic;"
set line_num 31; puts $output_file "---signal iReg : std_logic;"
set line_num 32; puts $output_file "signal dReg_val : std_logic;"
set line_num 33; puts $output_file ""
set line_num 34; puts $output_file ""
set line_num 35; puts $output_file "attribute syn_replicate : boolean;"
set line_num 36; puts $output_file "attribute syn_replicate of dReg_val : signal is false;"
set line_num 37; puts $output_file ""
set line_num 38; puts $output_file "begin"
set line_num 39; puts $output_file ""
set line_num 40; puts $output_file "iReg <= iReg_val;      "
set line_num 41; puts $output_file "dReg <= dReg_val;      "
set line_num 42; puts $output_file "	"
set line_num 43; puts $output_file "ireg_FD : FD port map ("
set line_num 44; puts $output_file "                      Q => iReg_val,"
set line_num 45; puts $output_file "                      --Q => iReg,"
set line_num 46; puts $output_file "                      D => dInp,"
set line_num 47; puts $output_file "                      C => clk);"
set line_num 48; puts $output_file ""
set line_num 49; puts $output_file "dreg_FD : FD port map ("
set line_num 50; puts $output_file "                      Q => dReg_val,"
set line_num 51; puts $output_file "                      D => iReg_val,"
set line_num 52; puts $output_file "                      --D => iReg,"
set line_num 53; puts $output_file "                      C => clk);"
set line_num 54; puts $output_file "end arc_cal_reg;"
close $output_file
