set output_file [open "mem_tester_sim/ddr2_controller_v1_00_a/hdl/vhdl/data_path_iobs_72bit.vhd" w ]
set line_num 1; puts $output_file "--******************************************************************************"
set line_num 2; puts $output_file "--"
set line_num 3; puts $output_file "--  Xilinx, Inc. 2002                 www.xilinx.com"
set line_num 4; puts $output_file "--"
set line_num 5; puts $output_file "--  XAPP 253 - Synthesizable DDR SDRAM Controller"
set line_num 6; puts $output_file "--"
set line_num 7; puts $output_file "--*******************************************************************************"
set line_num 8; puts $output_file "--"
set line_num 9; puts $output_file "--  File name :       data_path_iobs.vhd"
set line_num 10; puts $output_file "--"
set line_num 11; puts $output_file "--  Description :     All the inputs and outputs related to data path module "
set line_num 12; puts $output_file "--                    are declared here. The outputs and inputs are "
set line_num 13; puts $output_file "--                    registered within the IOB's.                   "
set line_num 14; puts $output_file "--"
set line_num 15; puts $output_file "--  Date - revision : 05/01/2002"
set line_num 16; puts $output_file "--"
set line_num 17; puts $output_file "--  Author :          Lakshmi Gopalakrishnan ( Modified by Sailaja)"
set line_num 18; puts $output_file "--"
set line_num 19; puts $output_file "--  Contact : e-mail  hotline@xilinx.com"
set line_num 20; puts $output_file "--            phone   + 1 800 255 7778 "
set line_num 21; puts $output_file "--"
set line_num 22; puts $output_file "--  Disclaimer: LIMITED WARRANTY AND DISCLAMER. These designs are "
set line_num 23; puts $output_file "--              provided to you \"as is\". Xilinx and its licensors make and you "
set line_num 24; puts $output_file "--              receive no warranties or conditions, express, implied, "
set line_num 25; puts $output_file "--              statutory or otherwise, and Xilinx specifically disclaims any "
set line_num 26; puts $output_file "--              implied warranties of merchantability, non-infringement, or "
set line_num 27; puts $output_file "--              fitness for a particular purpose. Xilinx does not warrant that "
set line_num 28; puts $output_file "--              the functions contained in these designs will meet your "
set line_num 29; puts $output_file "--              requirements, or that the operation of these designs will be "
set line_num 30; puts $output_file "--              uninterrupted or error free, or that defects in the Designs "
set line_num 31; puts $output_file "--              will be corrected. Furthermore, Xilinx does not warrant or "
set line_num 32; puts $output_file "--              make any representations regarding use or the results of the "
set line_num 33; puts $output_file "--              use of the designs in terms of correctness, accuracy, "
set line_num 34; puts $output_file "--              reliability, or otherwise. "
set line_num 35; puts $output_file "--"
set line_num 36; puts $output_file "--              LIMITATION OF LIABILITY. In no event will Xilinx or its "
set line_num 37; puts $output_file "--              licensors be liable for any loss of data, lost profits, cost "
set line_num 38; puts $output_file "--              or procurement of substitute goods or services, or for any "
set line_num 39; puts $output_file "--              special, incidental, consequential, or indirect damages "
set line_num 40; puts $output_file "--              arising from the use or operation of the designs or "
set line_num 41; puts $output_file "--              accompanying documentation, however caused and on any theory "
set line_num 42; puts $output_file "--              of liability. This limitation will apply even if Xilinx "
set line_num 43; puts $output_file "--              has been advised of the possibility of such damage. This "
set line_num 44; puts $output_file "--              limitation shall apply not-withstanding the failure of the "
set line_num 45; puts $output_file "--              essential purpose of any limited remedies herein. "
set line_num 46; puts $output_file "--"
set line_num 47; puts $output_file "--  Copyright © 2002 Xilinx, Inc."
set line_num 48; puts $output_file "--  All rights reserved "
set line_num 49; puts $output_file "-- "
set line_num 50; puts $output_file "--*****************************************************************************"
set line_num 51; puts $output_file "library ieee;"
set line_num 52; puts $output_file "use ieee.std_logic_1164.all;"
set line_num 53; puts $output_file "use ieee.std_logic_unsigned.all;"
set line_num 54; puts $output_file "--"
set line_num 55; puts $output_file "-- pragma translate_off"
set line_num 56; puts $output_file "library UNISIM;"
set line_num 57; puts $output_file "use UNISIM.VCOMPONENTS.ALL;"
set line_num 58; puts $output_file "-- pragma translate_on"
set line_num 59; puts $output_file "--"
set line_num 60; puts $output_file "entity   data_path_iobs_72bit  is"
set line_num 61; puts $output_file "port("
set line_num 62; puts $output_file "    clk               : in std_logic;"
set line_num 63; puts $output_file "    dqs_reset         : in std_logic;"
set line_num 64; puts $output_file "    dqs_enable        : in std_logic;"
set line_num 65; puts $output_file "    ddr_dqs           : inout std_logic_vector(8 downto 0);"
set line_num 66; puts $output_file "    ddr_dq            : inout std_logic_vector(71 downto 0);"
set line_num 67; puts $output_file "    write_data_falling: in std_logic_vector(71 downto 0);"
set line_num 68; puts $output_file "    write_data_rising : in std_logic_vector(71 downto 0);"
set line_num 69; puts $output_file "    write_en_val      : in std_logic;"
set line_num 70; puts $output_file "    clk90             : in std_logic;"
set line_num 71; puts $output_file "    reset270_r        : in std_logic;"
set line_num 72; puts $output_file "    data_mask_f       : in std_logic_vector(8 downto 0);"
set line_num 73; puts $output_file "    data_mask_r       : in std_logic_vector(8 downto 0);"
set line_num 74; puts $output_file "    dqs_int_delay_in0 : out std_logic;"
set line_num 75; puts $output_file "    dqs_int_delay_in1 : out std_logic;"
set line_num 76; puts $output_file "    dqs_int_delay_in2 : out std_logic;"
set line_num 77; puts $output_file "    dqs_int_delay_in3 : out std_logic;"
set line_num 78; puts $output_file "    dqs_int_delay_in4 : out std_logic;"
set line_num 79; puts $output_file "    dqs_int_delay_in5 : out std_logic;"
set line_num 80; puts $output_file "    dqs_int_delay_in6 : out std_logic;"
set line_num 81; puts $output_file "    dqs_int_delay_in7 : out std_logic;"
set line_num 82; puts $output_file "    dqs_int_delay_in8 : out std_logic;"
set line_num 83; puts $output_file "    dq                : out std_logic_vector(71 downto 0);"
set line_num 84; puts $output_file "    ddr_dm            : out std_logic_vector(8 downto 0)"
set line_num 85; puts $output_file ");"
set line_num 86; puts $output_file "end   data_path_iobs_72bit;  "
set line_num 87; puts $output_file ""
set line_num 88; puts $output_file ""
set line_num 89; puts $output_file "architecture   arc_data_path_iobs_72bit of   data_path_iobs_72bit    is"
set line_num 90; puts $output_file ""
set line_num 91; puts $output_file ""
set line_num 92; puts $output_file "component ddr_dqs_iob"
set line_num 93; puts $output_file "port("
set line_num 94; puts $output_file "     clk            : in std_logic;"
set line_num 95; puts $output_file "     ddr_dqs_reset  : in std_logic;"
set line_num 96; puts $output_file "     ddr_dqs_enable : in std_logic;"
set line_num 97; puts $output_file "     ddr_dqs        : inout std_logic;"
set line_num 98; puts $output_file "     dqs            : out std_logic"
set line_num 99; puts $output_file "     );"
set line_num 100; puts $output_file "end component;"
set line_num 101; puts $output_file ""
set line_num 102; puts $output_file "component ddr_dq_iob"
set line_num 103; puts $output_file "port ("
set line_num 104; puts $output_file "      ddr_dq_inout       : inout std_logic; --Bi-directional SDRAM data bus"
set line_num 105; puts $output_file "      write_data_falling : in std_logic;    --Transmit data, output on falling edge"
set line_num 106; puts $output_file "      write_data_rising  : in std_logic;    --Transmit data, output on rising edge"
set line_num 107; puts $output_file "      read_data_in       : out std_logic;   -- Received data"
set line_num 108; puts $output_file "      clk90              : in std_logic;    --Clock 90"
set line_num 109; puts $output_file "      write_en_val       : in std_logic;    --Transmit enable"
set line_num 110; puts $output_file "      reset              : in std_logic); "
set line_num 111; puts $output_file "end component;"
set line_num 112; puts $output_file ""
set line_num 113; puts $output_file ""
set line_num 114; puts $output_file "component	ddr2_dm_72bit "
set line_num 115; puts $output_file "port (                                                "
set line_num 116; puts $output_file "      ddr_dm       : out std_logic_vector(8 downto 0);"
set line_num 117; puts $output_file "      mask_falling : in std_logic_vector(8 downto 0); "
set line_num 118; puts $output_file "      mask_rising  : in std_logic_vector(8 downto 0); "
set line_num 119; puts $output_file "      write_en_val : in std_logic;"
set line_num 120; puts $output_file "      clk90        : in std_logic    --Clock 90                          "
set line_num 121; puts $output_file "      );                                              "
set line_num 122; puts $output_file "end component; "
set line_num 123; puts $output_file ""
set line_num 124; puts $output_file ""
set line_num 125; puts $output_file "component IOBUF_SSTL2_II"
set line_num 126; puts $output_file "port ("
set line_num 127; puts $output_file "       I  : in std_logic;"
set line_num 128; puts $output_file "       T  : in std_logic;"
set line_num 129; puts $output_file "       IO : inout std_logic;"
set line_num 130; puts $output_file "       O  : out std_logic);"
set line_num 131; puts $output_file "end component;"
set line_num 132; puts $output_file ""
set line_num 133; puts $output_file "component FD"
set line_num 134; puts $output_file "   port("
set line_num 135; puts $output_file "      Q                              :  out   STD_LOGIC;"
set line_num 136; puts $output_file "      D                              :  in    STD_LOGIC;"
set line_num 137; puts $output_file "      C                              :  in    STD_LOGIC);"
set line_num 138; puts $output_file "end component;"
set line_num 139; puts $output_file ""
set line_num 140; puts $output_file "component OBUF"
set line_num 141; puts $output_file " port ("
set line_num 142; puts $output_file "   O : out std_logic;"
set line_num 143; puts $output_file "   I : in std_logic);"
set line_num 144; puts $output_file " end component;"
set line_num 145; puts $output_file ""
set line_num 146; puts $output_file ""
set line_num 147; puts $output_file ""
set line_num 148; puts $output_file "begin"
set line_num 149; puts $output_file ""
set line_num 150; puts $output_file "  "
set line_num 151; puts $output_file "--***********************************************************************"
set line_num 152; puts $output_file "-- DQS IOB instantiations"
set line_num 153; puts $output_file "--***********************************************************************"
set line_num 154; puts $output_file ""
set line_num 155; puts $output_file " ddr_dqs_iob0 : ddr_dqs_iob port map ("
set line_num 156; puts $output_file "                              clk            => clk,"
set line_num 157; puts $output_file "                              ddr_dqs_reset  => dqs_reset,"
set line_num 158; puts $output_file "                              ddr_dqs_enable => dqs_enable,"
set line_num 159; puts $output_file "                              ddr_dqs        => ddr_dqs(0),"
set line_num 160; puts $output_file "                              dqs            => dqs_int_delay_in0"
set line_num 161; puts $output_file "                             );"
set line_num 162; puts $output_file "                             "
set line_num 163; puts $output_file " ddr_dqs_iob1 : ddr_dqs_iob port map ("
set line_num 164; puts $output_file "                              clk            => clk,"
set line_num 165; puts $output_file "                              ddr_dqs_reset  => dqs_reset,"
set line_num 166; puts $output_file "                              ddr_dqs_enable => dqs_enable,"
set line_num 167; puts $output_file "                              ddr_dqs        => ddr_dqs(1),"
set line_num 168; puts $output_file "                              dqs            => dqs_int_delay_in1"
set line_num 169; puts $output_file "                             );"
set line_num 170; puts $output_file "                             "
set line_num 171; puts $output_file " ddr_dqs_iob2 : ddr_dqs_iob port map ("
set line_num 172; puts $output_file "                              clk            => clk,"
set line_num 173; puts $output_file "                              ddr_dqs_reset  => dqs_reset,"
set line_num 174; puts $output_file "                              ddr_dqs_enable => dqs_enable,"
set line_num 175; puts $output_file "                              ddr_dqs        => ddr_dqs(2),"
set line_num 176; puts $output_file "                              dqs            => dqs_int_delay_in2"
set line_num 177; puts $output_file "                             );"
set line_num 178; puts $output_file "                             "
set line_num 179; puts $output_file " ddr_dqs_iob3 : ddr_dqs_iob port map ("
set line_num 180; puts $output_file "                              clk            => clk,"
set line_num 181; puts $output_file "                              ddr_dqs_reset  => dqs_reset,"
set line_num 182; puts $output_file "                              ddr_dqs_enable => dqs_enable,"
set line_num 183; puts $output_file "                              ddr_dqs        => ddr_dqs(3),"
set line_num 184; puts $output_file "                              dqs            => dqs_int_delay_in3"
set line_num 185; puts $output_file "                             );"
set line_num 186; puts $output_file "                             "
set line_num 187; puts $output_file " ddr_dqs_iob4 : ddr_dqs_iob port map ("
set line_num 188; puts $output_file "                              clk            => clk,"
set line_num 189; puts $output_file "                              ddr_dqs_reset  => dqs_reset,"
set line_num 190; puts $output_file "                              ddr_dqs_enable => dqs_enable,"
set line_num 191; puts $output_file "                              ddr_dqs        => ddr_dqs(4),"
set line_num 192; puts $output_file "                              dqs            => dqs_int_delay_in4"
set line_num 193; puts $output_file "                             );"
set line_num 194; puts $output_file "                             "
set line_num 195; puts $output_file " ddr_dqs_iob5 : ddr_dqs_iob port map ("
set line_num 196; puts $output_file "                              clk            => clk,"
set line_num 197; puts $output_file "                              ddr_dqs_reset  => dqs_reset,"
set line_num 198; puts $output_file "                              ddr_dqs_enable => dqs_enable,"
set line_num 199; puts $output_file "                              ddr_dqs        => ddr_dqs(5),"
set line_num 200; puts $output_file "                              dqs            => dqs_int_delay_in5"
set line_num 201; puts $output_file "                             );"
set line_num 202; puts $output_file "                             "
set line_num 203; puts $output_file " ddr_dqs_iob6 : ddr_dqs_iob port map ("
set line_num 204; puts $output_file "                              clk            => clk,"
set line_num 205; puts $output_file "                              ddr_dqs_reset  => dqs_reset,"
set line_num 206; puts $output_file "                              ddr_dqs_enable => dqs_enable,"
set line_num 207; puts $output_file "                              ddr_dqs        => ddr_dqs(6),"
set line_num 208; puts $output_file "                              dqs            => dqs_int_delay_in6"
set line_num 209; puts $output_file "                             );"
set line_num 210; puts $output_file "                             "
set line_num 211; puts $output_file " ddr_dqs_iob7 : ddr_dqs_iob port map ("
set line_num 212; puts $output_file "                              clk            => clk,"
set line_num 213; puts $output_file "                              ddr_dqs_reset  => dqs_reset,"
set line_num 214; puts $output_file "                              ddr_dqs_enable => dqs_enable,"
set line_num 215; puts $output_file "                              ddr_dqs        => ddr_dqs(7),"
set line_num 216; puts $output_file "                              dqs            => dqs_int_delay_in7"
set line_num 217; puts $output_file "                             );"
set line_num 218; puts $output_file "                             "
set line_num 219; puts $output_file " ddr_dqs_iob8 : ddr_dqs_iob port map ("
set line_num 220; puts $output_file "                              clk            => clk,"
set line_num 221; puts $output_file "                              ddr_dqs_reset  => dqs_reset,"
set line_num 222; puts $output_file "                              ddr_dqs_enable => dqs_enable,"
set line_num 223; puts $output_file "                              ddr_dqs        => ddr_dqs(8),"
set line_num 224; puts $output_file "                              dqs            => dqs_int_delay_in8"
set line_num 225; puts $output_file "                              );"
set line_num 226; puts $output_file "--***********************************************************************"
set line_num 227; puts $output_file "-- Dq IOB instantiations"
set line_num 228; puts $output_file "--***********************************************************************                            );"
set line_num 229; puts $output_file ""
set line_num 230; puts $output_file "ddr_dq_iob0 : ddr_dq_iob port map( "
set line_num 231; puts $output_file "                                     ddr_dq_inout       => ddr_dq(0),"
set line_num 232; puts $output_file "                                     write_data_rising  => write_data_rising(0),"
set line_num 233; puts $output_file "                                     write_data_falling => write_data_falling(0),"
set line_num 234; puts $output_file "                                     read_data_in       => dq(0),"
set line_num 235; puts $output_file "                                     clk90              => clk90,"
set line_num 236; puts $output_file "                                     write_en_val       => write_en_val,"
set line_num 237; puts $output_file "                                     reset              => reset270_r"
set line_num 238; puts $output_file "                                     );"
set line_num 239; puts $output_file ""
set line_num 240; puts $output_file "ddr_dq_iob1 : ddr_dq_iob port map( "
set line_num 241; puts $output_file "                                     ddr_dq_inout       => ddr_dq(1),"
set line_num 242; puts $output_file "                                     write_data_rising  => write_data_rising(1),"
set line_num 243; puts $output_file "                                     write_data_falling => write_data_falling(1),"
set line_num 244; puts $output_file "                                     read_data_in       => dq(1),"
set line_num 245; puts $output_file "                                     clk90              => clk90,"
set line_num 246; puts $output_file "                                     write_en_val       => write_en_val,"
set line_num 247; puts $output_file "                                     reset              => reset270_r"
set line_num 248; puts $output_file "                                     );"
set line_num 249; puts $output_file ""
set line_num 250; puts $output_file "ddr_dq_iob2 : ddr_dq_iob port map( "
set line_num 251; puts $output_file "                                     ddr_dq_inout       => ddr_dq(2),"
set line_num 252; puts $output_file "                                     write_data_rising  => write_data_rising(2),"
set line_num 253; puts $output_file "                                     write_data_falling => write_data_falling(2),"
set line_num 254; puts $output_file "                                     read_data_in       => dq(2),"
set line_num 255; puts $output_file "                                     clk90              => clk90,"
set line_num 256; puts $output_file "                                     write_en_val       => write_en_val,"
set line_num 257; puts $output_file "                                     reset              => reset270_r"
set line_num 258; puts $output_file "                                     );"
set line_num 259; puts $output_file ""
set line_num 260; puts $output_file "ddr_dq_iob3 : ddr_dq_iob port map( "
set line_num 261; puts $output_file "                                     ddr_dq_inout       => ddr_dq(3),"
set line_num 262; puts $output_file "                                     write_data_rising  => write_data_rising(3),"
set line_num 263; puts $output_file "                                     write_data_falling => write_data_falling(3),"
set line_num 264; puts $output_file "                                     read_data_in       => dq(3),"
set line_num 265; puts $output_file "                                     clk90              => clk90,"
set line_num 266; puts $output_file "                                     write_en_val       => write_en_val,"
set line_num 267; puts $output_file "                                     reset              => reset270_r"
set line_num 268; puts $output_file "                                     );"
set line_num 269; puts $output_file ""
set line_num 270; puts $output_file "ddr_dq_iob4 : ddr_dq_iob port map( "
set line_num 271; puts $output_file "                                     ddr_dq_inout       => ddr_dq(4),"
set line_num 272; puts $output_file "                                     write_data_rising  => write_data_rising(4),"
set line_num 273; puts $output_file "                                     write_data_falling => write_data_falling(4),"
set line_num 274; puts $output_file "                                     read_data_in       => dq(4),"
set line_num 275; puts $output_file "                                     clk90              => clk90,"
set line_num 276; puts $output_file "                                     write_en_val       => write_en_val,"
set line_num 277; puts $output_file "                                     reset              => reset270_r"
set line_num 278; puts $output_file "                                     );"
set line_num 279; puts $output_file ""
set line_num 280; puts $output_file "ddr_dq_iob5 : ddr_dq_iob port map( "
set line_num 281; puts $output_file "                                     ddr_dq_inout       => ddr_dq(5),"
set line_num 282; puts $output_file "                                     write_data_rising  => write_data_rising(5),"
set line_num 283; puts $output_file "                                     write_data_falling => write_data_falling(5),"
set line_num 284; puts $output_file "                                     read_data_in       => dq(5),"
set line_num 285; puts $output_file "                                     clk90              => clk90,"
set line_num 286; puts $output_file "                                     write_en_val       => write_en_val,"
set line_num 287; puts $output_file "                                     reset              => reset270_r"
set line_num 288; puts $output_file "                                     );"
set line_num 289; puts $output_file ""
set line_num 290; puts $output_file "ddr_dq_iob6 : ddr_dq_iob port map( "
set line_num 291; puts $output_file "                                     ddr_dq_inout       => ddr_dq(6),"
set line_num 292; puts $output_file "                                     write_data_rising  => write_data_rising(6),"
set line_num 293; puts $output_file "                                     write_data_falling => write_data_falling(6),"
set line_num 294; puts $output_file "                                     read_data_in       => dq(6),"
set line_num 295; puts $output_file "                                     clk90              => clk90,"
set line_num 296; puts $output_file "                                     write_en_val       => write_en_val,"
set line_num 297; puts $output_file "                                     reset              => reset270_r"
set line_num 298; puts $output_file "                                     );"
set line_num 299; puts $output_file ""
set line_num 300; puts $output_file "ddr_dq_iob7 : ddr_dq_iob port map( "
set line_num 301; puts $output_file "                                     ddr_dq_inout       => ddr_dq(7),"
set line_num 302; puts $output_file "                                     write_data_rising  => write_data_rising(7),"
set line_num 303; puts $output_file "                                     write_data_falling => write_data_falling(7),"
set line_num 304; puts $output_file "                                     read_data_in       => dq(7),"
set line_num 305; puts $output_file "                                     clk90              => clk90,"
set line_num 306; puts $output_file "                                     write_en_val       => write_en_val,"
set line_num 307; puts $output_file "                                     reset              => reset270_r"
set line_num 308; puts $output_file "                                     );"
set line_num 309; puts $output_file ""
set line_num 310; puts $output_file "ddr_dq_iob8 : ddr_dq_iob port map( "
set line_num 311; puts $output_file "                                     ddr_dq_inout       => ddr_dq(8),"
set line_num 312; puts $output_file "                                     write_data_rising  => write_data_rising(8),"
set line_num 313; puts $output_file "                                     write_data_falling => write_data_falling(8),"
set line_num 314; puts $output_file "                                     read_data_in       => dq(8),"
set line_num 315; puts $output_file "                                     clk90              => clk90,"
set line_num 316; puts $output_file "                                     write_en_val       => write_en_val,"
set line_num 317; puts $output_file "                                     reset              => reset270_r"
set line_num 318; puts $output_file "                                     );"
set line_num 319; puts $output_file ""
set line_num 320; puts $output_file "ddr_dq_iob9 : ddr_dq_iob port map( "
set line_num 321; puts $output_file "                                     ddr_dq_inout       => ddr_dq(9),"
set line_num 322; puts $output_file "                                     write_data_rising  => write_data_rising(9),"
set line_num 323; puts $output_file "                                     write_data_falling => write_data_falling(9),"
set line_num 324; puts $output_file "                                     read_data_in       => dq(9),"
set line_num 325; puts $output_file "                                     clk90              => clk90,"
set line_num 326; puts $output_file "                                     write_en_val       => write_en_val,"
set line_num 327; puts $output_file "                                     reset              => reset270_r"
set line_num 328; puts $output_file "                                     );"
set line_num 329; puts $output_file ""
set line_num 330; puts $output_file "ddr_dq_iob10 : ddr_dq_iob port map( "
set line_num 331; puts $output_file "                                     ddr_dq_inout       => ddr_dq(10),"
set line_num 332; puts $output_file "                                     write_data_rising  => write_data_rising(10),"
set line_num 333; puts $output_file "                                     write_data_falling => write_data_falling(10),"
set line_num 334; puts $output_file "                                     read_data_in       => dq(10),"
set line_num 335; puts $output_file "                                     clk90              => clk90,"
set line_num 336; puts $output_file "                                     write_en_val       => write_en_val,"
set line_num 337; puts $output_file "                                     reset              => reset270_r"
set line_num 338; puts $output_file "                                     );"
set line_num 339; puts $output_file ""
set line_num 340; puts $output_file "ddr_dq_iob11 : ddr_dq_iob port map( "
set line_num 341; puts $output_file "                                     ddr_dq_inout       => ddr_dq(11),"
set line_num 342; puts $output_file "                                     write_data_rising  => write_data_rising(11),"
set line_num 343; puts $output_file "                                     write_data_falling => write_data_falling(11),"
set line_num 344; puts $output_file "                                     read_data_in       => dq(11),"
set line_num 345; puts $output_file "                                     clk90              => clk90,"
set line_num 346; puts $output_file "                                     write_en_val       => write_en_val,"
set line_num 347; puts $output_file "                                     reset              => reset270_r"
set line_num 348; puts $output_file "                                     );"
set line_num 349; puts $output_file ""
set line_num 350; puts $output_file "ddr_dq_iob12 : ddr_dq_iob port map( "
set line_num 351; puts $output_file "                                     ddr_dq_inout       => ddr_dq(12),"
set line_num 352; puts $output_file "                                     write_data_rising  => write_data_rising(12),"
set line_num 353; puts $output_file "                                     write_data_falling => write_data_falling(12),"
set line_num 354; puts $output_file "                                     read_data_in       => dq(12),"
set line_num 355; puts $output_file "                                     clk90              => clk90,"
set line_num 356; puts $output_file "                                     write_en_val       => write_en_val,"
set line_num 357; puts $output_file "                                     reset              => reset270_r"
set line_num 358; puts $output_file "                                     );"
set line_num 359; puts $output_file ""
set line_num 360; puts $output_file "ddr_dq_iob13 : ddr_dq_iob port map( "
set line_num 361; puts $output_file "                                     ddr_dq_inout       => ddr_dq(13),"
set line_num 362; puts $output_file "                                     write_data_rising  => write_data_rising(13),"
set line_num 363; puts $output_file "                                     write_data_falling => write_data_falling(13),"
set line_num 364; puts $output_file "                                     read_data_in       => dq(13),"
set line_num 365; puts $output_file "                                     clk90              => clk90,"
set line_num 366; puts $output_file "                                     write_en_val       => write_en_val,"
set line_num 367; puts $output_file "                                     reset              => reset270_r"
set line_num 368; puts $output_file "                                     );"
set line_num 369; puts $output_file ""
set line_num 370; puts $output_file "ddr_dq_iob14 : ddr_dq_iob port map( "
set line_num 371; puts $output_file "                                     ddr_dq_inout       => ddr_dq(14),"
set line_num 372; puts $output_file "                                     write_data_rising  => write_data_rising(14),"
set line_num 373; puts $output_file "                                     write_data_falling => write_data_falling(14),"
set line_num 374; puts $output_file "                                     read_data_in       => dq(14),"
set line_num 375; puts $output_file "                                     clk90              => clk90,"
set line_num 376; puts $output_file "                                     write_en_val       => write_en_val,"
set line_num 377; puts $output_file "                                     reset              => reset270_r"
set line_num 378; puts $output_file "                                     );"
set line_num 379; puts $output_file ""
set line_num 380; puts $output_file "ddr_dq_iob15 : ddr_dq_iob port map( "
set line_num 381; puts $output_file "                                     ddr_dq_inout       => ddr_dq(15),"
set line_num 382; puts $output_file "                                     write_data_rising  => write_data_rising(15),"
set line_num 383; puts $output_file "                                     write_data_falling => write_data_falling(15),"
set line_num 384; puts $output_file "                                     read_data_in       => dq(15),"
set line_num 385; puts $output_file "                                     clk90              => clk90,"
set line_num 386; puts $output_file "                                     write_en_val       => write_en_val,"
set line_num 387; puts $output_file "                                     reset              => reset270_r"
set line_num 388; puts $output_file "                                     );"
set line_num 389; puts $output_file ""
set line_num 390; puts $output_file "ddr_dq_iob16 : ddr_dq_iob port map( "
set line_num 391; puts $output_file "                                     ddr_dq_inout       => ddr_dq(16),"
set line_num 392; puts $output_file "                                     write_data_rising  => write_data_rising(16),"
set line_num 393; puts $output_file "                                     write_data_falling => write_data_falling(16),"
set line_num 394; puts $output_file "                                     read_data_in       => dq(16),"
set line_num 395; puts $output_file "                                     clk90              => clk90,"
set line_num 396; puts $output_file "                                     write_en_val       => write_en_val,"
set line_num 397; puts $output_file "                                     reset              => reset270_r"
set line_num 398; puts $output_file "                                     );"
set line_num 399; puts $output_file ""
set line_num 400; puts $output_file "ddr_dq_iob17 : ddr_dq_iob port map( "
set line_num 401; puts $output_file "                                     ddr_dq_inout       => ddr_dq(17),"
set line_num 402; puts $output_file "                                     write_data_rising  => write_data_rising(17),"
set line_num 403; puts $output_file "                                     write_data_falling => write_data_falling(17),"
set line_num 404; puts $output_file "                                     read_data_in       => dq(17),"
set line_num 405; puts $output_file "                                     clk90              => clk90,"
set line_num 406; puts $output_file "                                     write_en_val       => write_en_val,"
set line_num 407; puts $output_file "                                     reset              => reset270_r"
set line_num 408; puts $output_file "                                     );"
set line_num 409; puts $output_file ""
set line_num 410; puts $output_file "ddr_dq_iob18 : ddr_dq_iob port map( "
set line_num 411; puts $output_file "                                     ddr_dq_inout       => ddr_dq(18),"
set line_num 412; puts $output_file "                                     write_data_rising  => write_data_rising(18),"
set line_num 413; puts $output_file "                                     write_data_falling => write_data_falling(18),"
set line_num 414; puts $output_file "                                     read_data_in       => dq(18),"
set line_num 415; puts $output_file "                                     clk90              => clk90,"
set line_num 416; puts $output_file "                                     write_en_val       => write_en_val,"
set line_num 417; puts $output_file "                                     reset              => reset270_r"
set line_num 418; puts $output_file "                                     );"
set line_num 419; puts $output_file ""
set line_num 420; puts $output_file "ddr_dq_iob19 : ddr_dq_iob port map( "
set line_num 421; puts $output_file "                                     ddr_dq_inout       => ddr_dq(19),"
set line_num 422; puts $output_file "                                     write_data_rising  => write_data_rising(19),"
set line_num 423; puts $output_file "                                     write_data_falling => write_data_falling(19),"
set line_num 424; puts $output_file "                                     read_data_in       => dq(19),"
set line_num 425; puts $output_file "                                     clk90              => clk90,"
set line_num 426; puts $output_file "                                     write_en_val       => write_en_val,"
set line_num 427; puts $output_file "                                     reset              => reset270_r"
set line_num 428; puts $output_file "                                     );"
set line_num 429; puts $output_file ""
set line_num 430; puts $output_file "ddr_dq_iob20 : ddr_dq_iob port map( "
set line_num 431; puts $output_file "                                     ddr_dq_inout       => ddr_dq(20),"
set line_num 432; puts $output_file "                                     write_data_rising  => write_data_rising(20),"
set line_num 433; puts $output_file "                                     write_data_falling => write_data_falling(20),"
set line_num 434; puts $output_file "                                     read_data_in       => dq(20),"
set line_num 435; puts $output_file "                                     clk90              => clk90,"
set line_num 436; puts $output_file "                                     write_en_val       => write_en_val,"
set line_num 437; puts $output_file "                                     reset              => reset270_r"
set line_num 438; puts $output_file "                                     );"
set line_num 439; puts $output_file ""
set line_num 440; puts $output_file "ddr_dq_iob21 : ddr_dq_iob port map( "
set line_num 441; puts $output_file "                                     ddr_dq_inout       => ddr_dq(21),"
set line_num 442; puts $output_file "                                     write_data_rising  => write_data_rising(21),"
set line_num 443; puts $output_file "                                     write_data_falling => write_data_falling(21),"
set line_num 444; puts $output_file "                                     read_data_in       => dq(21),"
set line_num 445; puts $output_file "                                     clk90              => clk90,"
set line_num 446; puts $output_file "                                     write_en_val       => write_en_val,"
set line_num 447; puts $output_file "                                     reset              => reset270_r"
set line_num 448; puts $output_file "                                     );"
set line_num 449; puts $output_file ""
set line_num 450; puts $output_file "ddr_dq_iob22 : ddr_dq_iob port map( "
set line_num 451; puts $output_file "                                     ddr_dq_inout       => ddr_dq(22),"
set line_num 452; puts $output_file "                                     write_data_rising  => write_data_rising(22),"
set line_num 453; puts $output_file "                                     write_data_falling => write_data_falling(22),"
set line_num 454; puts $output_file "                                     read_data_in       => dq(22),"
set line_num 455; puts $output_file "                                     clk90              => clk90,"
set line_num 456; puts $output_file "                                     write_en_val       => write_en_val,"
set line_num 457; puts $output_file "                                     reset              => reset270_r"
set line_num 458; puts $output_file "                                     );"
set line_num 459; puts $output_file ""
set line_num 460; puts $output_file "ddr_dq_iob23 : ddr_dq_iob port map( "
set line_num 461; puts $output_file "                                     ddr_dq_inout       => ddr_dq(23),"
set line_num 462; puts $output_file "                                     write_data_rising  => write_data_rising(23),"
set line_num 463; puts $output_file "                                     write_data_falling => write_data_falling(23),"
set line_num 464; puts $output_file "                                     read_data_in       => dq(23),"
set line_num 465; puts $output_file "                                     clk90              => clk90,"
set line_num 466; puts $output_file "                                     write_en_val       => write_en_val,"
set line_num 467; puts $output_file "                                     reset              => reset270_r"
set line_num 468; puts $output_file "                                     );"
set line_num 469; puts $output_file ""
set line_num 470; puts $output_file "ddr_dq_iob24 : ddr_dq_iob port map( "
set line_num 471; puts $output_file "                                     ddr_dq_inout       => ddr_dq(24),"
set line_num 472; puts $output_file "                                     write_data_rising  => write_data_rising(24),"
set line_num 473; puts $output_file "                                     write_data_falling => write_data_falling(24),"
set line_num 474; puts $output_file "                                     read_data_in       => dq(24),"
set line_num 475; puts $output_file "                                     clk90              => clk90,"
set line_num 476; puts $output_file "                                     write_en_val       => write_en_val,"
set line_num 477; puts $output_file "                                     reset              => reset270_r"
set line_num 478; puts $output_file "                                     );"
set line_num 479; puts $output_file ""
set line_num 480; puts $output_file "ddr_dq_iob25 : ddr_dq_iob port map( "
set line_num 481; puts $output_file "                                     ddr_dq_inout       => ddr_dq(25),"
set line_num 482; puts $output_file "                                     write_data_rising  => write_data_rising(25),"
set line_num 483; puts $output_file "                                     write_data_falling => write_data_falling(25),"
set line_num 484; puts $output_file "                                     read_data_in       => dq(25),"
set line_num 485; puts $output_file "                                     clk90              => clk90,"
set line_num 486; puts $output_file "                                     write_en_val       => write_en_val,"
set line_num 487; puts $output_file "                                     reset              => reset270_r"
set line_num 488; puts $output_file "                                     );"
set line_num 489; puts $output_file ""
set line_num 490; puts $output_file "ddr_dq_iob26 : ddr_dq_iob port map( "
set line_num 491; puts $output_file "                                     ddr_dq_inout       => ddr_dq(26),"
set line_num 492; puts $output_file "                                     write_data_rising  => write_data_rising(26),"
set line_num 493; puts $output_file "                                     write_data_falling => write_data_falling(26),"
set line_num 494; puts $output_file "                                     read_data_in       => dq(26),"
set line_num 495; puts $output_file "                                     clk90              => clk90,"
set line_num 496; puts $output_file "                                     write_en_val       => write_en_val,"
set line_num 497; puts $output_file "                                     reset              => reset270_r"
set line_num 498; puts $output_file "                                     );"
set line_num 499; puts $output_file ""
set line_num 500; puts $output_file "ddr_dq_iob27 : ddr_dq_iob port map( "
set line_num 501; puts $output_file "                                     ddr_dq_inout       => ddr_dq(27),"
set line_num 502; puts $output_file "                                     write_data_rising  => write_data_rising(27),"
set line_num 503; puts $output_file "                                     write_data_falling => write_data_falling(27),"
set line_num 504; puts $output_file "                                     read_data_in       => dq(27),"
set line_num 505; puts $output_file "                                     clk90              => clk90,"
set line_num 506; puts $output_file "                                     write_en_val       => write_en_val,"
set line_num 507; puts $output_file "                                     reset              => reset270_r"
set line_num 508; puts $output_file "                                     );"
set line_num 509; puts $output_file ""
set line_num 510; puts $output_file "ddr_dq_iob28 : ddr_dq_iob port map( "
set line_num 511; puts $output_file "                                     ddr_dq_inout       => ddr_dq(28),"
set line_num 512; puts $output_file "                                     write_data_rising  => write_data_rising(28),"
set line_num 513; puts $output_file "                                     write_data_falling => write_data_falling(28),"
set line_num 514; puts $output_file "                                     read_data_in       => dq(28),"
set line_num 515; puts $output_file "                                     clk90              => clk90,"
set line_num 516; puts $output_file "                                     write_en_val       => write_en_val,"
set line_num 517; puts $output_file "                                     reset              => reset270_r"
set line_num 518; puts $output_file "                                     );"
set line_num 519; puts $output_file ""
set line_num 520; puts $output_file "ddr_dq_iob29 : ddr_dq_iob port map( "
set line_num 521; puts $output_file "                                     ddr_dq_inout       => ddr_dq(29),"
set line_num 522; puts $output_file "                                     write_data_rising  => write_data_rising(29),"
set line_num 523; puts $output_file "                                     write_data_falling => write_data_falling(29),"
set line_num 524; puts $output_file "                                     read_data_in       => dq(29),"
set line_num 525; puts $output_file "                                     clk90              => clk90,"
set line_num 526; puts $output_file "                                     write_en_val       => write_en_val,"
set line_num 527; puts $output_file "                                     reset              => reset270_r"
set line_num 528; puts $output_file "                                     );"
set line_num 529; puts $output_file ""
set line_num 530; puts $output_file "ddr_dq_iob30 : ddr_dq_iob port map( "
set line_num 531; puts $output_file "                                     ddr_dq_inout       => ddr_dq(30),"
set line_num 532; puts $output_file "                                     write_data_rising  => write_data_rising(30),"
set line_num 533; puts $output_file "                                     write_data_falling => write_data_falling(30),"
set line_num 534; puts $output_file "                                     read_data_in       => dq(30),"
set line_num 535; puts $output_file "                                     clk90              => clk90,"
set line_num 536; puts $output_file "                                     write_en_val       => write_en_val,"
set line_num 537; puts $output_file "                                     reset              => reset270_r"
set line_num 538; puts $output_file "                                     );"
set line_num 539; puts $output_file ""
set line_num 540; puts $output_file "ddr_dq_iob31 : ddr_dq_iob port map( "
set line_num 541; puts $output_file "                                     ddr_dq_inout       => ddr_dq(31),"
set line_num 542; puts $output_file "                                     write_data_rising  => write_data_rising(31),"
set line_num 543; puts $output_file "                                     write_data_falling => write_data_falling(31),"
set line_num 544; puts $output_file "                                     read_data_in       => dq(31),"
set line_num 545; puts $output_file "                                     clk90              => clk90,"
set line_num 546; puts $output_file "                                     write_en_val       => write_en_val,"
set line_num 547; puts $output_file "                                     reset              => reset270_r"
set line_num 548; puts $output_file "                                     );"
set line_num 549; puts $output_file ""
set line_num 550; puts $output_file "ddr_dq_iob32 : ddr_dq_iob port map( "
set line_num 551; puts $output_file "                                     ddr_dq_inout       => ddr_dq(32),"
set line_num 552; puts $output_file "                                     write_data_rising  => write_data_rising(32),"
set line_num 553; puts $output_file "                                     write_data_falling => write_data_falling(32),"
set line_num 554; puts $output_file "                                     read_data_in       => dq(32),"
set line_num 555; puts $output_file "                                     clk90              => clk90,"
set line_num 556; puts $output_file "                                     write_en_val       => write_en_val,"
set line_num 557; puts $output_file "                                     reset              => reset270_r"
set line_num 558; puts $output_file "                                     );"
set line_num 559; puts $output_file ""
set line_num 560; puts $output_file "ddr_dq_iob33 : ddr_dq_iob port map( "
set line_num 561; puts $output_file "                                     ddr_dq_inout       => ddr_dq(33),"
set line_num 562; puts $output_file "                                     write_data_rising  => write_data_rising(33),"
set line_num 563; puts $output_file "                                     write_data_falling => write_data_falling(33),"
set line_num 564; puts $output_file "                                     read_data_in       => dq(33),"
set line_num 565; puts $output_file "                                     clk90              => clk90,"
set line_num 566; puts $output_file "                                     write_en_val       => write_en_val,"
set line_num 567; puts $output_file "                                     reset              => reset270_r"
set line_num 568; puts $output_file "                                     );"
set line_num 569; puts $output_file ""
set line_num 570; puts $output_file "ddr_dq_iob34 : ddr_dq_iob port map( "
set line_num 571; puts $output_file "                                     ddr_dq_inout       => ddr_dq(34),"
set line_num 572; puts $output_file "                                     write_data_rising  => write_data_rising(34),"
set line_num 573; puts $output_file "                                     write_data_falling => write_data_falling(34),"
set line_num 574; puts $output_file "                                     read_data_in       => dq(34),"
set line_num 575; puts $output_file "                                     clk90              => clk90,"
set line_num 576; puts $output_file "                                     write_en_val       => write_en_val,"
set line_num 577; puts $output_file "                                     reset              => reset270_r"
set line_num 578; puts $output_file "                                     );"
set line_num 579; puts $output_file ""
set line_num 580; puts $output_file "ddr_dq_iob35 : ddr_dq_iob port map( "
set line_num 581; puts $output_file "                                     ddr_dq_inout       => ddr_dq(35),"
set line_num 582; puts $output_file "                                     write_data_rising  => write_data_rising(35),"
set line_num 583; puts $output_file "                                     write_data_falling => write_data_falling(35),"
set line_num 584; puts $output_file "                                     read_data_in       => dq(35),"
set line_num 585; puts $output_file "                                     clk90              => clk90,"
set line_num 586; puts $output_file "                                     write_en_val       => write_en_val,"
set line_num 587; puts $output_file "                                     reset              => reset270_r"
set line_num 588; puts $output_file "                                     );"
set line_num 589; puts $output_file ""
set line_num 590; puts $output_file "ddr_dq_iob36 : ddr_dq_iob port map( "
set line_num 591; puts $output_file "                                     ddr_dq_inout       => ddr_dq(36),"
set line_num 592; puts $output_file "                                     write_data_rising  => write_data_rising(36),"
set line_num 593; puts $output_file "                                     write_data_falling => write_data_falling(36),"
set line_num 594; puts $output_file "                                     read_data_in       => dq(36),"
set line_num 595; puts $output_file "                                     clk90              => clk90,"
set line_num 596; puts $output_file "                                     write_en_val       => write_en_val,"
set line_num 597; puts $output_file "                                     reset              => reset270_r"
set line_num 598; puts $output_file "                                     );"
set line_num 599; puts $output_file ""
set line_num 600; puts $output_file "ddr_dq_iob37 : ddr_dq_iob port map( "
set line_num 601; puts $output_file "                                     ddr_dq_inout       => ddr_dq(37),"
set line_num 602; puts $output_file "                                     write_data_rising  => write_data_rising(37),"
set line_num 603; puts $output_file "                                     write_data_falling => write_data_falling(37),"
set line_num 604; puts $output_file "                                     read_data_in       => dq(37),"
set line_num 605; puts $output_file "                                     clk90              => clk90,"
set line_num 606; puts $output_file "                                     write_en_val       => write_en_val,"
set line_num 607; puts $output_file "                                     reset              => reset270_r"
set line_num 608; puts $output_file "                                     );"
set line_num 609; puts $output_file ""
set line_num 610; puts $output_file "ddr_dq_iob38 : ddr_dq_iob port map( "
set line_num 611; puts $output_file "                                     ddr_dq_inout       => ddr_dq(38),"
set line_num 612; puts $output_file "                                     write_data_rising  => write_data_rising(38),"
set line_num 613; puts $output_file "                                     write_data_falling => write_data_falling(38),"
set line_num 614; puts $output_file "                                     read_data_in       => dq(38),"
set line_num 615; puts $output_file "                                     clk90              => clk90,"
set line_num 616; puts $output_file "                                     write_en_val       => write_en_val,"
set line_num 617; puts $output_file "                                     reset              => reset270_r"
set line_num 618; puts $output_file "                                     );"
set line_num 619; puts $output_file ""
set line_num 620; puts $output_file "ddr_dq_iob39 : ddr_dq_iob port map( "
set line_num 621; puts $output_file "                                     ddr_dq_inout       => ddr_dq(39),"
set line_num 622; puts $output_file "                                     write_data_rising  => write_data_rising(39),"
set line_num 623; puts $output_file "                                     write_data_falling => write_data_falling(39),"
set line_num 624; puts $output_file "                                     read_data_in       => dq(39),"
set line_num 625; puts $output_file "                                     clk90              => clk90,"
set line_num 626; puts $output_file "                                     write_en_val       => write_en_val,"
set line_num 627; puts $output_file "                                     reset              => reset270_r"
set line_num 628; puts $output_file "                                     );"
set line_num 629; puts $output_file ""
set line_num 630; puts $output_file "ddr_dq_iob40 : ddr_dq_iob port map( "
set line_num 631; puts $output_file "                                     ddr_dq_inout       => ddr_dq(40),"
set line_num 632; puts $output_file "                                     write_data_rising  => write_data_rising(40),"
set line_num 633; puts $output_file "                                     write_data_falling => write_data_falling(40),"
set line_num 634; puts $output_file "                                     read_data_in       => dq(40),"
set line_num 635; puts $output_file "                                     clk90              => clk90,"
set line_num 636; puts $output_file "                                     write_en_val       => write_en_val,"
set line_num 637; puts $output_file "                                     reset              => reset270_r"
set line_num 638; puts $output_file "                                     );"
set line_num 639; puts $output_file ""
set line_num 640; puts $output_file "ddr_dq_iob41 : ddr_dq_iob port map( "
set line_num 641; puts $output_file "                                     ddr_dq_inout       => ddr_dq(41),"
set line_num 642; puts $output_file "                                     write_data_rising  => write_data_rising(41),"
set line_num 643; puts $output_file "                                     write_data_falling => write_data_falling(41),"
set line_num 644; puts $output_file "                                     read_data_in       => dq(41),"
set line_num 645; puts $output_file "                                     clk90              => clk90,"
set line_num 646; puts $output_file "                                     write_en_val       => write_en_val,"
set line_num 647; puts $output_file "                                     reset              => reset270_r"
set line_num 648; puts $output_file "                                     );"
set line_num 649; puts $output_file ""
set line_num 650; puts $output_file "ddr_dq_iob42 : ddr_dq_iob port map( "
set line_num 651; puts $output_file "                                     ddr_dq_inout       => ddr_dq(42),"
set line_num 652; puts $output_file "                                     write_data_rising  => write_data_rising(42),"
set line_num 653; puts $output_file "                                     write_data_falling => write_data_falling(42),"
set line_num 654; puts $output_file "                                     read_data_in       => dq(42),"
set line_num 655; puts $output_file "                                     clk90              => clk90,"
set line_num 656; puts $output_file "                                     write_en_val       => write_en_val,"
set line_num 657; puts $output_file "                                     reset              => reset270_r"
set line_num 658; puts $output_file "                                     );"
set line_num 659; puts $output_file ""
set line_num 660; puts $output_file "ddr_dq_iob43 : ddr_dq_iob port map( "
set line_num 661; puts $output_file "                                     ddr_dq_inout       => ddr_dq(43),"
set line_num 662; puts $output_file "                                     write_data_rising  => write_data_rising(43),"
set line_num 663; puts $output_file "                                     write_data_falling => write_data_falling(43),"
set line_num 664; puts $output_file "                                     read_data_in       => dq(43),"
set line_num 665; puts $output_file "                                     clk90              => clk90,"
set line_num 666; puts $output_file "                                     write_en_val       => write_en_val,"
set line_num 667; puts $output_file "                                     reset              => reset270_r"
set line_num 668; puts $output_file "                                     );"
set line_num 669; puts $output_file ""
set line_num 670; puts $output_file "ddr_dq_iob44 : ddr_dq_iob port map( "
set line_num 671; puts $output_file "                                     ddr_dq_inout       => ddr_dq(44),"
set line_num 672; puts $output_file "                                     write_data_rising  => write_data_rising(44),"
set line_num 673; puts $output_file "                                     write_data_falling => write_data_falling(44),"
set line_num 674; puts $output_file "                                     read_data_in       => dq(44),"
set line_num 675; puts $output_file "                                     clk90              => clk90,"
set line_num 676; puts $output_file "                                     write_en_val       => write_en_val,"
set line_num 677; puts $output_file "                                     reset              => reset270_r"
set line_num 678; puts $output_file "                                     );"
set line_num 679; puts $output_file ""
set line_num 680; puts $output_file "ddr_dq_iob45 : ddr_dq_iob port map( "
set line_num 681; puts $output_file "                                     ddr_dq_inout       => ddr_dq(45),"
set line_num 682; puts $output_file "                                     write_data_rising  => write_data_rising(45),"
set line_num 683; puts $output_file "                                     write_data_falling => write_data_falling(45),"
set line_num 684; puts $output_file "                                     read_data_in       => dq(45),"
set line_num 685; puts $output_file "                                     clk90              => clk90,"
set line_num 686; puts $output_file "                                     write_en_val       => write_en_val,"
set line_num 687; puts $output_file "                                     reset              => reset270_r"
set line_num 688; puts $output_file "                                     );"
set line_num 689; puts $output_file ""
set line_num 690; puts $output_file "ddr_dq_iob46 : ddr_dq_iob port map( "
set line_num 691; puts $output_file "                                     ddr_dq_inout       => ddr_dq(46),"
set line_num 692; puts $output_file "                                     write_data_rising  => write_data_rising(46),"
set line_num 693; puts $output_file "                                     write_data_falling => write_data_falling(46),"
set line_num 694; puts $output_file "                                     read_data_in       => dq(46),"
set line_num 695; puts $output_file "                                     clk90              => clk90,"
set line_num 696; puts $output_file "                                     write_en_val       => write_en_val,"
set line_num 697; puts $output_file "                                     reset              => reset270_r"
set line_num 698; puts $output_file "                                     );"
set line_num 699; puts $output_file ""
set line_num 700; puts $output_file "ddr_dq_iob47 : ddr_dq_iob port map( "
set line_num 701; puts $output_file "                                     ddr_dq_inout       => ddr_dq(47),"
set line_num 702; puts $output_file "                                     write_data_rising  => write_data_rising(47),"
set line_num 703; puts $output_file "                                     write_data_falling => write_data_falling(47),"
set line_num 704; puts $output_file "                                     read_data_in       => dq(47),"
set line_num 705; puts $output_file "                                     clk90              => clk90,"
set line_num 706; puts $output_file "                                     write_en_val       => write_en_val,"
set line_num 707; puts $output_file "                                     reset              => reset270_r"
set line_num 708; puts $output_file "                                     );"
set line_num 709; puts $output_file ""
set line_num 710; puts $output_file "ddr_dq_iob48 : ddr_dq_iob port map( "
set line_num 711; puts $output_file "                                     ddr_dq_inout       => ddr_dq(48),"
set line_num 712; puts $output_file "                                     write_data_rising  => write_data_rising(48),"
set line_num 713; puts $output_file "                                     write_data_falling => write_data_falling(48),"
set line_num 714; puts $output_file "                                     read_data_in       => dq(48),"
set line_num 715; puts $output_file "                                     clk90              => clk90,"
set line_num 716; puts $output_file "                                     write_en_val       => write_en_val,"
set line_num 717; puts $output_file "                                     reset              => reset270_r"
set line_num 718; puts $output_file "                                     );"
set line_num 719; puts $output_file ""
set line_num 720; puts $output_file "ddr_dq_iob49 : ddr_dq_iob port map( "
set line_num 721; puts $output_file "                                     ddr_dq_inout       => ddr_dq(49),"
set line_num 722; puts $output_file "                                     write_data_rising  => write_data_rising(49),"
set line_num 723; puts $output_file "                                     write_data_falling => write_data_falling(49),"
set line_num 724; puts $output_file "                                     read_data_in       => dq(49),"
set line_num 725; puts $output_file "                                     clk90              => clk90,"
set line_num 726; puts $output_file "                                     write_en_val       => write_en_val,"
set line_num 727; puts $output_file "                                     reset              => reset270_r"
set line_num 728; puts $output_file "                                     );"
set line_num 729; puts $output_file ""
set line_num 730; puts $output_file "ddr_dq_iob50 : ddr_dq_iob port map( "
set line_num 731; puts $output_file "                                     ddr_dq_inout       => ddr_dq(50),"
set line_num 732; puts $output_file "                                     write_data_rising  => write_data_rising(50),"
set line_num 733; puts $output_file "                                     write_data_falling => write_data_falling(50),"
set line_num 734; puts $output_file "                                     read_data_in       => dq(50),"
set line_num 735; puts $output_file "                                     clk90              => clk90,"
set line_num 736; puts $output_file "                                     write_en_val       => write_en_val,"
set line_num 737; puts $output_file "                                     reset              => reset270_r"
set line_num 738; puts $output_file "                                     );"
set line_num 739; puts $output_file ""
set line_num 740; puts $output_file "ddr_dq_iob51 : ddr_dq_iob port map( "
set line_num 741; puts $output_file "                                     ddr_dq_inout       => ddr_dq(51),"
set line_num 742; puts $output_file "                                     write_data_rising  => write_data_rising(51),"
set line_num 743; puts $output_file "                                     write_data_falling => write_data_falling(51),"
set line_num 744; puts $output_file "                                     read_data_in       => dq(51),"
set line_num 745; puts $output_file "                                     clk90              => clk90,"
set line_num 746; puts $output_file "                                     write_en_val       => write_en_val,"
set line_num 747; puts $output_file "                                     reset              => reset270_r"
set line_num 748; puts $output_file "                                     );"
set line_num 749; puts $output_file ""
set line_num 750; puts $output_file "ddr_dq_iob52 : ddr_dq_iob port map( "
set line_num 751; puts $output_file "                                     ddr_dq_inout       => ddr_dq(52),"
set line_num 752; puts $output_file "                                     write_data_rising  => write_data_rising(52),"
set line_num 753; puts $output_file "                                     write_data_falling => write_data_falling(52),"
set line_num 754; puts $output_file "                                     read_data_in       => dq(52),"
set line_num 755; puts $output_file "                                     clk90              => clk90,"
set line_num 756; puts $output_file "                                     write_en_val       => write_en_val,"
set line_num 757; puts $output_file "                                     reset              => reset270_r"
set line_num 758; puts $output_file "                                     );"
set line_num 759; puts $output_file ""
set line_num 760; puts $output_file "ddr_dq_iob53 : ddr_dq_iob port map( "
set line_num 761; puts $output_file "                                     ddr_dq_inout       => ddr_dq(53),"
set line_num 762; puts $output_file "                                     write_data_rising  => write_data_rising(53),"
set line_num 763; puts $output_file "                                     write_data_falling => write_data_falling(53),"
set line_num 764; puts $output_file "                                     read_data_in       => dq(53),"
set line_num 765; puts $output_file "                                     clk90              => clk90,"
set line_num 766; puts $output_file "                                     write_en_val       => write_en_val,"
set line_num 767; puts $output_file "                                     reset              => reset270_r"
set line_num 768; puts $output_file "                                     );"
set line_num 769; puts $output_file ""
set line_num 770; puts $output_file "ddr_dq_iob54 : ddr_dq_iob port map( "
set line_num 771; puts $output_file "                                     ddr_dq_inout       => ddr_dq(54),"
set line_num 772; puts $output_file "                                     write_data_rising  => write_data_rising(54),"
set line_num 773; puts $output_file "                                     write_data_falling => write_data_falling(54),"
set line_num 774; puts $output_file "                                     read_data_in       => dq(54),"
set line_num 775; puts $output_file "                                     clk90              => clk90,"
set line_num 776; puts $output_file "                                     write_en_val       => write_en_val,"
set line_num 777; puts $output_file "                                     reset              => reset270_r"
set line_num 778; puts $output_file "                                     );"
set line_num 779; puts $output_file ""
set line_num 780; puts $output_file "ddr_dq_iob55 : ddr_dq_iob port map( "
set line_num 781; puts $output_file "                                     ddr_dq_inout       => ddr_dq(55),"
set line_num 782; puts $output_file "                                     write_data_rising  => write_data_rising(55),"
set line_num 783; puts $output_file "                                     write_data_falling => write_data_falling(55),"
set line_num 784; puts $output_file "                                     read_data_in       => dq(55),"
set line_num 785; puts $output_file "                                     clk90              => clk90,"
set line_num 786; puts $output_file "                                     write_en_val       => write_en_val,"
set line_num 787; puts $output_file "                                     reset              => reset270_r"
set line_num 788; puts $output_file "                                     );"
set line_num 789; puts $output_file ""
set line_num 790; puts $output_file "ddr_dq_iob56 : ddr_dq_iob port map( "
set line_num 791; puts $output_file "                                     ddr_dq_inout       => ddr_dq(56),"
set line_num 792; puts $output_file "                                     write_data_rising  => write_data_rising(56),"
set line_num 793; puts $output_file "                                     write_data_falling => write_data_falling(56),"
set line_num 794; puts $output_file "                                     read_data_in       => dq(56),"
set line_num 795; puts $output_file "                                     clk90              => clk90,"
set line_num 796; puts $output_file "                                     write_en_val       => write_en_val,"
set line_num 797; puts $output_file "                                     reset              => reset270_r"
set line_num 798; puts $output_file "                                     );"
set line_num 799; puts $output_file ""
set line_num 800; puts $output_file "ddr_dq_iob57 : ddr_dq_iob port map( "
set line_num 801; puts $output_file "                                     ddr_dq_inout       => ddr_dq(57),"
set line_num 802; puts $output_file "                                     write_data_rising  => write_data_rising(57),"
set line_num 803; puts $output_file "                                     write_data_falling => write_data_falling(57),"
set line_num 804; puts $output_file "                                     read_data_in       => dq(57),"
set line_num 805; puts $output_file "                                     clk90              => clk90,"
set line_num 806; puts $output_file "                                     write_en_val       => write_en_val,"
set line_num 807; puts $output_file "                                     reset              => reset270_r"
set line_num 808; puts $output_file "                                     );"
set line_num 809; puts $output_file ""
set line_num 810; puts $output_file "ddr_dq_iob58 : ddr_dq_iob port map( "
set line_num 811; puts $output_file "                                     ddr_dq_inout       => ddr_dq(58),"
set line_num 812; puts $output_file "                                     write_data_rising  => write_data_rising(58),"
set line_num 813; puts $output_file "                                     write_data_falling => write_data_falling(58),"
set line_num 814; puts $output_file "                                     read_data_in       => dq(58),"
set line_num 815; puts $output_file "                                     clk90              => clk90,"
set line_num 816; puts $output_file "                                     write_en_val       => write_en_val,"
set line_num 817; puts $output_file "                                     reset              => reset270_r"
set line_num 818; puts $output_file "                                     );"
set line_num 819; puts $output_file ""
set line_num 820; puts $output_file "ddr_dq_iob59 : ddr_dq_iob port map( "
set line_num 821; puts $output_file "                                     ddr_dq_inout       => ddr_dq(59),"
set line_num 822; puts $output_file "                                     write_data_rising  => write_data_rising(59),"
set line_num 823; puts $output_file "                                     write_data_falling => write_data_falling(59),"
set line_num 824; puts $output_file "                                     read_data_in       => dq(59),"
set line_num 825; puts $output_file "                                     clk90              => clk90,"
set line_num 826; puts $output_file "                                     write_en_val       => write_en_val,"
set line_num 827; puts $output_file "                                     reset              => reset270_r"
set line_num 828; puts $output_file "                                     );"
set line_num 829; puts $output_file ""
set line_num 830; puts $output_file "ddr_dq_iob60 : ddr_dq_iob port map( "
set line_num 831; puts $output_file "                                     ddr_dq_inout       => ddr_dq(60),"
set line_num 832; puts $output_file "                                     write_data_rising  => write_data_rising(60),"
set line_num 833; puts $output_file "                                     write_data_falling => write_data_falling(60),"
set line_num 834; puts $output_file "                                     read_data_in       => dq(60),"
set line_num 835; puts $output_file "                                     clk90              => clk90,"
set line_num 836; puts $output_file "                                     write_en_val       => write_en_val,"
set line_num 837; puts $output_file "                                     reset              => reset270_r"
set line_num 838; puts $output_file "                                     );"
set line_num 839; puts $output_file ""
set line_num 840; puts $output_file "ddr_dq_iob61 : ddr_dq_iob port map( "
set line_num 841; puts $output_file "                                     ddr_dq_inout       => ddr_dq(61),"
set line_num 842; puts $output_file "                                     write_data_rising  => write_data_rising(61),"
set line_num 843; puts $output_file "                                     write_data_falling => write_data_falling(61),"
set line_num 844; puts $output_file "                                     read_data_in       => dq(61),"
set line_num 845; puts $output_file "                                     clk90              => clk90,"
set line_num 846; puts $output_file "                                     write_en_val       => write_en_val,"
set line_num 847; puts $output_file "                                     reset              => reset270_r"
set line_num 848; puts $output_file "                                     );"
set line_num 849; puts $output_file ""
set line_num 850; puts $output_file "ddr_dq_iob62 : ddr_dq_iob port map( "
set line_num 851; puts $output_file "                                     ddr_dq_inout       => ddr_dq(62),"
set line_num 852; puts $output_file "                                     write_data_rising  => write_data_rising(62),"
set line_num 853; puts $output_file "                                     write_data_falling => write_data_falling(62),"
set line_num 854; puts $output_file "                                     read_data_in       => dq(62),"
set line_num 855; puts $output_file "                                     clk90              => clk90,"
set line_num 856; puts $output_file "                                     write_en_val       => write_en_val,"
set line_num 857; puts $output_file "                                     reset              => reset270_r"
set line_num 858; puts $output_file "                                     );"
set line_num 859; puts $output_file ""
set line_num 860; puts $output_file "ddr_dq_iob63 : ddr_dq_iob port map( "
set line_num 861; puts $output_file "                                     ddr_dq_inout       => ddr_dq(63),"
set line_num 862; puts $output_file "                                     write_data_rising  => write_data_rising(63),"
set line_num 863; puts $output_file "                                     write_data_falling => write_data_falling(63),"
set line_num 864; puts $output_file "                                     read_data_in       => dq(63),"
set line_num 865; puts $output_file "                                     clk90              => clk90,"
set line_num 866; puts $output_file "                                     write_en_val       => write_en_val,"
set line_num 867; puts $output_file "                                     reset              => reset270_r"
set line_num 868; puts $output_file "                                     );"
set line_num 869; puts $output_file ""
set line_num 870; puts $output_file "ddr_dq_iob64 : ddr_dq_iob port map( "
set line_num 871; puts $output_file "                                     ddr_dq_inout       => ddr_dq(64),"
set line_num 872; puts $output_file "                                     write_data_rising  => write_data_rising(64),"
set line_num 873; puts $output_file "                                     write_data_falling => write_data_falling(64),"
set line_num 874; puts $output_file "                                     read_data_in       => dq(64),"
set line_num 875; puts $output_file "                                     clk90              => clk90,"
set line_num 876; puts $output_file "                                     write_en_val       => write_en_val,"
set line_num 877; puts $output_file "                                     reset              => reset270_r"
set line_num 878; puts $output_file "                                     );"
set line_num 879; puts $output_file ""
set line_num 880; puts $output_file "ddr_dq_iob65 : ddr_dq_iob port map( "
set line_num 881; puts $output_file "                                     ddr_dq_inout       => ddr_dq(65),"
set line_num 882; puts $output_file "                                     write_data_rising  => write_data_rising(65),"
set line_num 883; puts $output_file "                                     write_data_falling => write_data_falling(65),"
set line_num 884; puts $output_file "                                     read_data_in       => dq(65),"
set line_num 885; puts $output_file "                                     clk90              => clk90,"
set line_num 886; puts $output_file "                                     write_en_val       => write_en_val,"
set line_num 887; puts $output_file "                                     reset              => reset270_r"
set line_num 888; puts $output_file "                                     );"
set line_num 889; puts $output_file ""
set line_num 890; puts $output_file "ddr_dq_iob66 : ddr_dq_iob port map( "
set line_num 891; puts $output_file "                                     ddr_dq_inout       => ddr_dq(66),"
set line_num 892; puts $output_file "                                     write_data_rising  => write_data_rising(66),"
set line_num 893; puts $output_file "                                     write_data_falling => write_data_falling(66),"
set line_num 894; puts $output_file "                                     read_data_in       => dq(66),"
set line_num 895; puts $output_file "                                     clk90              => clk90,"
set line_num 896; puts $output_file "                                     write_en_val       => write_en_val,"
set line_num 897; puts $output_file "                                     reset              => reset270_r"
set line_num 898; puts $output_file "                                     );"
set line_num 899; puts $output_file ""
set line_num 900; puts $output_file "ddr_dq_iob67 : ddr_dq_iob port map( "
set line_num 901; puts $output_file "                                     ddr_dq_inout       => ddr_dq(67),"
set line_num 902; puts $output_file "                                     write_data_rising  => write_data_rising(67),"
set line_num 903; puts $output_file "                                     write_data_falling => write_data_falling(67),"
set line_num 904; puts $output_file "                                     read_data_in       => dq(67),"
set line_num 905; puts $output_file "                                     clk90              => clk90,"
set line_num 906; puts $output_file "                                     write_en_val       => write_en_val,"
set line_num 907; puts $output_file "                                     reset              => reset270_r"
set line_num 908; puts $output_file "                                     );"
set line_num 909; puts $output_file ""
set line_num 910; puts $output_file "ddr_dq_iob68 : ddr_dq_iob port map( "
set line_num 911; puts $output_file "                                     ddr_dq_inout       => ddr_dq(68),"
set line_num 912; puts $output_file "                                     write_data_rising  => write_data_rising(68),"
set line_num 913; puts $output_file "                                     write_data_falling => write_data_falling(68),"
set line_num 914; puts $output_file "                                     read_data_in       => dq(68),"
set line_num 915; puts $output_file "                                     clk90              => clk90,"
set line_num 916; puts $output_file "                                     write_en_val       => write_en_val,"
set line_num 917; puts $output_file "                                     reset              => reset270_r"
set line_num 918; puts $output_file "                                     );"
set line_num 919; puts $output_file ""
set line_num 920; puts $output_file "ddr_dq_iob69 : ddr_dq_iob port map( "
set line_num 921; puts $output_file "                                     ddr_dq_inout       => ddr_dq(69),"
set line_num 922; puts $output_file "                                     write_data_rising  => write_data_rising(69),"
set line_num 923; puts $output_file "                                     write_data_falling => write_data_falling(69),"
set line_num 924; puts $output_file "                                     read_data_in       => dq(69),"
set line_num 925; puts $output_file "                                     clk90              => clk90,"
set line_num 926; puts $output_file "                                     write_en_val       => write_en_val,"
set line_num 927; puts $output_file "                                     reset              => reset270_r"
set line_num 928; puts $output_file "                                     );"
set line_num 929; puts $output_file ""
set line_num 930; puts $output_file "ddr_dq_iob70 : ddr_dq_iob port map( "
set line_num 931; puts $output_file "                                     ddr_dq_inout       => ddr_dq(70),"
set line_num 932; puts $output_file "                                     write_data_rising  => write_data_rising(70),"
set line_num 933; puts $output_file "                                     write_data_falling => write_data_falling(70),"
set line_num 934; puts $output_file "                                     read_data_in       => dq(70),"
set line_num 935; puts $output_file "                                     clk90              => clk90,"
set line_num 936; puts $output_file "                                     write_en_val       => write_en_val,"
set line_num 937; puts $output_file "                                     reset              => reset270_r"
set line_num 938; puts $output_file "                                     );"
set line_num 939; puts $output_file ""
set line_num 940; puts $output_file "ddr_dq_iob71 : ddr_dq_iob port map( "
set line_num 941; puts $output_file "                                     ddr_dq_inout       => ddr_dq(71),"
set line_num 942; puts $output_file "                                     write_data_rising  => write_data_rising(71),"
set line_num 943; puts $output_file "                                     write_data_falling => write_data_falling(71),"
set line_num 944; puts $output_file "                                     read_data_in       => dq(71),"
set line_num 945; puts $output_file "                                     clk90              => clk90,"
set line_num 946; puts $output_file "                                     write_en_val       => write_en_val,"
set line_num 947; puts $output_file "                                     reset              => reset270_r"
set line_num 948; puts $output_file "                                     );"
set line_num 949; puts $output_file ""
set line_num 950; puts $output_file ""
set line_num 951; puts $output_file "--***********************************************************************"
set line_num 952; puts $output_file "--  DM IOB instantiations"
set line_num 953; puts $output_file "--***********************************************************************  "
set line_num 954; puts $output_file ""
set line_num 955; puts $output_file ""
set line_num 956; puts $output_file "ddr2_dm0	:	ddr2_dm_72bit	port	map	( "
set line_num 957; puts $output_file "                             ddr_dm       => ddr_dm(8 downto 0),"
set line_num 958; puts $output_file "                             mask_falling => data_mask_f(8 downto 0),"
set line_num 959; puts $output_file "                             mask_rising  => data_mask_r(8 downto 0),"
set line_num 960; puts $output_file "                             write_en_val => write_en_val,"
set line_num 961; puts $output_file "                             clk90        => clk90"
set line_num 962; puts $output_file "                            );    "
set line_num 963; puts $output_file ""
set line_num 964; puts $output_file ""
set line_num 965; puts $output_file "end   arc_data_path_iobs_72bit;  "
set line_num 966; puts $output_file "         "
set line_num 967; puts $output_file " "
set line_num 968; puts $output_file ""
set line_num 969; puts $output_file ""
set line_num 970; puts $output_file ""
set line_num 971; puts $output_file ""
set line_num 972; puts $output_file "   "
close $output_file
