set output_file [open "mem_tester_sim/ddr2_controller_v1_00_a/hdl/vhdl/dcmx3y0_2vp70_sim.vhd" w ]
set line_num 1; puts $output_file "-- simulation model for dcmx3y0_2vp70"
set line_num 2; puts $output_file "library ieee;"
set line_num 3; puts $output_file "use ieee.std_logic_1164.all;"
set line_num 4; puts $output_file "use ieee.std_logic_unsigned.all;"
set line_num 5; puts $output_file "--library synplify; "
set line_num 6; puts $output_file "--use synplify.attributes.all;"
set line_num 7; puts $output_file "--"
set line_num 8; puts $output_file "-- model for simulation only"
set line_num 9; puts $output_file "-- pragma translate_off"
set line_num 10; puts $output_file "library UNISIM;"
set line_num 11; puts $output_file "use UNISIM.VCOMPONENTS.ALL;"
set line_num 12; puts $output_file "-- pragma translate_on"
set line_num 13; puts $output_file ""
set line_num 14; puts $output_file "entity   dcmx3y0_2vp70_sim  is"
set line_num 15; puts $output_file "port("
set line_num 16; puts $output_file "	clock1_in     : in std_logic;   "
set line_num 17; puts $output_file "	clock2_in     : in std_logic;   "
set line_num 18; puts $output_file "	clock1_out    : out std_logic;   "
set line_num 19; puts $output_file "	clock2_out    : out std_logic"
set line_num 20; puts $output_file ");"
set line_num 21; puts $output_file "end   dcmx3y0_2vp70_sim;  "
set line_num 22; puts $output_file ""
set line_num 23; puts $output_file "architecture   arc_dcmx3y0_2vp70_sim of   dcmx3y0_2vp70_sim    is"
set line_num 24; puts $output_file ""
set line_num 25; puts $output_file "component LUT4"
set line_num 26; puts $output_file "   generic("
set line_num 27; puts $output_file "      INIT                           :  bit_vector(15 downto 0) := x\"0000\" );"
set line_num 28; puts $output_file "   port("
set line_num 29; puts $output_file "      O                              :	out   STD_ULOGIC;"
set line_num 30; puts $output_file "      I0                             :	in    STD_ULOGIC;"
set line_num 31; puts $output_file "      I1                             :	in    STD_ULOGIC;"
set line_num 32; puts $output_file "      I2                             :	in    STD_ULOGIC;"
set line_num 33; puts $output_file "      I3                             :	in    STD_ULOGIC"
set line_num 34; puts $output_file "      );"
set line_num 35; puts $output_file "end component;		  "
set line_num 36; puts $output_file ""
set line_num 37; puts $output_file "signal one: std_logic;"
set line_num 38; puts $output_file "signal clkd1inv_1        : std_logic;"
set line_num 39; puts $output_file "signal clkd1buf_1        : std_logic;"
set line_num 40; puts $output_file "signal dualinv_out_sig_1 : std_logic;"
set line_num 41; puts $output_file "signal clkd1buf_2        : std_logic;"
set line_num 42; puts $output_file "signal clkd1inv_2        : std_logic;"
set line_num 43; puts $output_file "signal dualinv_out_sig_2 : std_logic;"
set line_num 44; puts $output_file ""
set line_num 45; puts $output_file "begin"
set line_num 46; puts $output_file ""
set line_num 47; puts $output_file "one <= '1';"
set line_num 48; puts $output_file ""
set line_num 49; puts $output_file "BUF1_1 :  LUT4  generic map (INIT => x\"AAAA\")   "
set line_num 50; puts $output_file "port map   ( "
set line_num 51; puts $output_file "            I0 => clock1_in, "
set line_num 52; puts $output_file "            I1 => one, "
set line_num 53; puts $output_file "            I2 => one, "
set line_num 54; puts $output_file "            I3 => one, "
set line_num 55; puts $output_file "            O  => clkd1buf_1"
set line_num 56; puts $output_file "           );"
set line_num 57; puts $output_file ""
set line_num 58; puts $output_file "INV1_1 :  LUT4  generic map (INIT => x\"00FF\")   "
set line_num 59; puts $output_file "port map   ( "
set line_num 60; puts $output_file "            I0 => one, "
set line_num 61; puts $output_file "            I1 => one, "
set line_num 62; puts $output_file "            I2 => one, "
set line_num 63; puts $output_file "            I3 => clkd1buf_1, "
set line_num 64; puts $output_file "            O  => clkd1inv_1"
set line_num 65; puts $output_file "           );"
set line_num 66; puts $output_file ""
set line_num 67; puts $output_file "INV2_1 :  LUT4  generic map (INIT => x\"3333\")   "
set line_num 68; puts $output_file "port map   ( "
set line_num 69; puts $output_file "            I0 => one, "
set line_num 70; puts $output_file "            I1 => clkd1inv_1, "
set line_num 71; puts $output_file "            I2 => one, "
set line_num 72; puts $output_file "            I3 => one, "
set line_num 73; puts $output_file "            O  => dualinv_out_sig_1"
set line_num 74; puts $output_file "           );"
set line_num 75; puts $output_file ""
set line_num 76; puts $output_file "BUF2_1 :  LUT4  generic map (INIT => x\"CCCC\")   "
set line_num 77; puts $output_file "port map   ( "
set line_num 78; puts $output_file "            I0 => one, "
set line_num 79; puts $output_file "            I1 => dualinv_out_sig_1, "
set line_num 80; puts $output_file "            I2 => one, "
set line_num 81; puts $output_file "            I3 => one, "
set line_num 82; puts $output_file "            O  => clock1_out"
set line_num 83; puts $output_file "           );"
set line_num 84; puts $output_file ""
set line_num 85; puts $output_file "BUF1_2 :  LUT4  generic map (INIT => x\"CCCC\")   "
set line_num 86; puts $output_file "port map   ( "
set line_num 87; puts $output_file "            I0 => one, "
set line_num 88; puts $output_file "            I1 => clock2_in, "
set line_num 89; puts $output_file "            I2 => one, "
set line_num 90; puts $output_file "            I3 => one, "
set line_num 91; puts $output_file "            O  => clkd1buf_2"
set line_num 92; puts $output_file "           );"
set line_num 93; puts $output_file ""
set line_num 94; puts $output_file "INV1_2 :  LUT4  generic map (INIT => x\"00FF\")   "
set line_num 95; puts $output_file "port map   ( "
set line_num 96; puts $output_file "            I0 => one, "
set line_num 97; puts $output_file "            I1 => one, "
set line_num 98; puts $output_file "            I2 => one, "
set line_num 99; puts $output_file "            I3 => clkd1buf_2, "
set line_num 100; puts $output_file "            O  => clkd1inv_2"
set line_num 101; puts $output_file "           );"
set line_num 102; puts $output_file ""
set line_num 103; puts $output_file "INV2_2 :  LUT4  generic map (INIT => x\"3333\")   "
set line_num 104; puts $output_file "port map   ( "
set line_num 105; puts $output_file "            I0 => one, "
set line_num 106; puts $output_file "            I1 => clkd1inv_2, "
set line_num 107; puts $output_file "            I2 => one, "
set line_num 108; puts $output_file "            I3 => one, "
set line_num 109; puts $output_file "            O  => dualinv_out_sig_2"
set line_num 110; puts $output_file "           );"
set line_num 111; puts $output_file ""
set line_num 112; puts $output_file "BUF2_2 :  LUT4  generic map (INIT => x\"CCCC\")   "
set line_num 113; puts $output_file "port map   ( "
set line_num 114; puts $output_file "            I0 => one, "
set line_num 115; puts $output_file "            I1 => dualinv_out_sig_2, "
set line_num 116; puts $output_file "            I2 => one, "
set line_num 117; puts $output_file "            I3 => one, "
set line_num 118; puts $output_file "            O  => clock2_out"
set line_num 119; puts $output_file "           );"
set line_num 120; puts $output_file ""
set line_num 121; puts $output_file "end architecture;"
set line_num 122; puts $output_file ""
set line_num 123; puts $output_file ""
set line_num 124; puts $output_file ""
close $output_file
