set output_file [open "mem_tester_sim/ddr2_controller_v1_00_a/hdl/vhdl/dqs_delay.vhd" w ]
set line_num 1; puts $output_file "--#############################################################################//"
set line_num 2; puts $output_file "--         Internal dqs delay structure for ddr sdram controller               //                          "
set line_num 3; puts $output_file "--#############################################################################//"
set line_num 4; puts $output_file ""
set line_num 5; puts $output_file "library ieee;"
set line_num 6; puts $output_file "use ieee.std_logic_1164.all;"
set line_num 7; puts $output_file "use ieee.std_logic_unsigned.all;"
set line_num 8; puts $output_file ""
set line_num 9; puts $output_file "-- pragma translate_off     "
set line_num 10; puts $output_file "library UNISIM;             "
set line_num 11; puts $output_file "use UNISIM.VCOMPONENTS.ALL; "
set line_num 12; puts $output_file "-- pragma translate_on      "
set line_num 13; puts $output_file ""
set line_num 14; puts $output_file "entity dqs_delay is "
set line_num 15; puts $output_file "              port ("
set line_num 16; puts $output_file "		    clk_in   : in std_logic;"
set line_num 17; puts $output_file "		    sel_in   : in std_logic_vector(4 downto 0);"
set line_num 18; puts $output_file "		    clk_out  : out std_logic"
set line_num 19; puts $output_file "		  );"
set line_num 20; puts $output_file "end dqs_delay;"
set line_num 21; puts $output_file ""
set line_num 22; puts $output_file "architecture arc_dqs_delay of dqs_delay is"
set line_num 23; puts $output_file ""
set line_num 24;  if $synthesize {
set line_num 25; puts $output_file "attribute syn_hier : string;"
set line_num 26; puts $output_file "attribute syn_noprune : boolean;"
set line_num 27; puts $output_file "attribute syn_hier of arc_dqs_delay: architecture is \"hard\";"
set line_num 28; puts $output_file "attribute syn_noprune of arc_dqs_delay: architecture is true;"
set line_num 29; puts $output_file ""
set line_num 30; puts $output_file ""
set line_num 31; puts $output_file "component LUT4"
set line_num 32; puts $output_file "   generic("
set line_num 33; puts $output_file "      INIT                           :  bit_vector(15 downto 0) := x\"0000\" );"
set line_num 34; puts $output_file "   port("
set line_num 35; puts $output_file "      O                              :	out   STD_ULOGIC;"
set line_num 36; puts $output_file "      I0                             :	in    STD_ULOGIC;"
set line_num 37; puts $output_file "      I1                             :	in    STD_ULOGIC;"
set line_num 38; puts $output_file "      I2                             :	in    STD_ULOGIC;"
set line_num 39; puts $output_file "      I3                             :	in    STD_ULOGIC"
set line_num 40; puts $output_file "      );"
set line_num 41; puts $output_file "end component;		  "
set line_num 42; puts $output_file "    "
set line_num 43; puts $output_file "signal delay1     : std_logic;"
set line_num 44; puts $output_file "signal delay2     : std_logic;"
set line_num 45; puts $output_file "signal delay3     : std_logic;"
set line_num 46; puts $output_file "signal delay4     : std_logic;"
set line_num 47; puts $output_file "signal delay5     : std_logic;"
set line_num 48; puts $output_file "signal high       : std_logic;"
set line_num 49; puts $output_file ""
set line_num 50; puts $output_file "begin"
set line_num 51; puts $output_file ""
set line_num 52; puts $output_file "high <= '1';   "
set line_num 53; puts $output_file "   "
set line_num 54; puts $output_file "one :  LUT4  generic map (INIT => x\"f3c0\")  "
set line_num 55; puts $output_file "port map   ( I0 => high, "
set line_num 56; puts $output_file "             I1 => sel_in(4), "
set line_num 57; puts $output_file "             I2 => delay5, "
set line_num 58; puts $output_file "             I3 => clk_in, "
set line_num 59; puts $output_file "             O  => clk_out"
set line_num 60; puts $output_file "            );"
set line_num 61; puts $output_file "  "
set line_num 62; puts $output_file "   "
set line_num 63; puts $output_file "two :  LUT4  generic map (INIT => x\"ee22\")   "
set line_num 64; puts $output_file "port map   ( "
set line_num 65; puts $output_file "            I0 => clk_in, "
set line_num 66; puts $output_file "            I1 => sel_in(2), "
set line_num 67; puts $output_file "            I2 => high, "
set line_num 68; puts $output_file "            I3 => delay3, "
set line_num 69; puts $output_file "            O  => delay4"
set line_num 70; puts $output_file "           );"
set line_num 71; puts $output_file "   "
set line_num 72; puts $output_file "three :  LUT4  generic map (INIT => x\"e2e2\")    "
set line_num 73; puts $output_file "port map     ( "
set line_num 74; puts $output_file "              I0 => clk_in, "
set line_num 75; puts $output_file "              I1 => sel_in(0), "
set line_num 76; puts $output_file "              I2 => delay1, "
set line_num 77; puts $output_file "              I3 => high, "
set line_num 78; puts $output_file "              O  => delay2 "
set line_num 79; puts $output_file "             );"
set line_num 80; puts $output_file "   "
set line_num 81; puts $output_file "four :  LUT4  generic map (INIT => x\"ff00\")    "
set line_num 82; puts $output_file "port map    ( "
set line_num 83; puts $output_file "             I0 => high, "
set line_num 84; puts $output_file "             I1 => high, "
set line_num 85; puts $output_file "             I2 => high, "
set line_num 86; puts $output_file "             I3 => clk_in, "
set line_num 87; puts $output_file "             O  => delay1 "
set line_num 88; puts $output_file "            );"
set line_num 89; puts $output_file "   "
set line_num 90; puts $output_file "five :  LUT4  generic map (INIT => x\"f3c0\")    "
set line_num 91; puts $output_file "port map    ( "
set line_num 92; puts $output_file "             I0 => high, "
set line_num 93; puts $output_file "             I1 => sel_in(3), "
set line_num 94; puts $output_file "             I2 => delay4, "
set line_num 95; puts $output_file "             I3 => clk_in, "
set line_num 96; puts $output_file "             O  => delay5 "
set line_num 97; puts $output_file "            );"
set line_num 98; puts $output_file "   "
set line_num 99; puts $output_file "six :  LUT4  generic map (INIT => x\"e2e2\")    "
set line_num 100; puts $output_file "port map  ( "
set line_num 101; puts $output_file "            I0 => clk_in, "
set line_num 102; puts $output_file "            I1 => sel_in(1), "
set line_num 103; puts $output_file "            I2 => delay2, "
set line_num 104; puts $output_file "            I3 => high, "
set line_num 105; puts $output_file "            O  => delay3 "
set line_num 106; puts $output_file "           );"
set line_num 107; puts $output_file "   "
set line_num 108;  } else {
set line_num 109; puts $output_file "begin"
set line_num 110; puts $output_file ""
set line_num 111; puts $output_file "	clk_out <= clk_in after 1250 ps;"
set line_num 112;  }
set line_num 113; puts $output_file ""
set line_num 114; puts $output_file "end arc_dqs_delay;"
close $output_file
