set output_file [open "mem_tester_sim/ddr2_controller_v1_00_a/hdl/vhdl/infrastructure_top.vhd" w ]
set line_num 1; puts $output_file "--******************************************************************************"
set line_num 2; puts $output_file "--"
set line_num 3; puts $output_file "--  Xilinx, Inc. 2002                 www.xilinx.com"
set line_num 4; puts $output_file "--"
set line_num 5; puts $output_file "--  XAPP 253 - Synthesizable DDR SDRAM Controller"
set line_num 6; puts $output_file "--"
set line_num 7; puts $output_file "--*******************************************************************************"
set line_num 8; puts $output_file "--"
set line_num 9; puts $output_file "--  File name :       infrastructure.vhd"
set line_num 10; puts $output_file "--"
set line_num 11; puts $output_file "--  Description :     "
set line_num 12; puts $output_file "--                    Main fucntions of this module"
set line_num 13; puts $output_file "--                       - generation of FPGA clocks."
set line_num 14; puts $output_file "--                       - generation of reset signals"
set line_num 15; puts $output_file "--                       - implements calibration mechanism"
set line_num 16; puts $output_file "--"
set line_num 17; puts $output_file "--  Date - revision : 05/01/2002"
set line_num 18; puts $output_file "--"
set line_num 19; puts $output_file "--  Author :          Lakshmi Gopalakrishnan ( Modified by Sailja) "
set line_num 20; puts $output_file "--"
set line_num 21; puts $output_file "--  Contact : e-mail  hotline@xilinx.com"
set line_num 22; puts $output_file "--            phone   + 1 800 255 7778 "
set line_num 23; puts $output_file "--"
set line_num 24; puts $output_file "--  Disclaimer: LIMITED WARRANTY AND DISCLAMER. These designs are "
set line_num 25; puts $output_file "--              provided to you \"as is\". Xilinx and its licensors make and you "
set line_num 26; puts $output_file "--              receive no warranties or conditions, express, implied, "
set line_num 27; puts $output_file "--              statutory or otherwise, and Xilinx specifically disclaims any "
set line_num 28; puts $output_file "--              implied warranties of merchantability, non-infringement, or "
set line_num 29; puts $output_file "--              fitness for a particular purpose. Xilinx does not warrant that "
set line_num 30; puts $output_file "--              the functions contained in these designs will meet your "
set line_num 31; puts $output_file "--              requirements, or that the operation of these designs will be "
set line_num 32; puts $output_file "--              uninterrupted or error free, or that defects in the Designs "
set line_num 33; puts $output_file "--              will be corrected. Furthermore, Xilinx does not warrant or "
set line_num 34; puts $output_file "--              make any representations regarding use or the results of the "
set line_num 35; puts $output_file "--              use of the designs in terms of correctness, accuracy, "
set line_num 36; puts $output_file "--              reliability, or otherwise. "
set line_num 37; puts $output_file "--"
set line_num 38; puts $output_file "--              LIMITATION OF LIABILITY. In no event will Xilinx or its "
set line_num 39; puts $output_file "--              licensors be liable for any loss of data, lost profits, cost "
set line_num 40; puts $output_file "--              or procurement of substitute goods or services, or for any "
set line_num 41; puts $output_file "--              special, incidental, consequential, or indirect damages "
set line_num 42; puts $output_file "--              arising from the use or operation of the designs or "
set line_num 43; puts $output_file "--              accompanying documentation, however caused and on any theory "
set line_num 44; puts $output_file "--              of liability. This limitation will apply even if Xilinx "
set line_num 45; puts $output_file "--              has been advised of the possibility of such damage. This "
set line_num 46; puts $output_file "--              limitation shall apply not-withstanding the failure of the "
set line_num 47; puts $output_file "--              essential purpose of any limited remedies herein. "
set line_num 48; puts $output_file "--"
set line_num 49; puts $output_file "--  Copyright © 2002 Xilinx, Inc."
set line_num 50; puts $output_file "--  All rights reserved "
set line_num 51; puts $output_file "-- "
set line_num 52; puts $output_file "--*****************************************************************************"
set line_num 53; puts $output_file ""
set line_num 54; puts $output_file ""
set line_num 55; puts $output_file ""
set line_num 56; puts $output_file "library IEEE;"
set line_num 57; puts $output_file "use IEEE.std_logic_1164.all;"
set line_num 58; puts $output_file "use ieee.std_logic_unsigned.all;"
set line_num 59; puts $output_file "--library synplify; "
set line_num 60; puts $output_file "--use synplify.attributes.all;"
set line_num 61; puts $output_file "--"
set line_num 62; puts $output_file "-- pragma translate_off"
set line_num 63; puts $output_file "library UNISIM;"
set line_num 64; puts $output_file "use UNISIM.VCOMPONENTS.ALL;"
set line_num 65; puts $output_file "-- pragma translate_on"
set line_num 66; puts $output_file "--"
set line_num 67; puts $output_file ""
set line_num 68; puts $output_file "entity infrastructure_top is"
set line_num 69; puts $output_file "  port("
set line_num 70; puts $output_file "       reset_in         : in std_logic;"
set line_num 71; puts $output_file "       sys_clk_ibuf     : in std_logic;"
set line_num 72; puts $output_file "       delay_sel_val1_val   : out std_logic_vector(4 downto 0);"
set line_num 73; puts $output_file "       sys_rst_val          : out std_logic;"
set line_num 74; puts $output_file "       sys_rst90_val        : out std_logic;"
set line_num 75; puts $output_file "       sys_rst180_val       : out std_logic;"
set line_num 76; puts $output_file "       sys_rst270_val       : out std_logic;"
set line_num 77; puts $output_file "       clk_int_val          : out std_logic;"
set line_num 78; puts $output_file "       clk90_int_val        : out std_logic"
set line_num 79; puts $output_file "  );"
set line_num 80; puts $output_file "  "
set line_num 81; puts $output_file "end   infrastructure_top;"
set line_num 82; puts $output_file ""
set line_num 83; puts $output_file "architecture arc_infrastructure_top  of infrastructure_top  is"
set line_num 84; puts $output_file ""
set line_num 85; puts $output_file "---- Component declarations -----"
set line_num 86; puts $output_file ""
set line_num 87; puts $output_file "component clk_dcm "
set line_num 88; puts $output_file "port("
set line_num 89; puts $output_file "     input_clk   : in std_logic;"
set line_num 90; puts $output_file "     rst         : in std_logic;"
set line_num 91; puts $output_file "     clk         : out std_logic;"
set line_num 92; puts $output_file "     clk90       : out std_logic;"
set line_num 93; puts $output_file "     dcm_lock    : out std_logic"
set line_num 94; puts $output_file "     );"
set line_num 95; puts $output_file "end component;"
set line_num 96; puts $output_file ""
set line_num 97; puts $output_file "component cal_top                                                 "
set line_num 98; puts $output_file "port             (                                                "
set line_num 99; puts $output_file "	          clk         : in std_logic;                     "
set line_num 100; puts $output_file "	          clk0        : in std_logic;                     "
set line_num 101; puts $output_file "	          clk0dcmlock : in std_logic;                     "
set line_num 102; puts $output_file "	          reset       : in std_logic;                     "
set line_num 103; puts $output_file "	          okToSelTap  : in std_logic;"
set line_num 104; puts $output_file "	          tapForDqs   : out std_logic_vector(4 downto 0)"
set line_num 105; puts $output_file "                 );                                               "
set line_num 106; puts $output_file "end component;"
set line_num 107; puts $output_file ""
set line_num 108; puts $output_file "---- Signal declarations used on the diagram ----"
set line_num 109; puts $output_file ""
set line_num 110; puts $output_file "signal user_rst                : std_logic := '1';"
set line_num 111; puts $output_file "signal user_rst_reg0           : std_logic := '1';"
set line_num 112; puts $output_file "signal user_rst_reg90          : std_logic := '1';"
set line_num 113; puts $output_file "signal user_rst_reg180         : std_logic := '1';"
set line_num 114; puts $output_file "signal user_rst_reg270         : std_logic := '1';"
set line_num 115; puts $output_file "signal user_rst_reg0_resamp    : std_logic := '1';"
set line_num 116; puts $output_file "signal user_rst_reg90_resamp   : std_logic := '1';"
set line_num 117; puts $output_file "signal user_rst_reg180_resamp  : std_logic := '1';"
set line_num 118; puts $output_file "signal user_rst_reg270_resamp  : std_logic := '1';"
set line_num 119; puts $output_file "signal clk_int                 : std_logic;"
set line_num 120; puts $output_file "signal clk90_int               : std_logic;"
set line_num 121; puts $output_file "signal dcm_lock                : std_logic;"
set line_num 122; puts $output_file "signal sys_rst_o               : std_logic := '1';"
set line_num 123; puts $output_file "signal sys_rst_1               : std_logic := '1';"
set line_num 124; puts $output_file "signal sys_rst                 : std_logic := '1';"
set line_num 125; puts $output_file "signal sys_rst90_o             : std_logic := '1';"
set line_num 126; puts $output_file "signal sys_rst90_1             : std_logic := '1';"
set line_num 127; puts $output_file "signal sys_rst90               : std_logic := '1';"
set line_num 128; puts $output_file "signal sys_rst180_o            : std_logic := '1';"
set line_num 129; puts $output_file "signal sys_rst180_1            : std_logic := '1';"
set line_num 130; puts $output_file "signal sys_rst180              : std_logic := '1';"
set line_num 131; puts $output_file "signal sys_rst270_o            : std_logic := '1';"
set line_num 132; puts $output_file "signal sys_rst270_1            : std_logic := '1';"
set line_num 133; puts $output_file "signal sys_rst270              : std_logic := '1';"
set line_num 134; puts $output_file "signal delay_sel_val           : std_logic_vector(4 downto 0);"
set line_num 135; puts $output_file "signal vcc                     : std_logic;"
set line_num 136; puts $output_file ""
set line_num 137; puts $output_file "signal clk_int_val1            : std_logic;"
set line_num 138; puts $output_file "signal clk_int_val2            : std_logic;"
set line_num 139; puts $output_file "signal clk90_int_val1          : std_logic;"
set line_num 140; puts $output_file "signal clk90_int_val2          : std_logic;"
set line_num 141; puts $output_file ""
set line_num 142; puts $output_file "signal not_reset_in            : std_logic := '0';"
set line_num 143; puts $output_file "signal not_reset_in_delay      : std_logic := '0';"
set line_num 144; puts $output_file ""
set line_num 145; puts $output_file "begin"
set line_num 146; puts $output_file ""
set line_num 147; puts $output_file "clk_int_val <= clk_int;"
set line_num 148; puts $output_file "clk90_int_val <= clk90_int;"
set line_num 149; puts $output_file "sys_rst_val <= sys_rst;"
set line_num 150; puts $output_file "sys_rst90_val <= sys_rst90;"
set line_num 151; puts $output_file "sys_rst180_val <= sys_rst180;"
set line_num 152; puts $output_file "sys_rst270_val <= sys_rst270;"
set line_num 153; puts $output_file "delay_sel_val1_val <= delay_sel_val;"
set line_num 154; puts $output_file "not_reset_in   <= not reset_in;"
set line_num 155; puts $output_file "-----   To remove delta delays in the clock signals observed during simulation ,Following signals are used "
set line_num 156; puts $output_file ""
set line_num 157; puts $output_file "clk_int_val1 <= clk_int;"
set line_num 158; puts $output_file "clk90_int_val1 <= clk90_int;"
set line_num 159; puts $output_file "clk_int_val2 <= clk_int_val1;"
set line_num 160; puts $output_file "clk90_int_val2 <= clk90_int_val1;"
set line_num 161; puts $output_file ""
set line_num 162; puts $output_file "vcc       <= '1';"
set line_num 163; puts $output_file ""
set line_num 164; puts $output_file "-- register the reset a first time"
set line_num 165; puts $output_file "process(clk_int_val2)"
set line_num 166; puts $output_file "begin"
set line_num 167; puts $output_file " if clk_int_val2'event and clk_int_val2 = '1' then"
set line_num 168; puts $output_file "	user_rst           <= reset_in or (not dcm_lock);"
set line_num 169; puts $output_file "	not_reset_in_delay <= not_reset_in;"
set line_num 170; puts $output_file " end if;"
set line_num 171; puts $output_file "end process;"
set line_num 172; puts $output_file ""
set line_num 173; puts $output_file "-- register the reset a second time with a different register for each clock"
set line_num 174; puts $output_file "process(clk_int_val2)"
set line_num 175; puts $output_file "begin"
set line_num 176; puts $output_file " if clk_int_val2'event and clk_int_val2 = '1' then"
set line_num 177; puts $output_file "  user_rst_reg0    <= user_rst;                                        "
set line_num 178; puts $output_file "  user_rst_reg90   <= user_rst;                                        "
set line_num 179; puts $output_file "  user_rst_reg180  <= user_rst;                                        "
set line_num 180; puts $output_file "  user_rst_reg270  <= user_rst;                                        "
set line_num 181; puts $output_file " end if;"
set line_num 182; puts $output_file ""
set line_num 183; puts $output_file "end process;"
set line_num 184; puts $output_file ""
set line_num 185; puts $output_file "-- resample the reset on each clock"
set line_num 186; puts $output_file "process(clk_int_val2)"
set line_num 187; puts $output_file "begin"
set line_num 188; puts $output_file " if clk_int_val2'event and clk_int_val2 = '1' then"
set line_num 189; puts $output_file "  if user_rst_reg0 = '1' then"
set line_num 190; puts $output_file "      sys_rst_o <= '1';"
set line_num 191; puts $output_file "      sys_rst_1 <= '1';"
set line_num 192; puts $output_file "      sys_rst   <= '1';"
set line_num 193; puts $output_file "  else"
set line_num 194; puts $output_file "      sys_rst_o <= '0';"
set line_num 195; puts $output_file "      sys_rst_1 <= sys_rst_o;"
set line_num 196; puts $output_file "      sys_rst   <= sys_rst_1;"
set line_num 197; puts $output_file "  end if;"
set line_num 198; puts $output_file " end if;"
set line_num 199; puts $output_file "end process;"
set line_num 200; puts $output_file ""
set line_num 201; puts $output_file "process(clk90_int_val2)"
set line_num 202; puts $output_file "begin"
set line_num 203; puts $output_file " if clk90_int_val2'event and clk90_int_val2 = '1' then"
set line_num 204; puts $output_file "  if user_rst_reg90_resamp = '1' then"
set line_num 205; puts $output_file "      sys_rst90_o <= '1';"
set line_num 206; puts $output_file "      sys_rst90_1 <= '1';"
set line_num 207; puts $output_file "      sys_rst90   <= '1';"
set line_num 208; puts $output_file "  else"
set line_num 209; puts $output_file "      sys_rst90_o <= '0';"
set line_num 210; puts $output_file "      sys_rst90_1 <= sys_rst90_o;"
set line_num 211; puts $output_file "      sys_rst90   <= sys_rst90_1;"
set line_num 212; puts $output_file "  end if;"
set line_num 213; puts $output_file "  user_rst_reg90_resamp <= user_rst_reg90;"
set line_num 214; puts $output_file " end if;"
set line_num 215; puts $output_file "end process;"
set line_num 216; puts $output_file ""
set line_num 217; puts $output_file "process(clk_int_val2)"
set line_num 218; puts $output_file "begin"
set line_num 219; puts $output_file " if clk_int_val2'event and clk_int_val2 = '0' then"
set line_num 220; puts $output_file "  if user_rst_reg180_resamp = '1' then"
set line_num 221; puts $output_file "      sys_rst180_o <= '1';"
set line_num 222; puts $output_file "      sys_rst180_1 <= '1';"
set line_num 223; puts $output_file "      sys_rst180   <= '1';"
set line_num 224; puts $output_file "  else"
set line_num 225; puts $output_file "      sys_rst180_o <= '0';"
set line_num 226; puts $output_file "      sys_rst180_1 <= sys_rst180_o;"
set line_num 227; puts $output_file "      sys_rst180   <= sys_rst180_1;"
set line_num 228; puts $output_file "  end if;"
set line_num 229; puts $output_file "  user_rst_reg180_resamp <= user_rst_reg180;"
set line_num 230; puts $output_file " end if;"
set line_num 231; puts $output_file "end process;"
set line_num 232; puts $output_file ""
set line_num 233; puts $output_file "process(clk90_int_val2)"
set line_num 234; puts $output_file "begin"
set line_num 235; puts $output_file " if clk90_int_val2'event and clk90_int_val2 = '0' then"
set line_num 236; puts $output_file "  if user_rst_reg270_resamp = '1' then"
set line_num 237; puts $output_file "      sys_rst270_o <= '1';"
set line_num 238; puts $output_file "      sys_rst270_1 <= '1';"
set line_num 239; puts $output_file "      sys_rst270   <= '1';"
set line_num 240; puts $output_file "  else"
set line_num 241; puts $output_file "      sys_rst270_o <= '0';"
set line_num 242; puts $output_file "      sys_rst270_1 <= sys_rst270_o;"
set line_num 243; puts $output_file "      sys_rst270   <= sys_rst270_1;"
set line_num 244; puts $output_file "  end if;"
set line_num 245; puts $output_file "  user_rst_reg270_resamp <= user_rst_reg270;"
set line_num 246; puts $output_file " end if;"
set line_num 247; puts $output_file "end process;"
set line_num 248; puts $output_file ""
set line_num 249; puts $output_file "----  Component instantiations  ----"
set line_num 250; puts $output_file ""
set line_num 251; puts $output_file "                                   "
set line_num 252; puts $output_file "clk_dcm0 : clk_dcm port map ("
set line_num 253; puts $output_file "                             input_clk   => sys_clk_ibuf,"
set line_num 254; puts $output_file "                             rst         => reset_in,                            "
set line_num 255; puts $output_file "                             clk         => clk_int,"
set line_num 256; puts $output_file "                             clk90       => clk90_int,"
set line_num 257; puts $output_file "                             dcm_lock    => dcm_lock"
set line_num 258; puts $output_file "                            ); "
set line_num 259; puts $output_file "                            "
set line_num 260; puts $output_file "cal_top0 : cal_top port map (                                                 "
set line_num 261; puts $output_file "                             clk         => sys_clk_ibuf,  "
set line_num 262; puts $output_file "                             clk0        => clk_int_val2,                "
set line_num 263; puts $output_file "                             clk0dcmlock => dcm_lock,  "
set line_num 264; puts $output_file "                             reset       => not_reset_in_delay,      "
set line_num 265; puts $output_file "                             okToSelTap  => vcc,"
set line_num 266; puts $output_file "                             tapForDqs   => delay_sel_val"
set line_num 267; puts $output_file "                             );       "
set line_num 268; puts $output_file "                                          "
set line_num 269; puts $output_file ""
set line_num 270; puts $output_file "end arc_infrastructure_top ;"
set line_num 271; puts $output_file ""
set line_num 272; puts $output_file ""
close $output_file
