set output_file [open "mem_tester_sim/ddr2_controller_v1_00_a/hdl/vhdl/parameter.vhd" w ]
set line_num 1; puts $output_file "library ieee;"
set line_num 2; puts $output_file "use ieee.std_logic_1164.all;"
set line_num 3; puts $output_file "--library synplify;"
set line_num 4; puts $output_file "--use synplify.attributes.all;"
set line_num 5; puts $output_file "-- pragma translate_off"
set line_num 6; puts $output_file "library UNISIM; "
set line_num 7; puts $output_file " use UNISIM.VCOMPONENTS.ALL;"
set line_num 8; puts $output_file " -- pragma translate_on"
set line_num 9; puts $output_file "package parameter is"
set line_num 10; puts $output_file "  constant row_address_p   : INTEGER   := 14;"
set line_num 11; puts $output_file "  constant column_address_p: INTEGER   := 10;"
set line_num 12; puts $output_file "  constant bank_address_p  : INTEGER   :=  2;"
set line_num 13; puts $output_file "end parameter;"
set line_num 14; puts $output_file ""
close $output_file
