webtalk_init -webtalk_dir C:/XilinxProjects/ip_repo/tp3_data_rx_1.0/tp3_data_rx_sim/tp3_data_rx_sim.sim/sim_1/behav/xsim/xsim.dir/data_rx_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Nov 27 18:00:55 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "668b0e7b-1639-483c-b430-47469e60b02d" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "95fedf9cebdd437c807c06f999637897" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "84" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1992 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1540462 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "29.26_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "18372_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2242334702 -regid "" -xml C:/XilinxProjects/ip_repo/tp3_data_rx_1.0/tp3_data_rx_sim/tp3_data_rx_sim.sim/sim_1/behav/xsim/xsim.dir/data_rx_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/XilinxProjects/ip_repo/tp3_data_rx_1.0/tp3_data_rx_sim/tp3_data_rx_sim.sim/sim_1/behav/xsim/xsim.dir/data_rx_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/XilinxProjects/ip_repo/tp3_data_rx_1.0/tp3_data_rx_sim/tp3_data_rx_sim.sim/sim_1/behav/xsim/xsim.dir/data_rx_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
