set_property IOSTANDARD LVDS [get_ports AUX_CLK_P]
set_property IOSTANDARD LVDS [get_ports AUX_CLK_N]

set_property IOSTANDARD LVDS [get_ports AUX_SYNCI_P]
set_property IOSTANDARD LVDS [get_ports AUX_SYNCI_N]
set_property IOSTANDARD LVDS [get_ports AUX_SYNCO_P]
set_property IOSTANDARD LVDS [get_ports AUX_SYNCO_N]
set_property PACKAGE_PIN BC27 [get_ports {FLASH_DQ[0]}]
set_property PACKAGE_PIN BD27 [get_ports {FLASH_DQ[1]}]
set_property PACKAGE_PIN BD29 [get_ports {FLASH_DQ[2]}]
set_property PACKAGE_PIN BD30 [get_ports {FLASH_DQ[3]}]
set_property PACKAGE_PIN BB28 [get_ports EMCCLK]
set_property PACKAGE_PIN BB30 [get_ports {FLASH_DQ[4]}]
set_property PACKAGE_PIN BC30 [get_ports {FLASH_DQ[5]}]
set_property PACKAGE_PIN BC28 [get_ports {FLASH_DQ[6]}]
set_property PACKAGE_PIN BC29 [get_ports {FLASH_DQ[7]}]
set_property PACKAGE_PIN BA29 [get_ports FLASH_CS_N]
set_property PACKAGE_PIN BA30 [get_ports {FLASH_DQ[8]}]
set_property PACKAGE_PIN AW29 [get_ports {FLASH_DQ[9]}]
set_property PACKAGE_PIN AY29 [get_ports {FLASH_DQ[10]}]
set_property PACKAGE_PIN AW27 [get_ports {FLASH_DQ[11]}]
set_property PACKAGE_PIN AY27 [get_ports {FLASH_DQ[12]}]
set_property PACKAGE_PIN BA31 [get_ports {FLASH_DQ[13]}]
set_property PACKAGE_PIN AY28 [get_ports {FLASH_DQ[14]}]
set_property PACKAGE_PIN BA28 [get_ports {FLASH_DQ[15]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_DQ[15]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_DQ[14]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_DQ[13]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_DQ[12]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_DQ[11]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_DQ[10]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_DQ[9]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_DQ[8]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_DQ[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_DQ[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_DQ[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_DQ[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_DQ[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_DQ[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_DQ[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_DQ[0]}]
set_property PACKAGE_PIN AT29 [get_ports {FLASH_A[15]}]
set_property PACKAGE_PIN AP29 [get_ports {FLASH_A[14]}]
set_property PACKAGE_PIN AP30 [get_ports {FLASH_A[13]}]
set_property PACKAGE_PIN AR28 [get_ports {FLASH_A[12]}]
set_property PACKAGE_PIN AR29 [get_ports {FLASH_A[11]}]
set_property PACKAGE_PIN AN28 [get_ports {FLASH_A[10]}]
set_property PACKAGE_PIN AN29 [get_ports {FLASH_A[9]}]
set_property PACKAGE_PIN AM30 [get_ports {FLASH_A[8]}]
set_property PACKAGE_PIN AN30 [get_ports {FLASH_A[7]}]
set_property PACKAGE_PIN AK28 [get_ports {FLASH_A[6]}]
set_property PACKAGE_PIN AM27 [get_ports {FLASH_A[5]}]
set_property PACKAGE_PIN AM28 [get_ports {FLASH_A[4]}]
set_property PACKAGE_PIN AJ29 [get_ports {FLASH_A[3]}]
set_property PACKAGE_PIN AK29 [get_ports {FLASH_A[2]}]
set_property PACKAGE_PIN AL28 [get_ports {FLASH_A[1]}]
set_property PACKAGE_PIN AL29 [get_ports {FLASH_A[0]}]
set_property PACKAGE_PIN AT26 [get_ports {FLASH_A[28]}]
set_property PACKAGE_PIN AU27 [get_ports {FLASH_A[27]}]
set_property PACKAGE_PIN AP24 [get_ports {FLASH_A[26]}]
set_property PACKAGE_PIN AP25 [get_ports {FLASH_A[25]}]
set_property PACKAGE_PIN AN25 [get_ports {FLASH_A[24]}]
set_property PACKAGE_PIN AP26 [get_ports {FLASH_A[23]}]
set_property PACKAGE_PIN AL23 [get_ports {FLASH_A[22]}]
set_property PACKAGE_PIN AM23 [get_ports {FLASH_A[21]}]
set_property PACKAGE_PIN AM25 [get_ports {FLASH_A[20]}]
set_property PACKAGE_PIN AM26 [get_ports {FLASH_A[19]}]
set_property PACKAGE_PIN AK24 [get_ports {FLASH_A[18]}]
set_property PACKAGE_PIN AK26 [get_ports {FLASH_A[17]}]
set_property PACKAGE_PIN AL26 [get_ports {FLASH_A[16]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_A[28]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_A[27]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_A[26]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_A[25]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_A[24]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_A[23]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_A[22]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_A[21]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_A[20]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_A[19]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_A[18]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_A[17]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_A[16]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_A[15]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_A[14]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_A[13]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_A[12]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_A[11]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_A[10]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_A[9]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_A[8]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_A[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_A[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_A[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_A[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_A[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_A[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_A[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_A[0]}]
set_property PACKAGE_PIN AN24 [get_ports FLASH_ADV_N]
set_property PACKAGE_PIN AL24 [get_ports FLASH_OE_N]
set_property PACKAGE_PIN AL25 [get_ports FLASH_WE_N]
set_property PACKAGE_PIN AJ25 [get_ports FLASH_RS1]
set_property PACKAGE_PIN AJ26 [get_ports FLASH_RS0]
set_property PACKAGE_PIN BD26 [get_ports FLASH_WAIT]
set_property IOSTANDARD LVCMOS18 [get_ports FLASH_ADV_N]
set_property IOSTANDARD LVCMOS18 [get_ports FLASH_CS_N]
set_property IOSTANDARD LVCMOS18 [get_ports FLASH_OE_N]
set_property IOSTANDARD LVCMOS18 [get_ports FLASH_RS0]
set_property IOSTANDARD LVCMOS18 [get_ports FLASH_RS1]
set_property IOSTANDARD LVCMOS18 [get_ports FLASH_WAIT]
set_property IOSTANDARD LVCMOS18 [get_ports FLASH_WE_N]
set_property IOSTANDARD LVCMOS18 [get_ports EMCCLK]

set_property PACKAGE_PIN BB26 [get_ports CONFIG_IO_0]
set_property PACKAGE_PIN BB25 [get_ports CONFIG_IO_1]
set_property PACKAGE_PIN BC25 [get_ports CONFIG_IO_2]
set_property PACKAGE_PIN BD25 [get_ports CONFIG_IO_3]
set_property PACKAGE_PIN AY24 [get_ports CONFIG_IO_4]
set_property PACKAGE_PIN BA24 [get_ports CONFIG_IO_5]
set_property PACKAGE_PIN BC24 [get_ports CONFIG_IO_6]
set_property PACKAGE_PIN BD24 [get_ports CONFIG_IO_7]
set_property IOSTANDARD LVCMOS18 [get_ports CONFIG_IO_0]
set_property IOSTANDARD LVCMOS18 [get_ports CONFIG_IO_1]
set_property IOSTANDARD LVCMOS18 [get_ports CONFIG_IO_2]
set_property IOSTANDARD LVCMOS18 [get_ports CONFIG_IO_3]
set_property IOSTANDARD LVCMOS18 [get_ports CONFIG_IO_4]
set_property IOSTANDARD LVCMOS18 [get_ports CONFIG_IO_5]
set_property IOSTANDARD LVCMOS18 [get_ports CONFIG_IO_6]
set_property IOSTANDARD LVCMOS18 [get_ports CONFIG_IO_7]
set_property IOSTANDARD LVCMOS18 [get_ports CPU_PWR_BTN_N]
set_property PACKAGE_PIN A18 [get_ports CPU_PWR_OK]
set_property IOSTANDARD LVCMOS18 [get_ports CPU_PWR_OK]
set_property PACKAGE_PIN A19 [get_ports CPU_SUS_S3_N]
set_property PACKAGE_PIN B16 [get_ports CPU_SUS_S4_N]
set_property PACKAGE_PIN B17 [get_ports CPU_SUS_S5_N]
set_property PACKAGE_PIN B18 [get_ports CPU_SUS_STAT_N]
set_property IOSTANDARD LVCMOS18 [get_ports CPU_SUS_S3_N]
set_property IOSTANDARD LVCMOS18 [get_ports CPU_SUS_S4_N]
set_property IOSTANDARD LVCMOS18 [get_ports CPU_SUS_S5_N]
set_property IOSTANDARD LVCMOS18 [get_ports CPU_SUS_STAT_N]
set_property IOSTANDARD LVCMOS18 [get_ports CPU_SYS_RESET_N]
set_property PACKAGE_PIN C18 [get_ports PCIE_RST_N]
set_property IOSTANDARD LVCMOS18 [get_ports PCIE_RST_N]
set_property PACKAGE_PIN BA26 [get_ports SPARTAN_CLK]
set_property IOSTANDARD LVCMOS18 [get_ports SPARTAN_CLK]
set_property PACKAGE_PIN BD22 [get_ports FAN_CONT_ALERT_N]
set_property PACKAGE_PIN BC22 [get_ports FAN_CONT_FAULT_N]
set_property PACKAGE_PIN BB22 [get_ports FAN_CONT_RST_N]
set_property IOSTANDARD LVCMOS18 [get_ports FAN_CONT_FAULT_N]
set_property IOSTANDARD LVCMOS18 [get_ports FAN_CONT_ALERT_N]
set_property IOSTANDARD LVCMOS18 [get_ports FAN_CONT_RST_N]
set_property PACKAGE_PIN BC34 [get_ports MEZZANINE_1_ONE_WIRE]
set_property PACKAGE_PIN BD34 [get_ports MEZZANINE_1_ONE_WIRE_STRONG_PULLUP_EN_N]
set_property IOSTANDARD LVCMOS18 [get_ports MEZZANINE_1_CLK_SEL]
set_property IOSTANDARD LVCMOS18 [get_ports MEZZANINE_1_ENABLE_N]
set_property IOSTANDARD LVCMOS18 [get_ports MEZZANINE_1_FAULT_N]
set_property IOSTANDARD LVCMOS18 [get_ports MEZZANINE_1_ONE_WIRE]
set_property IOSTANDARD LVCMOS18 [get_ports MEZZANINE_1_ONE_WIRE_STRONG_PULLUP_EN_N]
set_property IOSTANDARD LVCMOS18 [get_ports MEZZANINE_1_PRESENT_N]
set_property IOSTANDARD LVCMOS18 [get_ports MEZZANINE_1_RESET]
set_property DRIVE 12 [get_ports CPU_PWR_BTN_N]
set_property PACKAGE_PIN A33 [get_ports MEZZANINE_0_CLK_SEL]
set_property PACKAGE_PIN B33 [get_ports MEZZANINE_0_ENABLE_N]
set_property PACKAGE_PIN C33 [get_ports MEZZANINE_0_RESET]
set_property PACKAGE_PIN B32 [get_ports MEZZANINE_0_ONE_WIRE]
set_property PACKAGE_PIN C32 [get_ports MEZZANINE_0_ONE_WIRE_STRONG_PULLUP_EN_N]
set_property IOSTANDARD LVCMOS18 [get_ports MEZZANINE_0_CLK_SEL]
set_property IOSTANDARD LVCMOS18 [get_ports MEZZANINE_0_ENABLE_N]
set_property IOSTANDARD LVCMOS18 [get_ports MEZZANINE_0_ONE_WIRE]
set_property IOSTANDARD LVCMOS18 [get_ports MEZZANINE_0_ONE_WIRE_STRONG_PULLUP_EN_N]
set_property IOSTANDARD LVCMOS18 [get_ports MEZZANINE_0_RESET]
set_property PACKAGE_PIN BB10 [get_ports MEZZANINE_2_ONE_WIRE]
set_property PACKAGE_PIN BA10 [get_ports MEZZANINE_2_ONE_WIRE_STRONG_PULLUP_EN_N]
set_property IOSTANDARD LVCMOS18 [get_ports MEZZANINE_2_CLK_SEL]
set_property IOSTANDARD LVCMOS18 [get_ports MEZZANINE_2_ENABLE_N]
set_property IOSTANDARD LVCMOS18 [get_ports MEZZANINE_2_ONE_WIRE]
set_property IOSTANDARD LVCMOS18 [get_ports MEZZANINE_2_ONE_WIRE_STRONG_PULLUP_EN_N]
set_property IOSTANDARD LVCMOS18 [get_ports MEZZANINE_2_RESET]
set_property PACKAGE_PIN B12 [get_ports MEZZANINE_3_CLK_SEL]
set_property PACKAGE_PIN C12 [get_ports MEZZANINE_3_ENABLE_N]
set_property PACKAGE_PIN D32 [get_ports MEZZANINE_0_PRESENT_N]
set_property IOSTANDARD LVCMOS18 [get_ports MEZZANINE_0_FAULT_N]
set_property IOSTANDARD LVCMOS18 [get_ports MEZZANINE_0_PRESENT_N]
set_property PACKAGE_PIN BA11 [get_ports MEZZANINE_2_PRESENT_N]
set_property IOSTANDARD LVCMOS18 [get_ports MEZZANINE_2_FAULT_N]
set_property IOSTANDARD LVCMOS18 [get_ports MEZZANINE_2_PRESENT_N]
set_property PACKAGE_PIN A13 [get_ports MEZZANINE_3_ONE_WIRE]
set_property PACKAGE_PIN B13 [get_ports MEZZANINE_3_ONE_WIRE_STRONG_PULLUP_EN_N]
set_property PACKAGE_PIN C13 [get_ports MEZZANINE_3_PRESENT_N]
set_property PACKAGE_PIN E12 [get_ports MEZZANINE_3_RESET]
set_property IOSTANDARD LVCMOS18 [get_ports MEZZANINE_3_CLK_SEL]
set_property IOSTANDARD LVCMOS18 [get_ports MEZZANINE_3_ENABLE_N]
set_property IOSTANDARD LVCMOS18 [get_ports MEZZANINE_3_FAULT_N]
set_property IOSTANDARD LVCMOS18 [get_ports MEZZANINE_3_ONE_WIRE]
set_property IOSTANDARD LVCMOS18 [get_ports MEZZANINE_3_PRESENT_N]
set_property IOSTANDARD LVCMOS18 [get_ports MEZZANINE_3_RESET]
set_property IOSTANDARD LVCMOS18 [get_ports MEZZANINE_3_ONE_WIRE_STRONG_PULLUP_EN_N]
set_property IOSTANDARD LVCMOS18 [get_ports MONITOR_ALERT_N]
set_property PACKAGE_PIN A29 [get_ports {FPGA_GPIO[0]}]
set_property PACKAGE_PIN C29 [get_ports {FPGA_GPIO[1]}]
set_property PACKAGE_PIN D29 [get_ports {FPGA_GPIO[2]}]
set_property PACKAGE_PIN E29 [get_ports {FPGA_GPIO[3]}]
set_property PACKAGE_PIN A28 [get_ports {FPGA_GPIO[4]}]
set_property PACKAGE_PIN B28 [get_ports {FPGA_GPIO[5]}]
set_property PACKAGE_PIN C28 [get_ports {FPGA_GPIO[6]}]
set_property PACKAGE_PIN E28 [get_ports {FPGA_GPIO[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FPGA_GPIO[15]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FPGA_GPIO[14]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FPGA_GPIO[13]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FPGA_GPIO[12]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FPGA_GPIO[11]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FPGA_GPIO[10]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FPGA_GPIO[9]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FPGA_GPIO[8]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FPGA_GPIO[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FPGA_GPIO[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FPGA_GPIO[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FPGA_GPIO[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FPGA_GPIO[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FPGA_GPIO[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FPGA_GPIO[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {FPGA_GPIO[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {USB_FPGA[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {USB_FPGA[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {USB_FPGA[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {USB_FPGA[0]}]
set_property PACKAGE_PIN BB16 [get_ports USB_UART_RXD]
set_property IOSTANDARD LVCMOS18 [get_ports USB_I2C_CTRL]
set_property IOSTANDARD LVCMOS18 [get_ports USB_UART_RXD]
set_property IOSTANDARD LVCMOS18 [get_ports USB_UART_TXD]
set_property PACKAGE_PIN BB12 [get_ports ONE_GBE_INT_N]
set_property PACKAGE_PIN BC12 [get_ports ONE_GBE_LINK]
set_property PACKAGE_PIN BD12 [get_ports ONE_GBE_RESET_N]
set_property IOSTANDARD LVCMOS18 [get_ports ONE_GBE_INT_N]
set_property IOSTANDARD LVCMOS18 [get_ports ONE_GBE_LINK]
set_property IOSTANDARD LVCMOS18 [get_ports ONE_GBE_RESET_N]
set_property IOSTANDARD LVCMOS18 [get_ports FPGA_ATX_PSU_KILL]
set_property IOSTANDARD LVCMOS18 [get_ports FPGA_RESET_N]
set_property PACKAGE_PIN BD17 [get_ports ONE_WIRE_EEPROM]
set_property PACKAGE_PIN BC17 [get_ports ONE_WIRE_EEPROM_STRONG_PULLUP_EN_N]
set_property IOSTANDARD LVCMOS18 [get_ports ONE_WIRE_EEPROM]
set_property IOSTANDARD LVCMOS18 [get_ports ONE_WIRE_EEPROM_STRONG_PULLUP_EN_N]
set_property PACKAGE_PIN BC19 [get_ports I2C_RESET_FPGA]
set_property PACKAGE_PIN BB18 [get_ports I2C_SCL_FPGA]
set_property PACKAGE_PIN BC18 [get_ports I2C_SDA_FPGA]
set_property IOSTANDARD LVCMOS18 [get_ports I2C_RESET_FPGA]
set_property IOSTANDARD LVCMOS18 [get_ports I2C_SCL_FPGA]
set_property IOSTANDARD LVCMOS18 [get_ports I2C_SDA_FPGA]
set_property PACKAGE_PIN BD20 [get_ports DEBUG_UART_TX]
set_property IOSTANDARD LVCMOS18 [get_ports DEBUG_UART_RX]
set_property IOSTANDARD LVCMOS18 [get_ports DEBUG_UART_TX]
set_property PACKAGE_PIN AV19 [get_ports AUX_CLK_N]
set_property PACKAGE_PIN AU21 [get_ports AUX_SYNCI_N]
set_property PACKAGE_PIN AY21 [get_ports AUX_SYNCO_N]
set_property IOSTANDARD LVDS [get_ports FPGA_REFCLK_BUF0_P]
set_property IOSTANDARD LVDS [get_ports FPGA_REFCLK_BUF1_P]

set_property PACKAGE_PIN AY23 [get_ports CONFIG_IO_8]
set_property PACKAGE_PIN BA23 [get_ports CONFIG_IO_9]
set_property PACKAGE_PIN BB23 [get_ports CONFIG_IO_10]
set_property PACKAGE_PIN BC23 [get_ports CONFIG_IO_11]
set_property PACKAGE_PIN BB21 [get_ports SPI_CLK]
set_property PACKAGE_PIN BD21 [get_ports SPI_CSB]
set_property PACKAGE_PIN BB20 [get_ports SPI_MISO]


set_property PACKAGE_PIN BC20 [get_ports SPI_MOSI]
set_property IOSTANDARD LVCMOS18 [get_ports CONFIG_IO_8]
set_property IOSTANDARD LVCMOS18 [get_ports CONFIG_IO_9]
set_property IOSTANDARD LVCMOS18 [get_ports CONFIG_IO_10]
set_property IOSTANDARD LVCMOS18 [get_ports CONFIG_IO_11]
set_property IOSTANDARD LVCMOS18 [get_ports SPI_CLK]
set_property IOSTANDARD LVCMOS18 [get_ports SPI_CSB]
set_property IOSTANDARD LVCMOS18 [get_ports SPI_MISO]
set_property IOSTANDARD LVCMOS18 [get_ports SPI_MOSI]

set_property PACKAGE_PIN AV27 [get_ports FPGA_EMCCLK2]

set_property IOSTANDARD LVCMOS18 [get_ports FPGA_EMCCLK2]

set_property IOSTANDARD LVCMOS18 [get_ports EMCCLK_FIX]
set_property PACKAGE_PIN BB27 [get_ports EMCCLK_FIX]

set_property IOSTANDARD LVCMOS18 [get_ports {GND[15]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GND[14]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GND[13]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GND[12]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GND[11]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GND[10]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GND[9]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GND[8]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GND[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GND[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GND[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GND[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GND[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GND[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GND[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {GND[0]}]
set_property PACKAGE_PIN AY31 [get_ports {GND[0]}]
set_property PACKAGE_PIN AW30 [get_ports {GND[1]}]
set_property PACKAGE_PIN AW31 [get_ports {GND[2]}]
set_property PACKAGE_PIN AV28 [get_ports {GND[3]}]
set_property PACKAGE_PIN AV29 [get_ports {GND[4]}]
set_property PACKAGE_PIN AN27 [get_ports {GND[5]}]
set_property PACKAGE_PIN AP27 [get_ports {GND[6]}]
set_property PACKAGE_PIN AT28 [get_ports {GND[7]}]
set_property PACKAGE_PIN AK27 [get_ports {GND[8]}]
set_property PACKAGE_PIN AW26 [get_ports {GND[9]}]
set_property PACKAGE_PIN AY26 [get_ports {GND[10]}]
set_property PACKAGE_PIN AV25 [get_ports {GND[11]}]
set_property PACKAGE_PIN AW25 [get_ports {GND[12]}]
set_property PACKAGE_PIN AW24 [get_ports {GND[13]}]
set_property PACKAGE_PIN AT25 [get_ports {GND[14]}]
set_property PACKAGE_PIN AK23 [get_ports {GND[15]}]

set_property PACKAGE_PIN BA20 [get_ports MEZZANINE_COMBINED_FAULT]
#AI Start: Only need one I2C bus for Mezzanine Site 3
#set_property PACKAGE_PIN A31 [get_ports MEZZANINE_0_SCL_FPGA]
#set_property PACKAGE_PIN A30 [get_ports MEZZANINE_0_SDA_FPGA]
#set_property IOSTANDARD LVCMOS18 [get_ports MEZZANINE_0_SCL_FPGA]
#set_property IOSTANDARD LVCMOS18 [get_ports MEZZANINE_0_SDA_FPGA]
#set_property PACKAGE_PIN BD32 [get_ports MEZZANINE_1_SCL_FPGA]
#set_property PACKAGE_PIN BD31 [get_ports MEZZANINE_1_SDA_FPGA]
#set_property IOSTANDARD LVCMOS18 [get_ports MEZZANINE_1_SDA_FPGA]
#set_property IOSTANDARD LVCMOS18 [get_ports MEZZANINE_1_SCL_FPGA]
#set_property PACKAGE_PIN BD14 [get_ports MEZZANINE_2_SCL_FPGA]
#set_property PACKAGE_PIN BC14 [get_ports MEZZANINE_2_SDA_FPGA]
#set_property IOSTANDARD LVCMOS18 [get_ports MEZZANINE_2_SDA_FPGA]
#set_property IOSTANDARD LVCMOS18 [get_ports MEZZANINE_2_SCL_FPGA]
#AI End: Only need one I2C bus for Mezzanine Site 3
set_property PACKAGE_PIN A14 [get_ports MEZZANINE_3_SCL_FPGA]
set_property PACKAGE_PIN A15 [get_ports MEZZANINE_3_SDA_FPGA]
set_property IOSTANDARD LVCMOS18 [get_ports MEZZANINE_3_SCL_FPGA]
set_property IOSTANDARD LVCMOS18 [get_ports MEZZANINE_3_SDA_FPGA]
set_property IOSTANDARD LVCMOS18 [get_ports MEZZANINE_COMBINED_FAULT]

set_property PACKAGE_PIN B31 [get_ports MEZZANINE_0_INT_N]
set_property IOSTANDARD LVCMOS18 [get_ports MEZZANINE_0_INT_N]
set_property PACKAGE_PIN BC33 [get_ports MEZZANINE_1_INT_N]
set_property IOSTANDARD LVCMOS18 [get_ports MEZZANINE_1_INT_N]
set_property PACKAGE_PIN BC13 [get_ports MEZZANINE_2_INT_N]
set_property IOSTANDARD LVCMOS18 [get_ports MEZZANINE_2_INT_N]
set_property PACKAGE_PIN B15 [get_ports MEZZANINE_3_INT_N]
set_property IOSTANDARD LVCMOS18 [get_ports MEZZANINE_3_INT_N]

set_property PACKAGE_PIN BD35 [get_ports FPGA_RESET_N]
set_property PACKAGE_PIN BC35 [get_ports {FPGA_GPIO[8]}]
set_property PACKAGE_PIN BB35 [get_ports {FPGA_GPIO[9]}]
set_property PACKAGE_PIN BA34 [get_ports {FPGA_GPIO[10]}]
set_property PACKAGE_PIN AY34 [get_ports {FPGA_GPIO[11]}]
set_property PACKAGE_PIN AW34 [get_ports {FPGA_GPIO[12]}]
set_property PACKAGE_PIN BB33 [get_ports {FPGA_GPIO[13]}]
set_property PACKAGE_PIN BA33 [get_ports {FPGA_GPIO[14]}]
set_property PACKAGE_PIN AY33 [get_ports {FPGA_GPIO[15]}]
set_property PACKAGE_PIN BA14 [get_ports MEZZANINE_0_FAULT_N]
set_property PACKAGE_PIN AY14 [get_ports MEZZANINE_1_FAULT_N]
set_property PACKAGE_PIN AW14 [get_ports MEZZANINE_2_FAULT_N]
set_property PACKAGE_PIN AV14 [get_ports MEZZANINE_3_FAULT_N]
set_property PACKAGE_PIN BB13 [get_ports MONITOR_ALERT_N]
set_property PACKAGE_PIN BA13 [get_ports USB_UART_TXD]
set_property PACKAGE_PIN AY13 [get_ports USB_I2C_CTRL]
set_property PACKAGE_PIN AV13 [get_ports DEBUG_UART_RX]
set_property PACKAGE_PIN BD11 [get_ports CPU_PWR_BTN_N]
set_property PACKAGE_PIN BC10 [get_ports CPU_SYS_RESET_N]
set_property PACKAGE_PIN BD10 [get_ports FPGA_ATX_PSU_KILL]
set_property PACKAGE_PIN C15 [get_ports MEZZANINE_1_RESET]
set_property PACKAGE_PIN D15 [get_ports MEZZANINE_2_RESET]
set_property PACKAGE_PIN E14 [get_ports {USB_FPGA[0]}]
set_property PACKAGE_PIN F14 [get_ports {USB_FPGA[1]}]
set_property PACKAGE_PIN E13 [get_ports {USB_FPGA[2]}]
set_property PACKAGE_PIN F13 [get_ports {USB_FPGA[3]}]
set_property PACKAGE_PIN C17 [get_ports MEZZANINE_1_ENABLE_N]
set_property PACKAGE_PIN D17 [get_ports MEZZANINE_1_CLK_SEL]
set_property PACKAGE_PIN E16 [get_ports MEZZANINE_2_CLK_SEL]
set_property PACKAGE_PIN E17 [get_ports MEZZANINE_2_ENABLE_N]
set_property PACKAGE_PIN AV15 [get_ports FPGA_REFCLK_BUF0_N]
set_property PACKAGE_PIN AU18 [get_ports FPGA_REFCLK_BUF1_N]
set_property PACKAGE_PIN BA35 [get_ports MEZZANINE_1_PRESENT_N]

set_property PACKAGE_PIN A10 [get_ports ONE_GBE_MGTREFCLK_P]
set_property PACKAGE_PIN A9 [get_ports ONE_GBE_MGTREFCLK_N]
set_property PACKAGE_PIN B4 [get_ports ONE_GBE_SGMII_TX_P]
set_property PACKAGE_PIN B3 [get_ports ONE_GBE_SGMII_TX_N]
set_property PACKAGE_PIN A6 [get_ports ONE_GBE_SGMII_RX_P]
set_property PACKAGE_PIN A5 [get_ports ONE_GBE_SGMII_RX_N]

#set_property PACKAGE_PIN E10 [get_ports PCIE_MGTREFCLK_P]
#set_property PACKAGE_PIN E9 [get_ports PCIE_MGTREFCLK_N]
#set_property PACKAGE_PIN G2 [get_ports PCIE_LANE0_TX_P]
#set_property PACKAGE_PIN G1 [get_ports PCIE_LANE0_TX_N]
#set_property PACKAGE_PIN D8 [get_ports PCIE_LANE0_RX_P]
#set_property PACKAGE_PIN D7 [get_ports PCIE_LANE0_RX_N]

set_property CONFIG_MODE BPI16 [current_design]
set_property BITSTREAM.CONFIG.EXTMASTERCCLK_EN DIV-2 [current_design]
set_property CONFIG_VOLTAGE 1.8 [current_design]
set_property CFGBVS GND [current_design]
set_property BITSTREAM.CONFIG.BPI_SYNC_MODE TYPE1 [current_design]
set_property BITSTREAM.STARTUP.STARTUPCLK CCLK [current_design]
set_property LOC ICAP_X0Y1 [get_cells wishbone_flash_sdram_interface_0/icape_controller_0/ICAPE2_0]
set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property BITSTREAM.CONFIG.CONFIGFALLBACK ENABLE [current_design]
set_property BITSTREAM.CONFIG.TIMER_CFG 0X00040000 [current_design]

create_clock -period 2.800 -name AUX_CLK_P -waveform {0.000 1.400} [get_ports AUX_CLK_P]
create_clock -period 6.400 -name FPGA_REFCLK_BUF0_P -waveform {0.000 3.200} [get_ports FPGA_REFCLK_BUF0_P]
create_clock -period 6.400 -name ONE_GBE_MGTREFCLK_P -waveform {0.000 3.200} [get_ports ONE_GBE_MGTREFCLK_P]
create_clock -period 16.666 -name FPGA_EMCCLK2 -waveform {0.000 8.333} [get_ports FPGA_EMCCLK2]
#create_generated_clock -name wishbone_flash_sdram_interface_0/icape_controller_0/CLK -source [get_pins {wishbone_flash_sdram_interface_0/icape_controller_0/icape_clk_count_reg[3]/C}] -divide_by 16 [get_pins {wishbone_flash_sdram_interface_0/icape_controller_0/icape_clk_count_reg[3]/Q}]
set_output_delay -clock [get_clocks FPGA_REFCLK_BUF0_P] -min -add_delay -2.500 [get_ports {FLASH_A[*]}]
set_output_delay -clock [get_clocks FPGA_REFCLK_BUF0_P] -max -add_delay -3.000 [get_ports {FLASH_A[*]}]
set_output_delay -clock [get_clocks FPGA_REFCLK_BUF0_P] -min -add_delay -2.500 [get_ports {FLASH_DQ[*]}]
set_output_delay -clock [get_clocks FPGA_REFCLK_BUF0_P] -max -add_delay -3.000 [get_ports {FLASH_DQ[*]}]
set_output_delay -clock [get_clocks FPGA_REFCLK_BUF0_P] -min -add_delay -2.500 [get_ports FLASH_ADV_N]
set_output_delay -clock [get_clocks FPGA_REFCLK_BUF0_P] -max -add_delay -3.000 [get_ports FLASH_ADV_N]
set_output_delay -clock [get_clocks FPGA_REFCLK_BUF0_P] -min -add_delay -2.500 [get_ports FLASH_CS_N]
set_output_delay -clock [get_clocks FPGA_REFCLK_BUF0_P] -max -add_delay -3.000 [get_ports FLASH_CS_N]
set_output_delay -clock [get_clocks FPGA_REFCLK_BUF0_P] -min -add_delay -2.500 [get_ports FLASH_OE_N]
set_output_delay -clock [get_clocks FPGA_REFCLK_BUF0_P] -max -add_delay -3.000 [get_ports FLASH_OE_N]
set_output_delay -clock [get_clocks FPGA_REFCLK_BUF0_P] -min -add_delay -2.500 [get_ports FLASH_RS0]
set_output_delay -clock [get_clocks FPGA_REFCLK_BUF0_P] -max -add_delay -3.000 [get_ports FLASH_RS0]
set_output_delay -clock [get_clocks FPGA_REFCLK_BUF0_P] -min -add_delay -2.500 [get_ports FLASH_RS1]
set_output_delay -clock [get_clocks FPGA_REFCLK_BUF0_P] -max -add_delay -3.000 [get_ports FLASH_RS1]
set_output_delay -clock [get_clocks FPGA_REFCLK_BUF0_P] -min -add_delay -2.500 [get_ports FLASH_WE_N]
set_output_delay -clock [get_clocks FPGA_REFCLK_BUF0_P] -max -add_delay -3.000 [get_ports FLASH_WE_N]
set_output_delay -clock [get_clocks FPGA_REFCLK_BUF0_P] -min -add_delay -2.500 [get_ports SPARTAN_CLK]
set_output_delay -clock [get_clocks FPGA_REFCLK_BUF0_P] -max -add_delay -3.000 [get_ports SPARTAN_CLK]

set_output_delay -clock [get_clocks FPGA_REFCLK_BUF0_P] -min -add_delay -2.500 [get_ports CONFIG_IO_0]
set_output_delay -clock [get_clocks FPGA_REFCLK_BUF0_P] -max -add_delay -2.500 [get_ports CONFIG_IO_0]
set_output_delay -clock [get_clocks FPGA_REFCLK_BUF0_P] -min -add_delay -2.500 [get_ports CONFIG_IO_1]
set_output_delay -clock [get_clocks FPGA_REFCLK_BUF0_P] -max -add_delay -2.500 [get_ports CONFIG_IO_1]
set_output_delay -clock [get_clocks FPGA_REFCLK_BUF0_P] -min -add_delay -2.500 [get_ports CONFIG_IO_3]
set_output_delay -clock [get_clocks FPGA_REFCLK_BUF0_P] -max -add_delay -2.500 [get_ports CONFIG_IO_3]
set_output_delay -clock [get_clocks FPGA_REFCLK_BUF0_P] -min -add_delay -2.500 [get_ports CONFIG_IO_4]
set_output_delay -clock [get_clocks FPGA_REFCLK_BUF0_P] -max -add_delay -2.500 [get_ports CONFIG_IO_4]
set_output_delay -clock [get_clocks FPGA_REFCLK_BUF0_P] -min -add_delay -2.500 [get_ports CONFIG_IO_6]
set_output_delay -clock [get_clocks FPGA_REFCLK_BUF0_P] -max -add_delay -2.500 [get_ports CONFIG_IO_6]
set_output_delay -clock [get_clocks FPGA_REFCLK_BUF0_P] -min -add_delay -2.500 [get_ports CONFIG_IO_7]
set_output_delay -clock [get_clocks FPGA_REFCLK_BUF0_P] -max -add_delay -2.500 [get_ports CONFIG_IO_7]
set_output_delay -clock [get_clocks FPGA_REFCLK_BUF0_P] -min -add_delay -2.500 [get_ports CONFIG_IO_8]
set_output_delay -clock [get_clocks FPGA_REFCLK_BUF0_P] -max -add_delay -2.500 [get_ports CONFIG_IO_8]
set_output_delay -clock [get_clocks FPGA_REFCLK_BUF0_P] -min -add_delay -2.500 [get_ports CONFIG_IO_9]
set_output_delay -clock [get_clocks FPGA_REFCLK_BUF0_P] -max -add_delay -2.500 [get_ports CONFIG_IO_9]

set_clock_groups -asynchronous -group [get_clocks clkout0] -group [get_clocks FPGA_REFCLK_BUF0_P]
set_clock_groups -asynchronous -group [get_clocks FPGA_REFCLK_BUF0_P] -group [get_clocks clkout0]

set_clock_groups -asynchronous -group [get_clocks AUX_CLK_P] -group [get_clocks FPGA_REFCLK_BUF0_P]
set_clock_groups -asynchronous -group [get_clocks FPGA_REFCLK_BUF0_P] -group [get_clocks AUX_CLK_P]

set_false_path -to [get_pins FPGA_DNA_CHECKER_inst/FPGA_DNA_O_reg[*]/D]

set_false_path -to [get_pins clock_frequency_measure_1/second_toggle_z_reg/D]
set_false_path -from [get_pins {clock_frequency_measure_1/clk_count_low_reg_reg[*]/C}]
set_false_path -from [get_pins {clock_frequency_measure_1/clk_count_high_reg_reg[*]/C}]
set_false_path -to [get_pins clock_frequency_measure_2/second_toggle_z_reg/D]
set_false_path -from [get_pins {clock_frequency_measure_2/clk_count_low_reg_reg[*]/C}]
set_false_path -from [get_pins {clock_frequency_measure_2/clk_count_high_reg_reg[*]/C}]

set_property PACKAGE_PIN J10 [get_ports MEZ_REFCLK_0_P]
set_property PACKAGE_PIN J9 [get_ports MEZ_REFCLK_0_N]
set_property PACKAGE_PIN P4 [get_ports MEZ_PHY11_LANE_TX_P[0]]
set_property PACKAGE_PIN P3 [get_ports MEZ_PHY11_LANE_TX_N[0]]
set_property PACKAGE_PIN L6 [get_ports MEZ_PHY11_LANE_RX_P[0]]
set_property PACKAGE_PIN L5 [get_ports MEZ_PHY11_LANE_RX_N[0]]
set_property PACKAGE_PIN N2 [get_ports MEZ_PHY11_LANE_TX_P[1]]
set_property PACKAGE_PIN N1 [get_ports MEZ_PHY11_LANE_TX_N[1]]
set_property PACKAGE_PIN K8 [get_ports MEZ_PHY11_LANE_RX_P[1]]
set_property PACKAGE_PIN K7 [get_ports MEZ_PHY11_LANE_RX_N[1]]
set_property PACKAGE_PIN M4 [get_ports MEZ_PHY11_LANE_TX_P[2]]
set_property PACKAGE_PIN M3 [get_ports MEZ_PHY11_LANE_TX_N[2]]
set_property PACKAGE_PIN J6 [get_ports MEZ_PHY11_LANE_RX_P[2]]
set_property PACKAGE_PIN J5 [get_ports MEZ_PHY11_LANE_RX_N[2]]
set_property PACKAGE_PIN L2 [get_ports MEZ_PHY11_LANE_TX_P[3]]
set_property PACKAGE_PIN L1 [get_ports MEZ_PHY11_LANE_TX_N[3]]
set_property PACKAGE_PIN H8 [get_ports MEZ_PHY11_LANE_RX_P[3]]
set_property PACKAGE_PIN H7 [get_ports MEZ_PHY11_LANE_RX_N[3]]

create_clock -period 6.400 -waveform {0.000 3.200} [get_ports MEZ_REFCLK_0_P]
create_pblock MEZ_PHY11_QSFP
add_cells_to_pblock [get_pblocks MEZ_PHY11_QSFP] [get_cells -quiet [list generate_IEEE802_3_XL_PHY_ROACH3.IEEE802_3_XL_PHY_0/PHY_inst/RX_CLK_RCC]]
add_cells_to_pblock [get_pblocks MEZ_PHY11_QSFP] [get_cells -quiet [list generate_IEEE802_3_XL_PHY_ROACH3.IEEE802_3_XL_PHY_0/PHY_inst/TX_CLK_RCC]]
resize_pblock [get_pblocks MEZ_PHY11_QSFP] -add {CLOCKREGION_X1Y7:CLOCKREGION_X1Y7}

#AI Start: Only Single 40GbE Core Utilised (comment out other 3 x 40GbE Cores)
#set_property PACKAGE_PIN N10 [get_ports MEZ_REFCLK_1_P]
#set_property PACKAGE_PIN N9 [get_ports MEZ_REFCLK_1_N]
#set_property PACKAGE_PIN V4 [get_ports MEZ_PHY12_LANE_TX_P[0]]
#set_property PACKAGE_PIN V3 [get_ports MEZ_PHY12_LANE_TX_N[0]]
#set_property PACKAGE_PIN R6 [get_ports MEZ_PHY12_LANE_RX_P[0]]
#set_property PACKAGE_PIN R5 [get_ports MEZ_PHY12_LANE_RX_N[0]]
#set_property PACKAGE_PIN U2 [get_ports MEZ_PHY12_LANE_TX_P[1]]
#set_property PACKAGE_PIN U1 [get_ports MEZ_PHY12_LANE_TX_N[1]]
#set_property PACKAGE_PIN P8 [get_ports MEZ_PHY12_LANE_RX_P[1]]
#set_property PACKAGE_PIN P7 [get_ports MEZ_PHY12_LANE_RX_N[1]]
#set_property PACKAGE_PIN T4 [get_ports MEZ_PHY12_LANE_TX_P[2]]
#set_property PACKAGE_PIN T3 [get_ports MEZ_PHY12_LANE_TX_N[2]]
#set_property PACKAGE_PIN N6 [get_ports MEZ_PHY12_LANE_RX_P[2]]
#set_property PACKAGE_PIN N5 [get_ports MEZ_PHY12_LANE_RX_N[2]]
#set_property PACKAGE_PIN R2 [get_ports MEZ_PHY12_LANE_TX_P[3]]
#set_property PACKAGE_PIN R1 [get_ports MEZ_PHY12_LANE_TX_N[3]]
#set_property PACKAGE_PIN M8 [get_ports MEZ_PHY12_LANE_RX_P[3]]
#set_property PACKAGE_PIN M7 [get_ports MEZ_PHY12_LANE_RX_N[3]]

#create_clock -period 6.400 -waveform {0.000 3.200} [get_ports MEZ_REFCLK_1_P]
#create_pblock MEZ_PHY12_QSFP
#add_cells_to_pblock [get_pblocks MEZ_PHY12_QSFP] [get_cells -quiet [list generate_IEEE802_3_XL_PHY_ROACH3.IEEE802_3_XL_PHY_1/PHY_inst/RX_CLK_RCC]]
#add_cells_to_pblock [get_pblocks MEZ_PHY12_QSFP] [get_cells -quiet [list generate_IEEE802_3_XL_PHY_ROACH3.IEEE802_3_XL_PHY_1/PHY_inst/TX_CLK_RCC]]
#resize_pblock [get_pblocks MEZ_PHY12_QSFP] -add {CLOCKREGION_X1Y6:CLOCKREGION_X1Y6}

#set_property PACKAGE_PIN U10 [get_ports MEZ_REFCLK_2_P]
#set_property PACKAGE_PIN U9 [get_ports MEZ_REFCLK_2_N]
#set_property PACKAGE_PIN AB4 [get_ports MEZ_PHY21_LANE_TX_P[0]]
#set_property PACKAGE_PIN AB3 [get_ports MEZ_PHY21_LANE_TX_N[0]]
#set_property PACKAGE_PIN W6 [get_ports MEZ_PHY21_LANE_RX_P[0]]
#set_property PACKAGE_PIN W5 [get_ports MEZ_PHY21_LANE_RX_N[0]]
#set_property PACKAGE_PIN AA2 [get_ports MEZ_PHY21_LANE_TX_P[1]]
#set_property PACKAGE_PIN AA1 [get_ports MEZ_PHY21_LANE_TX_N[1]]
#set_property PACKAGE_PIN V8 [get_ports MEZ_PHY21_LANE_RX_P[1]]
#set_property PACKAGE_PIN V7 [get_ports MEZ_PHY21_LANE_RX_N[1]]
#set_property PACKAGE_PIN Y4 [get_ports MEZ_PHY21_LANE_TX_P[2]]
#set_property PACKAGE_PIN Y3 [get_ports MEZ_PHY21_LANE_TX_N[2]]
#set_property PACKAGE_PIN U6 [get_ports MEZ_PHY21_LANE_RX_P[2]]
#set_property PACKAGE_PIN U5 [get_ports MEZ_PHY21_LANE_RX_N[2]]
#set_property PACKAGE_PIN W2 [get_ports MEZ_PHY21_LANE_TX_P[3]]
#set_property PACKAGE_PIN W1 [get_ports MEZ_PHY21_LANE_TX_N[3]]
#set_property PACKAGE_PIN T8 [get_ports MEZ_PHY21_LANE_RX_P[3]]
#set_property PACKAGE_PIN T7 [get_ports MEZ_PHY21_LANE_RX_N[3]]

#create_clock -period 6.400 -waveform {0.000 3.200} [get_ports MEZ_REFCLK_2_P]
#create_pblock MEZ_PHY21_QSFP
#add_cells_to_pblock [get_pblocks MEZ_PHY21_QSFP] [get_cells -quiet [list generate_IEEE802_3_XL_PHY_ROACH3.IEEE802_3_XL_PHY_2/PHY_inst/RX_CLK_RCC]]
#add_cells_to_pblock [get_pblocks MEZ_PHY21_QSFP] [get_cells -quiet [list generate_IEEE802_3_XL_PHY_ROACH3.IEEE802_3_XL_PHY_2/PHY_inst/TX_CLK_RCC]]
#resize_pblock [get_pblocks MEZ_PHY21_QSFP] -add {CLOCKREGION_X1Y5:CLOCKREGION_X1Y5}

#set_property PACKAGE_PIN AA10 [get_ports MEZ_REFCLK_3_P]
#set_property PACKAGE_PIN AA9 [get_ports MEZ_REFCLK_3_N]
#set_property PACKAGE_PIN AF4 [get_ports MEZ_PHY22_LANE_TX_P[0]]
#set_property PACKAGE_PIN AF3 [get_ports MEZ_PHY22_LANE_TX_N[0]]
#set_property PACKAGE_PIN AD8 [get_ports MEZ_PHY22_LANE_RX_P[0]]
#set_property PACKAGE_PIN AD7 [get_ports MEZ_PHY22_LANE_RX_N[0]]
#set_property PACKAGE_PIN AE2 [get_ports MEZ_PHY22_LANE_TX_P[1]]
#set_property PACKAGE_PIN AE1 [get_ports MEZ_PHY22_LANE_TX_N[1]]
#set_property PACKAGE_PIN AC6 [get_ports MEZ_PHY22_LANE_RX_P[1]]
#set_property PACKAGE_PIN AC5 [get_ports MEZ_PHY22_LANE_RX_N[1]]
#set_property PACKAGE_PIN AD4 [get_ports MEZ_PHY22_LANE_TX_P[2]]
#set_property PACKAGE_PIN AD3 [get_ports MEZ_PHY22_LANE_TX_N[2]]
#set_property PACKAGE_PIN AA6 [get_ports MEZ_PHY22_LANE_RX_P[2]]
#set_property PACKAGE_PIN AA5 [get_ports MEZ_PHY22_LANE_RX_N[2]]
#set_property PACKAGE_PIN AC2 [get_ports MEZ_PHY22_LANE_TX_P[3]]
#set_property PACKAGE_PIN AC1 [get_ports MEZ_PHY22_LANE_TX_N[3]]
#set_property PACKAGE_PIN Y8 [get_ports MEZ_PHY22_LANE_RX_P[3]]
#set_property PACKAGE_PIN Y7 [get_ports MEZ_PHY22_LANE_RX_N[3]]

#create_clock -period 6.400 -waveform {0.000 3.200} [get_ports MEZ_REFCLK_3_P]
#create_pblock MEZ_PHY22_QSFP
#add_cells_to_pblock [get_pblocks MEZ_PHY22_QSFP] [get_cells -quiet [list generate_IEEE802_3_XL_PHY_ROACH3.IEEE802_3_XL_PHY_3/PHY_inst/RX_CLK_RCC]]
#add_cells_to_pblock [get_pblocks MEZ_PHY22_QSFP] [get_cells -quiet [list generate_IEEE802_3_XL_PHY_ROACH3.IEEE802_3_XL_PHY_3/PHY_inst/TX_CLK_RCC]]
#resize_pblock [get_pblocks MEZ_PHY22_QSFP] -add {CLOCKREGION_X1Y4:CLOCKREGION_X1Y4}

#AI Start: Only Single 40GbE Core Utilised (comment out other 3 x 40GbE Cores)

#################################################################################
### HITECH GLOBAL DEV BOARD CONSTRAINTS
#################################################################################
#set_property PACKAGE_PIN AV24 [get_ports FPGA_USER_IO0_F]
#set_property PACKAGE_PIN AV23 [get_ports FPGA_USER_IO1_F]
#set_property PACKAGE_PIN AW24 [get_ports FPGA_USER_IO2_F]
#set_property PACKAGE_PIN AY24 [get_ports FPGA_USER_IO3_F]
#set_property PACKAGE_PIN AY23 [get_ports FPGA_USER_IO4_F]
#set_property PACKAGE_PIN BA24 [get_ports FPGA_USER_IO5_F]
#set_property PACKAGE_PIN BA23 [get_ports FPGA_USER_IO6_F]
#set_property PACKAGE_PIN BB23 [get_ports FPGA_USER_IO7_F]
#set_property PACKAGE_PIN U22 [get_ports FPGA_USER_LED0]
#set_property PACKAGE_PIN U20 [get_ports FPGA_USER_LED1]
#set_property PACKAGE_PIN D21 [get_ports FPGA_USER_LED2]
#set_property PACKAGE_PIN G20 [get_ports FPGA_USER_LED3]
#set_property PACKAGE_PIN E22 [get_ports FPGA_USER_LED4]
#set_property PACKAGE_PIN F21 [get_ports FPGA_USER_LED5]
#set_property PACKAGE_PIN BB22 [get_ports FPGA_USER_LED6]
#set_property PACKAGE_PIN BD22 [get_ports FPGA_USER_LED7]
#set_property PACKAGE_PIN AT28 [get_ports I2C_MAIN0_RST_N]
#set_property PACKAGE_PIN AN27 [get_ports I2C_MAIN0_SCL_F]
#set_property PACKAGE_PIN AP27 [get_ports I2C_MAIN0_SDA_F]
#set_property PACKAGE_PIN BC24 [get_ports I2C_MAIN1_RST_N]
#set_property PACKAGE_PIN BD24 [get_ports I2C_MAIN1_SCL_F]
#set_property PACKAGE_PIN BC23 [get_ports I2C_MAIN1_SDA_F]
#set_property PACKAGE_PIN AU23 [get_ports I2C_MAIN2_RST_N]
#set_property PACKAGE_PIN AN23 [get_ports I2C_MAIN2_SCL_F]
#set_property PACKAGE_PIN AT23 [get_ports I2C_MAIN2_SDA_F]
#set_property PACKAGE_PIN AV29 [get_ports PCIE_PERST_N_F]
#set_property PACKAGE_PIN L13 [get_ports S0_LOS_F]
#set_property PACKAGE_PIN K14 [get_ports S0_MOD_F]
#set_property PACKAGE_PIN K13 [get_ports S0_TX_DIS_F]
#set_property PACKAGE_PIN AY26 [get_ports UART_CTS]
#set_property PACKAGE_PIN AT25 [get_ports UART_DCD]
#set_property PACKAGE_PIN AV25 [get_ports UART_DSR]
#set_property PACKAGE_PIN AT26 [get_ports UART_DTR]
#set_property PACKAGE_PIN BD26 [get_ports UART_GPIO0]
#set_property PACKAGE_PIN BC25 [get_ports UART_GPIO1]
#set_property PACKAGE_PIN BD25 [get_ports UART_GPIO2]
#set_property PACKAGE_PIN BB25 [get_ports UART_GPIO3]
#set_property PACKAGE_PIN AT24 [get_ports UART_RI]
#set_property PACKAGE_PIN BB26 [get_ports UART_RST_N]
#set_property PACKAGE_PIN AU27 [get_ports UART_RTS]
#set_property PACKAGE_PIN AW26 [get_ports UART_RXD]
#set_property PACKAGE_PIN BA25 [get_ports UART_SUSPEND_N]
#set_property PACKAGE_PIN AW25 [get_ports UART_TXD]
#set_property PACKAGE_PIN BA26 [get_ports USB_PERI_PWR]

#set_property PACKAGE_PIN BC22 [get_ports FPGA_USER_PB]
#set_property PACKAGE_PIN AU26 [get_ports REFCLK_N]
#set_property IOSTANDARD LVCMOS18 [get_ports FPGA_USER_IO0_F]
#set_property IOSTANDARD LVCMOS18 [get_ports FPGA_USER_IO1_F]
#set_property IOSTANDARD LVCMOS18 [get_ports FPGA_USER_IO2_F]
#set_property IOSTANDARD LVCMOS18 [get_ports FPGA_USER_IO3_F]
#set_property IOSTANDARD LVCMOS18 [get_ports FPGA_USER_IO4_F]
#set_property IOSTANDARD LVCMOS18 [get_ports FPGA_USER_IO5_F]
#set_property IOSTANDARD LVCMOS18 [get_ports FPGA_USER_IO6_F]
#set_property IOSTANDARD LVCMOS18 [get_ports FPGA_USER_IO7_F]
#set_property IOSTANDARD LVCMOS15 [get_ports FPGA_USER_LED0]
#set_property IOSTANDARD LVCMOS15 [get_ports FPGA_USER_LED1]
#set_property IOSTANDARD LVCMOS15 [get_ports FPGA_USER_LED2]
#set_property IOSTANDARD LVCMOS15 [get_ports FPGA_USER_LED3]
#set_property IOSTANDARD LVCMOS15 [get_ports FPGA_USER_LED4]
#set_property IOSTANDARD LVCMOS15 [get_ports FPGA_USER_LED5]
#set_property IOSTANDARD LVCMOS15 [get_ports FPGA_USER_LED6]
#set_property IOSTANDARD LVCMOS15 [get_ports FPGA_USER_LED7]
#set_property IOSTANDARD LVCMOS15 [get_ports FPGA_USER_PB]
#set_property IOSTANDARD LVCMOS18 [get_ports I2C_MAIN0_RST_N]
#set_property IOSTANDARD LVCMOS18 [get_ports I2C_MAIN0_SCL_F]
#set_property IOSTANDARD LVCMOS18 [get_ports I2C_MAIN0_SDA_F]
#set_property IOSTANDARD LVCMOS18 [get_ports I2C_MAIN1_RST_N]
#set_property IOSTANDARD LVCMOS18 [get_ports I2C_MAIN1_SCL_F]
#set_property IOSTANDARD LVCMOS18 [get_ports I2C_MAIN1_SDA_F]
#set_property IOSTANDARD LVCMOS18 [get_ports I2C_MAIN2_RST_N]
#set_property IOSTANDARD LVCMOS18 [get_ports I2C_MAIN2_SCL_F]
#set_property IOSTANDARD LVCMOS18 [get_ports I2C_MAIN2_SDA_F]
#set_property IOSTANDARD LVCMOS18 [get_ports PCIE_PERST_N_F]
#set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports REFCLK_P]
#set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports REFCLK_N]
#set_property IOSTANDARD LVCMOS15 [get_ports S0_LOS_F]
#set_property IOSTANDARD LVCMOS15 [get_ports S0_MOD_F]
#set_property IOSTANDARD LVCMOS15 [get_ports S0_TX_DIS_F]
#set_property IOSTANDARD LVCMOS18 [get_ports UART_CTS]
#set_property IOSTANDARD LVCMOS18 [get_ports UART_DCD]
#set_property IOSTANDARD LVCMOS18 [get_ports UART_DSR]
#set_property IOSTANDARD LVCMOS18 [get_ports UART_DTR]
#set_property IOSTANDARD LVCMOS18 [get_ports UART_GPIO0]
#set_property IOSTANDARD LVCMOS18 [get_ports UART_GPIO1]
#set_property IOSTANDARD LVCMOS18 [get_ports UART_GPIO2]
#set_property IOSTANDARD LVCMOS18 [get_ports UART_GPIO3]
#set_property IOSTANDARD LVCMOS18 [get_ports UART_RI]
#set_property IOSTANDARD LVCMOS18 [get_ports UART_RST_N]
#set_property IOSTANDARD LVCMOS18 [get_ports UART_RTS]
#set_property IOSTANDARD LVCMOS18 [get_ports UART_SUSPEND_N]
#set_property IOSTANDARD LVCMOS18 [get_ports UART_TXD]
#set_property IOSTANDARD LVCMOS18 [get_ports USB_PERI_PWR]
#set_property IOSTANDARD LVCMOS18 [get_ports UART_RXD]
#set_property IOSTANDARD LVCMOS18 [get_ports EMCCLK_FIX]

#create_clock -period 6.400 -name REFCLK_P -waveform {0.000 3.200} [get_ports REFCLK_P]

#create_clock -period 6.400 -name SFP_CLK_MGT_P -waveform {0.000 3.200} [get_ports SFP_CLK_MGT_P]
#set_property PACKAGE_PIN N9 [get_ports SFP_CLK_MGT_N]

#set_property PACKAGE_PIN M7 [get_ports SFP0_RX_N]


#set_clock_groups -name REFCLK_P_to_clkout0_async_group -asynchronous -group [get_clocks REFCLK_P] -group [get_clocks clkout0]
#set_property LOC BSCAN_X0Y1 [get_cells cont_microblaze_wrapper_0/cont_microblaze_i/mdm_1/U0/Use_E2.BSCANE2_I]

#set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_A[25]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_A[24]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_A[23]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_A[22]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_A[21]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_A[20]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_A[19]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_A[18]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_A[17]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_A[16]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_A[15]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_A[14]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_A[13]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_A[12]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_A[11]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_A[10]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_A[9]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_A[8]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_A[7]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_A[6]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_A[5]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_A[4]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_A[3]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_A[2]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_A[1]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_A[0]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_DQ[15]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_DQ[14]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_DQ[13]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_DQ[12]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_DQ[11]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_DQ[10]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_DQ[9]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_DQ[8]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_DQ[7]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_DQ[6]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_DQ[5]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_DQ[4]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_DQ[3]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_DQ[2]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_DQ[1]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {FLASH_DQ[0]}]
#set_property IOSTANDARD LVCMOS18 [get_ports FLASH_ADV_N]
#set_property IOSTANDARD LVCMOS18 [get_ports FLASH_CS_N]
#set_property IOSTANDARD LVCMOS18 [get_ports FLASH_OE_N]
#set_property IOSTANDARD LVCMOS18 [get_ports FLASH_RS0]
#set_property IOSTANDARD LVCMOS18 [get_ports FLASH_RS1]
#set_property IOSTANDARD LVCMOS18 [get_ports FLASH_WE_N]
#set_property IOSTANDARD LVCMOS18 [get_ports EMCCLK]
#set_property PACKAGE_PIN AN24 [get_ports FLASH_ADV_N]
#set_property PACKAGE_PIN BA29 [get_ports FLASH_CS_N]
#set_property PACKAGE_PIN AL24 [get_ports FLASH_OE_N]
#set_property PACKAGE_PIN AJ26 [get_ports FLASH_RS0]
#set_property PACKAGE_PIN AJ25 [get_ports FLASH_RS1]
#set_property PACKAGE_PIN AL25 [get_ports FLASH_WE_N]
#set_property PACKAGE_PIN BB28 [get_ports EMCCLK]
#set_property PACKAGE_PIN BA28 [get_ports {FLASH_DQ[15]}]
#set_property PACKAGE_PIN AY28 [get_ports {FLASH_DQ[14]}]
#set_property PACKAGE_PIN BA31 [get_ports {FLASH_DQ[13]}]
#set_property PACKAGE_PIN AY27 [get_ports {FLASH_DQ[12]}]
#set_property PACKAGE_PIN AW27 [get_ports {FLASH_DQ[11]}]
#set_property PACKAGE_PIN AY29 [get_ports {FLASH_DQ[10]}]
#set_property PACKAGE_PIN AW29 [get_ports {FLASH_DQ[9]}]
#set_property PACKAGE_PIN BA30 [get_ports {FLASH_DQ[8]}]
#set_property PACKAGE_PIN BC29 [get_ports {FLASH_DQ[7]}]
#set_property PACKAGE_PIN BC28 [get_ports {FLASH_DQ[6]}]
#set_property PACKAGE_PIN BC30 [get_ports {FLASH_DQ[5]}]
#set_property PACKAGE_PIN BB30 [get_ports {FLASH_DQ[4]}]
#set_property PACKAGE_PIN BD30 [get_ports {FLASH_DQ[3]}]
#set_property PACKAGE_PIN BD29 [get_ports {FLASH_DQ[2]}]
#set_property PACKAGE_PIN BD27 [get_ports {FLASH_DQ[1]}]
#set_property PACKAGE_PIN BC27 [get_ports {FLASH_DQ[0]}]
#set_property PACKAGE_PIN AP25 [get_ports {FLASH_A[25]}]
#set_property PACKAGE_PIN AN25 [get_ports {FLASH_A[24]}]
#set_property PACKAGE_PIN AP26 [get_ports {FLASH_A[23]}]
#set_property PACKAGE_PIN AL23 [get_ports {FLASH_A[22]}]
#set_property PACKAGE_PIN AM23 [get_ports {FLASH_A[21]}]
#set_property PACKAGE_PIN AM25 [get_ports {FLASH_A[20]}]
#set_property PACKAGE_PIN AM26 [get_ports {FLASH_A[19]}]
#set_property PACKAGE_PIN AK24 [get_ports {FLASH_A[18]}]
#set_property PACKAGE_PIN AK26 [get_ports {FLASH_A[17]}]
#set_property PACKAGE_PIN AL26 [get_ports {FLASH_A[16]}]
#set_property PACKAGE_PIN AT29 [get_ports {FLASH_A[15]}]
#set_property PACKAGE_PIN AP29 [get_ports {FLASH_A[14]}]
#set_property PACKAGE_PIN AP30 [get_ports {FLASH_A[13]}]
#set_property PACKAGE_PIN AR28 [get_ports {FLASH_A[12]}]
#set_property PACKAGE_PIN AR29 [get_ports {FLASH_A[11]}]
#set_property PACKAGE_PIN AN28 [get_ports {FLASH_A[10]}]
#set_property PACKAGE_PIN AN29 [get_ports {FLASH_A[9]}]
#set_property PACKAGE_PIN AM30 [get_ports {FLASH_A[8]}]
#set_property PACKAGE_PIN AN30 [get_ports {FLASH_A[7]}]
#set_property PACKAGE_PIN AK28 [get_ports {FLASH_A[6]}]
#set_property PACKAGE_PIN AM27 [get_ports {FLASH_A[5]}]
#set_property PACKAGE_PIN AM28 [get_ports {FLASH_A[4]}]
#set_property PACKAGE_PIN AK29 [get_ports {FLASH_A[2]}]
#set_property PACKAGE_PIN AL28 [get_ports {FLASH_A[1]}]
#set_property PACKAGE_PIN AL29 [get_ports {FLASH_A[0]}]
#set_property PACKAGE_PIN AJ29 [get_ports {FLASH_A[3]}]
#set_property PACKAGE_PIN BB27 [get_ports EMCCLK_FIX]

#set_property PACKAGE_PIN AU28 [get_ports ONE_WIRE_EEPROM]
#set_property IOSTANDARD LVCMOS18 [get_ports ONE_WIRE_EEPROM]

#set_property CONFIG_MODE BPI16 [current_design]
#set_property BITSTREAM.CONFIG.EXTMASTERCCLK_EN DIV-2 [current_design]
#set_property CONFIG_VOLTAGE 1.8 [current_design]
#set_property CFGBVS GND [current_design]
#set_property BITSTREAM.CONFIG.BPI_SYNC_MODE TYPE1 [current_design]

#set_property BITSTREAM.CONFIG.NEXT_CONFIG_REBOOT ENABLE [current_design]
#set_property BITSTREAM.STARTUP.STARTUPCLK CCLK [current_design]
#set_property LOC ICAP_X0Y1 [get_cells wishbone_flash_sdram_interface_0/icape_controller_0/ICAPE2_0]


#set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]



#set_property BITSTREAM.CONFIG.NEXT_CONFIG_REBOOT ENABLE [current_design]
#set_property BITSTREAM.STARTUP.STARTUPCLK CCLK [current_design]
#set_property LOC ICAP_X0Y1 [get_cells wishbone_flash_sdram_interface_0/icape_controller_0/ICAPE2_0]

#set_property PACKAGE_PIN AU25 [get_ports REFCLK_P]

###
### QSFP pin locs and timing constraints
###
#create_clock -period 6.400 -waveform {0.000 3.200} [get_ports QSFP_GTREFCLK_PAD_P_I]
#set_property PACKAGE_PIN A35 [get_ports QSFP_GTREFCLK_PAD_P_I]

#set_property PACKAGE_PIN F41 [get_ports {QSFP_TXP_O[0]}]
#set_property PACKAGE_PIN E43 [get_ports {QSFP_TXP_O[1]}]
#set_property PACKAGE_PIN C43 [get_ports {QSFP_TXP_O[2]}]
#set_property PACKAGE_PIN B41 [get_ports {QSFP_TXP_O[3]}]

#create_pblock QSFP
#add_cells_to_pblock [get_pblocks QSFP] [get_cells -quiet [list generate_IEEE802_3_XL_PHY_DEV_PLATFORM.IEEE802_3_XL_PHY_0/PCS_inst/RX2 generate_IEEE802_3_XL_PHY_DEV_PLATFORM.IEEE802_3_XL_PHY_0/RX_CLK_RCC]]
#resize_pblock [get_pblocks QSFP] -add {CLOCKREGION_X0Y9:CLOCKREGION_X0Y9}


#set_clock_groups -name REFCLK_P_to_ref_clkB_MMCME2_BASE_inst_async_group -asynchronous -group [get_clocks REFCLK_P] -group [get_clocks -of_objects [get_pins XL_PMA_TX_RESET_CLOCKING_CONTROLLER_0/ref_clkB_MMCME2_BASE_inst/CLKOUT1]]

set_property OFFCHIP_TERM NONE [get_ports CONFIG_IO_0]
set_property OFFCHIP_TERM NONE [get_ports CONFIG_IO_1]
set_property OFFCHIP_TERM NONE [get_ports CONFIG_IO_10]
set_property OFFCHIP_TERM NONE [get_ports CONFIG_IO_11]
set_property OFFCHIP_TERM NONE [get_ports CONFIG_IO_3]
set_property OFFCHIP_TERM NONE [get_ports CONFIG_IO_4]
set_property OFFCHIP_TERM NONE [get_ports CONFIG_IO_6]
set_property OFFCHIP_TERM NONE [get_ports CONFIG_IO_7]
set_property OFFCHIP_TERM NONE [get_ports CONFIG_IO_8]
set_property OFFCHIP_TERM NONE [get_ports CONFIG_IO_9]
set_property OFFCHIP_TERM NONE [get_ports CPU_PWR_BTN_N]
set_property OFFCHIP_TERM NONE [get_ports CPU_PWR_OK]
set_property OFFCHIP_TERM NONE [get_ports CPU_SYS_RESET_N]
set_property OFFCHIP_TERM NONE [get_ports DEBUG_UART_TX]
set_property OFFCHIP_TERM NONE [get_ports FAN_CONT_RST_N]
set_property OFFCHIP_TERM NONE [get_ports FLASH_ADV_N]
set_property OFFCHIP_TERM NONE [get_ports FLASH_A[0]]
set_property OFFCHIP_TERM NONE [get_ports FLASH_A[10]]
set_property OFFCHIP_TERM NONE [get_ports FLASH_A[11]]
set_property OFFCHIP_TERM NONE [get_ports FLASH_A[12]]
set_property OFFCHIP_TERM NONE [get_ports FLASH_A[13]]
set_property OFFCHIP_TERM NONE [get_ports FLASH_A[14]]
set_property OFFCHIP_TERM NONE [get_ports FLASH_A[15]]
set_property OFFCHIP_TERM NONE [get_ports FLASH_A[16]]
set_property OFFCHIP_TERM NONE [get_ports FLASH_A[17]]
set_property OFFCHIP_TERM NONE [get_ports FLASH_A[18]]
set_property OFFCHIP_TERM NONE [get_ports FLASH_A[19]]
set_property OFFCHIP_TERM NONE [get_ports FLASH_A[1]]
set_property OFFCHIP_TERM NONE [get_ports FLASH_A[20]]
set_property OFFCHIP_TERM NONE [get_ports FLASH_A[21]]
set_property OFFCHIP_TERM NONE [get_ports FLASH_A[22]]
set_property OFFCHIP_TERM NONE [get_ports FLASH_A[23]]
set_property OFFCHIP_TERM NONE [get_ports FLASH_A[24]]
set_property OFFCHIP_TERM NONE [get_ports FLASH_A[25]]
set_property OFFCHIP_TERM NONE [get_ports FLASH_A[26]]
set_property OFFCHIP_TERM NONE [get_ports FLASH_A[27]]
set_property OFFCHIP_TERM NONE [get_ports FLASH_A[28]]
set_property OFFCHIP_TERM NONE [get_ports FLASH_A[2]]
set_property OFFCHIP_TERM NONE [get_ports FLASH_A[3]]
set_property OFFCHIP_TERM NONE [get_ports FLASH_A[4]]
set_property OFFCHIP_TERM NONE [get_ports FLASH_A[5]]
set_property OFFCHIP_TERM NONE [get_ports FLASH_A[6]]
set_property OFFCHIP_TERM NONE [get_ports FLASH_A[7]]
set_property OFFCHIP_TERM NONE [get_ports FLASH_A[8]]
set_property OFFCHIP_TERM NONE [get_ports FLASH_A[9]]
set_property OFFCHIP_TERM NONE [get_ports FLASH_CS_N]
set_property OFFCHIP_TERM NONE [get_ports FLASH_DQ[0]]
set_property OFFCHIP_TERM NONE [get_ports FLASH_DQ[10]]
set_property OFFCHIP_TERM NONE [get_ports FLASH_DQ[11]]
set_property OFFCHIP_TERM NONE [get_ports FLASH_DQ[12]]
set_property OFFCHIP_TERM NONE [get_ports FLASH_DQ[13]]
set_property OFFCHIP_TERM NONE [get_ports FLASH_DQ[14]]
set_property OFFCHIP_TERM NONE [get_ports FLASH_DQ[15]]
set_property OFFCHIP_TERM NONE [get_ports FLASH_DQ[1]]
set_property OFFCHIP_TERM NONE [get_ports FLASH_DQ[2]]
set_property OFFCHIP_TERM NONE [get_ports FLASH_DQ[3]]
set_property OFFCHIP_TERM NONE [get_ports FLASH_DQ[4]]
set_property OFFCHIP_TERM NONE [get_ports FLASH_DQ[5]]
set_property OFFCHIP_TERM NONE [get_ports FLASH_DQ[6]]
set_property OFFCHIP_TERM NONE [get_ports FLASH_DQ[7]]
set_property OFFCHIP_TERM NONE [get_ports FLASH_DQ[8]]
set_property OFFCHIP_TERM NONE [get_ports FLASH_DQ[9]]
set_property OFFCHIP_TERM NONE [get_ports FLASH_OE_N]
set_property OFFCHIP_TERM NONE [get_ports FLASH_RS0]
set_property OFFCHIP_TERM NONE [get_ports FLASH_RS1]
set_property OFFCHIP_TERM NONE [get_ports FLASH_WE_N]
set_property OFFCHIP_TERM NONE [get_ports FPGA_ATX_PSU_KILL]
set_property OFFCHIP_TERM NONE [get_ports FPGA_GPIO[0]]
set_property OFFCHIP_TERM NONE [get_ports FPGA_GPIO[10]]
set_property OFFCHIP_TERM NONE [get_ports FPGA_GPIO[11]]
set_property OFFCHIP_TERM NONE [get_ports FPGA_GPIO[12]]
set_property OFFCHIP_TERM NONE [get_ports FPGA_GPIO[13]]
set_property OFFCHIP_TERM NONE [get_ports FPGA_GPIO[14]]
set_property OFFCHIP_TERM NONE [get_ports FPGA_GPIO[15]]
set_property OFFCHIP_TERM NONE [get_ports FPGA_GPIO[1]]
set_property OFFCHIP_TERM NONE [get_ports FPGA_GPIO[2]]
set_property OFFCHIP_TERM NONE [get_ports FPGA_GPIO[3]]
set_property OFFCHIP_TERM NONE [get_ports FPGA_GPIO[4]]
set_property OFFCHIP_TERM NONE [get_ports FPGA_GPIO[5]]
set_property OFFCHIP_TERM NONE [get_ports FPGA_GPIO[6]]
set_property OFFCHIP_TERM NONE [get_ports FPGA_GPIO[7]]
set_property OFFCHIP_TERM NONE [get_ports FPGA_GPIO[8]]
set_property OFFCHIP_TERM NONE [get_ports FPGA_GPIO[9]]
set_property OFFCHIP_TERM NONE [get_ports GND[0]]
set_property OFFCHIP_TERM NONE [get_ports GND[10]]
set_property OFFCHIP_TERM NONE [get_ports GND[11]]
set_property OFFCHIP_TERM NONE [get_ports GND[12]]
set_property OFFCHIP_TERM NONE [get_ports GND[13]]
set_property OFFCHIP_TERM NONE [get_ports GND[14]]
set_property OFFCHIP_TERM NONE [get_ports GND[15]]
set_property OFFCHIP_TERM NONE [get_ports GND[1]]
set_property OFFCHIP_TERM NONE [get_ports GND[2]]
set_property OFFCHIP_TERM NONE [get_ports GND[3]]
set_property OFFCHIP_TERM NONE [get_ports GND[4]]
set_property OFFCHIP_TERM NONE [get_ports GND[5]]
set_property OFFCHIP_TERM NONE [get_ports GND[6]]
set_property OFFCHIP_TERM NONE [get_ports GND[7]]
set_property OFFCHIP_TERM NONE [get_ports GND[8]]
set_property OFFCHIP_TERM NONE [get_ports GND[9]]
set_property OFFCHIP_TERM NONE [get_ports I2C_RESET_FPGA]
set_property OFFCHIP_TERM NONE [get_ports I2C_SCL_FPGA]
set_property OFFCHIP_TERM NONE [get_ports I2C_SDA_FPGA]
set_property OFFCHIP_TERM NONE [get_ports MEZZANINE_0_CLK_SEL]
set_property OFFCHIP_TERM NONE [get_ports MEZZANINE_0_ENABLE_N]
set_property OFFCHIP_TERM NONE [get_ports MEZZANINE_0_ONE_WIRE]
set_property OFFCHIP_TERM NONE [get_ports MEZZANINE_0_ONE_WIRE_STRONG_PULLUP_EN_N]
set_property OFFCHIP_TERM NONE [get_ports MEZZANINE_0_RESET]
set_property OFFCHIP_TERM NONE [get_ports MEZZANINE_1_CLK_SEL]
set_property OFFCHIP_TERM NONE [get_ports MEZZANINE_1_ENABLE_N]
set_property OFFCHIP_TERM NONE [get_ports MEZZANINE_1_ONE_WIRE]
set_property OFFCHIP_TERM NONE [get_ports MEZZANINE_1_ONE_WIRE_STRONG_PULLUP_EN_N]
set_property OFFCHIP_TERM NONE [get_ports MEZZANINE_1_RESET]
set_property OFFCHIP_TERM NONE [get_ports MEZZANINE_2_CLK_SEL]
set_property OFFCHIP_TERM NONE [get_ports MEZZANINE_2_ENABLE_N]
set_property OFFCHIP_TERM NONE [get_ports MEZZANINE_2_ONE_WIRE]
set_property OFFCHIP_TERM NONE [get_ports MEZZANINE_2_ONE_WIRE_STRONG_PULLUP_EN_N]
set_property OFFCHIP_TERM NONE [get_ports MEZZANINE_2_RESET]
set_property OFFCHIP_TERM NONE [get_ports MEZZANINE_3_CLK_SEL]
set_property OFFCHIP_TERM NONE [get_ports MEZZANINE_3_ENABLE_N]
set_property OFFCHIP_TERM NONE [get_ports MEZZANINE_3_ONE_WIRE]
set_property OFFCHIP_TERM NONE [get_ports MEZZANINE_3_ONE_WIRE_STRONG_PULLUP_EN_N]
set_property OFFCHIP_TERM NONE [get_ports MEZZANINE_3_RESET]
set_property OFFCHIP_TERM NONE [get_ports ONE_GBE_RESET_N]
set_property OFFCHIP_TERM NONE [get_ports ONE_WIRE_EEPROM]
set_property OFFCHIP_TERM NONE [get_ports ONE_WIRE_EEPROM_STRONG_PULLUP_EN_N]
set_property OFFCHIP_TERM NONE [get_ports SPARTAN_CLK]
set_property OFFCHIP_TERM NONE [get_ports SPI_CLK]
set_property OFFCHIP_TERM NONE [get_ports SPI_CSB]
set_property OFFCHIP_TERM NONE [get_ports USB_UART_RXD]

