set_property -dict [ list CONFIG.PSU_DYNAMIC_DDR_CONFIG_EN {0}\
CONFIG.PSU__PRESET_APPLIED {1}\
CONFIG.PSU_BANK_0_IO_STANDARD {LVCMOS33}\
CONFIG.PSU_BANK_1_IO_STANDARD {LVCMOS18}\
CONFIG.PSU_BANK_2_IO_STANDARD {LVCMOS18}\
CONFIG.PSU_BANK_3_IO_STANDARD {LVCMOS18}\
CONFIG.PSU__CAN1__PERIPHERAL__ENABLE {0}\
CONFIG.PSU__ENET1__GRP_MDIO__ENABLE {1}\
CONFIG.PSU__ENET1__GRP_MDIO__IO {MIO 50 .. 51}\
CONFIG.PSU__ENET1__PERIPHERAL__ENABLE {1}\
CONFIG.PSU__ENET1__PERIPHERAL__IO {MIO 38 .. 49}\
CONFIG.PSU__GPIO_EMIO__PERIPHERAL__ENABLE {1}\
CONFIG.PSU__GPIO_EMIO__PERIPHERAL__IO {41}\
CONFIG.PSU__GPIO0_MIO__IO {MIO 0 .. 25}\
CONFIG.PSU__GPIO0_MIO__PERIPHERAL__ENABLE {1}\
CONFIG.PSU__GPIO1_MIO__IO {MIO 26 .. 51}\
CONFIG.PSU__GPIO1_MIO__PERIPHERAL__ENABLE {1}\
CONFIG.PSU__GPIO2_MIO__IO {MIO 52 .. 77}\
CONFIG.PSU__GPIO2_MIO__PERIPHERAL__ENABLE {1}\
CONFIG.PSU__I2C0__PERIPHERAL__ENABLE {1}\
CONFIG.PSU__I2C0__PERIPHERAL__IO {MIO 18 .. 19}\
CONFIG.PSU__I2C1__PERIPHERAL__ENABLE {1}\
CONFIG.PSU__I2C1__PERIPHERAL__IO {MIO 36 .. 37}\
CONFIG.PSU__QSPI__PERIPHERAL__ENABLE {0}\
CONFIG.PSU__QSPI__GRP_FBCLK__ENABLE {0}\
CONFIG.PSU__SD0__GRP_CD__ENABLE {1}\
CONFIG.PSU__SD0__GRP_CD__IO {MIO 24}\
CONFIG.PSU__SD0__GRP_POW__ENABLE {0}\
CONFIG.PSU__SD0__GRP_WP__ENABLE {1}\
CONFIG.PSU__SD0__GRP_WP__IO {MIO 25}\
CONFIG.PSU__SD0__PERIPHERAL__ENABLE {1}\
CONFIG.PSU__SD0__DATA_TRANSFER_MODE {4Bit}\
CONFIG.PSU__SD0__PERIPHERAL__IO {MIO 13 .. 16 21 22}\
CONFIG.PSU__SD0__SLOT_TYPE {SD 2.0}\
CONFIG.PSU__UART0__PERIPHERAL__ENABLE {0}\
CONFIG.PSU__UART1__PERIPHERAL__ENABLE {1}\
CONFIG.PSU__UART1__PERIPHERAL__IO {MIO 32 .. 33}\
CONFIG.PSU__USB0__PERIPHERAL__ENABLE {1}\
CONFIG.PSU__USB0__PERIPHERAL__IO {MIO 52 .. 63}\
CONFIG.PSU__USB1__PERIPHERAL__ENABLE {1}\
CONFIG.PSU__USB1__PERIPHERAL__IO {MIO 64 .. 75}\
CONFIG.PSU__USE__IRQ0 {1}\
CONFIG.PSU__USE__IRQ1 {1}\
CONFIG.PSU__USE__M_AXI_GP0 {1}\
CONFIG.PSU__USE__M_AXI_GP1 {1}\
CONFIG.PSU__USE__M_AXI_GP2 {0}\
CONFIG.PSU__USB3_0__PERIPHERAL__ENABLE {1}\
CONFIG.PSU__USB3_0__PERIPHERAL__IO {GT Lane2}\
CONFIG.PSU__USB3_1__PERIPHERAL__ENABLE {1}\
CONFIG.PSU__USB3_1__PERIPHERAL__IO {GT Lane3}\
CONFIG.PSU__PMU__PERIPHERAL__ENABLE {0}\
CONFIG.PSU__DDRC__VREF {1}\
CONFIG.PSU__DDRC__ECC {Disabled}\
CONFIG.PSU__DDRC__BUS_WIDTH {64 Bit}\
CONFIG.PSU__DDRC__DRAM_WIDTH {16 Bits}\
CONFIG.PSU__DDRC__MEMORY_TYPE {DDR 4}\
CONFIG.PSU__DDRC__COMPONENTS {Components}\
CONFIG.PSU__DDRC__SPEED_BIN {DDR4_2400R}\
CONFIG.PSU__CRF_APB__DDR_CTRL__FREQMHZ {1200}\
CONFIG.PSU__DDRC__DEVICE_CAPACITY {8192 MBits}\
CONFIG.PSU__DDRC__RANK_ADDR_COUNT {0}\
CONFIG.PSU__DDRC__BG_ADDR_COUNT {1}\
CONFIG.PSU__DDRC__BANK_ADDR_COUNT {2}\
CONFIG.PSU__DDRC__ROW_ADDR_COUNT {17}\
CONFIG.PSU__DDRC__COL_ADDR_COUNT {10}\
CONFIG.PSU__DDRC__CL {16}\
CONFIG.PSU__DDRC__CWL {12}\
CONFIG.PSU__DDRC__T_RCD {16}\
CONFIG.PSU__DDRC__T_RP {16}\
CONFIG.PSU__DDRC__T_RC {45.32}\
CONFIG.PSU__DDRC__T_RAS_MIN {32.0}\
CONFIG.PSU__DDRC__T_FAW {30.0}\
CONFIG.PSU__DDRC__DDR4_T_REF_MODE {0}\
CONFIG.PSU__DDRC__DDR4_T_REF_RANGE {Normal (0-85)}\
CONFIG.PSU__DDRC__PHY_DBI_MODE {0}\
CONFIG.PSU__DDRC__PARITY_ENABLE {0}\
CONFIG.PSU__DDRC__CLOCK_STOP_EN {0}\
CONFIG.PSU__DDRC__DDR4_CAL_MODE_ENABLE {0}\
CONFIG.PSU__DDRC__DDR4_CRC_CONTROL {0}\
CONFIG.PSU__DDRC__TRAIN_DATA_EYE {1}\
CONFIG.PSU__DDRC__TRAIN_READ_GATE {1}\
CONFIG.PSU__DDRC__TRAIN_WRITE_LEVEL {1}\
CONFIG.PSU__DDRC__DDR4_ADDR_MAPPING {1}\
CONFIG.PSU__DDRC__BRC_MAPPING {ROW_BANK_COL}\
CONFIG.PSU__DDRC__DM_DBI {DM_NO_DBI}\
CONFIG.PSU__DDRC__PER_BANK_REFRESH {0}\
CONFIG.PSU__DDRC__FGRM {1X}\
CONFIG.PSU__DDRC__LP_ASR {manual normal}\
CONFIG.PSU__DDRC__DIMM_ADDR_MIRROR {0}\
CONFIG.PSU__DDRC__STATIC_RD_MODE {0}\
CONFIG.PSU__DDRC__SELF_REF_ABORT {0}\
CONFIG.PSU__DISPLAYPORT__LANE0__ENABLE {1}\
CONFIG.PSU__DISPLAYPORT__LANE0__IO {GT Lane1}\
CONFIG.PSU__DISPLAYPORT__LANE1__ENABLE {1}\
CONFIG.PSU__DISPLAYPORT__LANE1__IO {GT Lane0}\
CONFIG.PSU__DISPLAYPORT__PERIPHERAL__ENABLE {1}\
CONFIG.PSU__DPAUX__PERIPHERAL__ENABLE {1}\
CONFIG.PSU__DPAUX__PERIPHERAL__IO {MIO 27 .. 30}\
CONFIG.PSU__DP__LANE_SEL {Dual Lower}\
CONFIG.PSU__DP__REF_CLK_FREQ {27}\
CONFIG.PSU__DP__REF_CLK_SEL {Ref Clk0}\
CONFIG.PSU__PSS_REF_CLK__FREQMHZ {33.33333}\
CONFIG.PSU__USB0__REF_CLK_SEL {Ref Clk1}\
CONFIG.PSU__USB0__REF_CLK_FREQ {100}\
CONFIG.PSU__USB1__REF_CLK_SEL {Ref Clk1}\
CONFIG.PSU__USB1__REF_CLK_FREQ {100}\
CONFIG.PSU__OVERRIDE__BASIC_CLOCK {0}\
CONFIG.PSU__CRF_APB__APLL_CTRL__SRCSEL {PSS_REF_CLK}\
CONFIG.PSU__CRF_APB__DPLL_CTRL__SRCSEL {PSS_REF_CLK}\
CONFIG.PSU__CRF_APB__VPLL_CTRL__SRCSEL {PSS_REF_CLK}\
CONFIG.PSU__CRL_APB__IOPLL_CTRL__SRCSEL {PSS_REF_CLK}\
CONFIG.PSU__CRL_APB__RPLL_CTRL__SRCSEL {PSS_REF_CLK}\
CONFIG.PSU__CRL_APB__CPU_R5_CTRL__SRCSEL {IOPLL}\
CONFIG.PSU__CRL_APB__CPU_R5_CTRL__FREQMHZ {500}\
CONFIG.PSU__CRL_APB__QSPI_REF_CTRL__FREQMHZ {125}\
CONFIG.PSU__CRL_APB__SDIO0_REF_CTRL__SRCSEL {IOPLL}\
CONFIG.PSU__CRL_APB__SDIO0_REF_CTRL__FREQMHZ {200}\
CONFIG.PSU__CRL_APB__SDIO1_REF_CTRL__SRCSEL {IOPLL}\
CONFIG.PSU__CRL_APB__SDIO1_REF_CTRL__FREQMHZ {200}\
CONFIG.PSU__CRL_APB__UART0_REF_CTRL__SRCSEL {IOPLL}\
CONFIG.PSU__CRL_APB__UART0_REF_CTRL__FREQMHZ {100}\
CONFIG.PSU__CRL_APB__I2C1_REF_CTRL__SRCSEL {IOPLL}\
CONFIG.PSU__CRL_APB__I2C1_REF_CTRL__FREQMHZ {100}\
CONFIG.PSU__CRL_APB__USB0_BUS_REF_CTRL__SRCSEL {IOPLL}\
CONFIG.PSU__CRL_APB__USB0_BUS_REF_CTRL__FREQMHZ {250}\
CONFIG.PSU__CRL_APB__USB1_BUS_REF_CTRL__SRCSEL {IOPLL}\
CONFIG.PSU__CRL_APB__USB1_BUS_REF_CTRL__FREQMHZ {250}\
CONFIG.PSU__CRL_APB__USB3_DUAL_REF_CTRL__SRCSEL {IOPLL}\
CONFIG.PSU__CRL_APB__USB3_DUAL_REF_CTRL__FREQMHZ {20}\
CONFIG.PSU__CRL_APB__GEM3_REF_CTRL__SRCSEL {IOPLL}\
CONFIG.PSU__CRL_APB__GEM3_REF_CTRL__FREQMHZ {125}\
CONFIG.PSU__FPGA_PL0_ENABLE {1}\
CONFIG.PSU__CRL_APB__PL0_REF_CTRL__SRCSEL {IOPLL}\
CONFIG.PSU__CRL_APB__PL0_REF_CTRL__FREQMHZ {100}\
CONFIG.PSU__CRL_APB__DBG_LPD_CTRL__SRCSEL {IOPLL}\
CONFIG.PSU__CRL_APB__DBG_LPD_CTRL__FREQMHZ {250}\
CONFIG.PSU__CRF_APB__ACPU_CTRL__SRCSEL {APLL}\
CONFIG.PSU__CRF_APB__ACPU_CTRL__FREQMHZ {1200}\
CONFIG.PSU__CRF_APB__GPU_REF_CTRL__FREQMHZ {600}\
CONFIG.PSU__CRF_APB__DDR_CTRL__SRCSEL {DPLL}\
CONFIG.PSU__CRF_APB__DDR_CTRL__FREQMHZ {1200}\
CONFIG.PSU__CRF_APB__DBG_FPD_CTRL__SRCSEL {IOPLL}\
CONFIG.PSU__CRF_APB__DBG_FPD_CTRL__FREQMHZ {250}\
CONFIG.PSU__CRF_APB__DBG_TRACE_CTRL__FREQMHZ {250}\
CONFIG.PSU__CRF_APB__DBG_TSTMP_CTRL__SRCSEL {IOPLL}\
CONFIG.PSU__CRF_APB__DBG_TSTMP_CTRL__FREQMHZ {250}\
CONFIG.PSU__CRL_APB__IOU_SWITCH_CTRL__SRCSEL {RPLL}\
CONFIG.PSU__CRL_APB__IOU_SWITCH_CTRL__FREQMHZ {267}\
CONFIG.PSU__CRL_APB__LPD_SWITCH_CTRL__SRCSEL {RPLL}\
CONFIG.PSU__CRL_APB__LPD_SWITCH_CTRL__FREQMHZ {533.333}\
CONFIG.PSU__CRL_APB__LPD_LSBUS_CTRL__SRCSEL {IOPLL}\
CONFIG.PSU__CRL_APB__LPD_LSBUS_CTRL__FREQMHZ {100}\
CONFIG.PSU__CRL_APB__TIMESTAMP_REF_CTRL__SRCSEL {PSS_REF_CLK}\
CONFIG.PSU__CRL_APB__TIMESTAMP_REF_CTRL__FREQMHZ {100}\
CONFIG.PSU__CRL_APB__PCAP_CTRL__SRCSEL {IOPLL}\
CONFIG.PSU__CRL_APB__PCAP_CTRL__FREQMHZ {200}\
CONFIG.PSU__CRF_APB__DP_STC_REF_CTRL__SRCSEL {RPLL}\
CONFIG.PSU__CRF_APB__DP_AUDIO_REF_CTRL__SRCSEL {RPLL}\
CONFIG.PSU__CRL_APB__ADMA_REF_CTRL__SRCSEL {RPLL}\
CONFIG.PSU__CRL_APB__ADMA_REF_CTRL__FREQMHZ {533.333}\
CONFIG.PSU__CRF_APB__GDMA_REF_CTRL__SRCSEL {DPLL}\
CONFIG.PSU__CRF_APB__GDMA_REF_CTRL__FREQMHZ {600}\
CONFIG.PSU__CRF_APB__DPDMA_REF_CTRL__SRCSEL {DPLL}\
CONFIG.PSU__CRF_APB__DPDMA_REF_CTRL__FREQMHZ {600}\
CONFIG.PSU__CRF_APB__TOPSW_MAIN_CTRL__SRCSEL {DPLL}\
CONFIG.PSU__CRF_APB__TOPSW_MAIN_CTRL__FREQMHZ {533.33}\
CONFIG.PSU__CRF_APB__TOPSW_LSBUS_CTRL__SRCSEL {IOPLL}\
CONFIG.PSU__CRF_APB__TOPSW_LSBUS_CTRL__FREQMHZ {100}\
CONFIG.PSU__CRL_APB__SPI0_REF_CTRL__SRCSEL {IOPLL}\
CONFIG.PSU__CRL_APB__SPI0_REF_CTRL__FREQMHZ {200}\
CONFIG.PSU__SPI0__PERIPHERAL__ENABLE {1}\
CONFIG.PSU__SPI0__PERIPHERAL__IO {MIO 0 .. 5}\
CONFIG.PSU__SPI0__GRP_SS0__ENABLE {1}\
CONFIG.PSU__SPI0__GRP_SS0__IO {MIO 3}\
CONFIG.PSU__SPI0__GRP_SS1__ENABLE {1}\
CONFIG.PSU__SPI0__GRP_SS1__IO {MIO 2}\
CONFIG.PSU__SPI0__GRP_SS2__ENABLE {1}\
CONFIG.PSU__SPI0__GRP_SS2__IO {MIO 1}\
CONFIG.PSU__CRL_APB__SPI1_REF_CTRL__SRCSEL {IOPLL}\
CONFIG.PSU__CRL_APB__SPI1_REF_CTRL__FREQMHZ {200}\
CONFIG.PSU__SPI1__PERIPHERAL__ENABLE {1}\
CONFIG.PSU__SPI1__PERIPHERAL__IO {MIO 6 .. 11}\
CONFIG.PSU__SPI1__GRP_SS0__ENABLE {1}\
CONFIG.PSU__SPI1__GRP_SS0__IO {MIO 9}\
CONFIG.PSU__SPI1__GRP_SS1__ENABLE {0}\
CONFIG.PSU__SPI1__GRP_SS2__ENABLE {0}\
] [get_bd_cells mpsoc]
