# Auto Generated by Xilinx generate_app. Modify at your own risk

# Set size of heap
HEAP_SIZE = 0x6000

CC := mb-gcc
CC_FLAGS := -MMD -MP -mlittle-endian -mxl-soft-mul -mcpu=v10.0
override CFLAGS += -ffunction-sections -fdata-sections -O2
CFLAGS_PEDANTIC := -Wall -Werror
LN_FLAGS := -Wl,--start-group,-lxil,-lgcc,-lc,--end-group \
            -Wl,--gc-sections \
            -Wl,-Map=map \
            -Wl,--strip-debug \
            -Wl,--defsym=_HEAP_SIZE=$(HEAP_SIZE)

c_SOURCES := $(wildcard *.c)

# Add just the LwIP sources that we need
c_SOURCES += lwip/src/core/def.c           \
             lwip/src/core/init.c          \
             lwip/src/core/inet_chksum.c   \
             lwip/src/core/ip.c            \
             lwip/src/core/mem.c           \
             lwip/src/core/memp.c          \
             lwip/src/core/netif.c         \
             lwip/src/core/pbuf.c          \
             lwip/src/core/stats.c         \
             lwip/src/core/timeouts.c      \
             lwip/src/core/udp.c           \
             lwip/src/core/ipv4/autoip.c   \
             lwip/src/core/ipv4/dhcp.c     \
             lwip/src/core/ipv4/etharp.c   \
             lwip/src/core/ipv4/icmp.c     \
             lwip/src/core/ipv4/ip4.c      \
             lwip/src/core/ipv4/ip4_addr.c \
             lwip/src/netif/ethernet.c     \
             lwip/src/apps/tftp/tftp_server.c

S_SOURCES := $(wildcard *.S)
s_SOURCES := $(wildcard *.s)
INCLUDES := $(wildcard *.h)
OBJS := $(patsubst %.c, %.o, $(c_SOURCES))
OBJS += $(patsubst %.S, %.o, $(S_SOURCES))
OBJS += $(patsubst %.s, %.o, $(s_SOURCES))
LSCRIPT := -Tlscript.ld

# Variables related to core_info data
OBJCOPY = mb-objcopy
OBJFMT = elf32-microblazeel
OBJARCH = MicroBlaze

# Use core_info if .bin or .tab exists, otherwise use dummy_info.bin
core_info_BINARY = $(word 1, \
									 $(wildcard core_info.bin core_info.tab) \
									 dummy_info.bin)

OBJS += $(patsubst %.bin, %.o, \
				$(patsubst %.tab, %.o, $(core_info_BINARY)))

CURRENT_DIR = $(shell pwd)
DEPFILES := $(patsubst %.o, %.d, $(OBJS))
LIBS := bsp/microblaze_0/lib/libxil.a
EXEC := executable.elf
MEM = $(patsubst %.elf, %.mem, $(EXEC))

INSTALL_FILE = ../../hdl_sources/microblaze_wb/executable.mem

INCLUDEPATH := -Ibsp/microblaze_0/include -I. -Ijam_lwip/include -Ilwip/src/include
LIBPATH := -Lbsp/microblaze_0/lib

export CFLAGS

all: symbols

$(EXEC): $(LIBS) $(OBJS) $(INCLUDES)
	$(CC) -o $@ $(OBJS) $(CC_FLAGS) $(CFLAGS) $(LN_FLAGS) $(LIBPATH) $(LSCRIPT)

$(MEM): $(EXEC)
	data2mem -bd $< -der -o m $@

$(LIBS):
	$(MAKE) -C bsp

%.o:%.c
	$(CC) $(CC_FLAGS) $(CFLAGS) $(CFLAGS_PEDANTIC) -c $< -o $@ $(INCLUDEPATH)

%.i:%.c
	$(CC) $(CC_FLAGS) $(CFLAGS) $(CFLAGS_PEDANTIC) -E $< -o $@ $(INCLUDEPATH)

%.o:%.S
	$(CC) $(CC_FLAGS) $(CFLAGS) $(CFLAGS_PEDANTIC) -c $< -o $@ $(INCLUDEPATH)

%.o:%.s
	$(CC) $(CC_FLAGS) $(CFLAGS) $(CFLAGS_PEDANTIC) -c $< -o $@ $(INCLUDEPATH)

dummy_info.o: dummy_info.bin
	$(OBJCOPY) -I binary -O $(OBJFMT) -B $(OBJARCH) \
		--redefine-sym \
		_binary_dummy_info_bin_start=_core_info \
		-N _binary_dummy_info_bin_end \
		-N _binary_dummy_info_bin_size \
		--rename-section .data=.core_info \
		$< $@

core_info.o: core_info.bin
	$(OBJCOPY) -I binary -O $(OBJFMT) -B $(OBJARCH) \
		--redefine-sym \
		_binary_core_info_bin_start=_core_info \
		-N _binary_core_info_bin_end \
		-N _binary_core_info_bin_size \
		--rename-section .data=.core_info \
		$< $@

core_info.bin: core_info.tab
	ruby ./util/cit2bin.rb $< > $@

symbols: $(EXEC)
	mb-readelf -s $< | sort -rnk3 > $@

install: $(MEM)
	sed '/Program header record #3, Size = 0x4, at 0x0001F000 to 0x0001F003/,$$d' $< > $(INSTALL_FILE)

tags:
	ctags -R

foo:
	echo = $(wildcard core_info.bin core_info.tab) dummy_info.bin

clean:
	$(MAKE) -C bsp clean
	rm -rf $(OBJS) $(LIBS) $(EXEC) *.o tags

.PHONY: install tags clean

-include $(DEPFILES)
