// soc_system_hps_0.v

// This file was auto-generated from altera_hps_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 24.1 1077

`timescale 1 ps / 1 ps
module soc_system_hps_0 #(
		parameter F2S_Width = 1,
		parameter S2F_Width = 0
	) (
		output wire        h2f_rst_n,      //         h2f_reset.reset_n	AXI4-Lite
		input  wire        f2h_axi_clk,    //     f2h_axi_clock.clk			AXI4-Lite
		input  wire [7:0]  f2h_AWID,       //     f2h_axi_slave.awid
		input  wire [31:0] f2h_AWADDR,     //                  .awaddr
		input  wire [3:0]  f2h_AWLEN,      //                  .awlen
		input  wire [2:0]  f2h_AWSIZE,     //                  .awsize
		input  wire [1:0]  f2h_AWBURST,    //                  .awburst
		input  wire [1:0]  f2h_AWLOCK,     //                  .awlock
		input  wire [3:0]  f2h_AWCACHE,    //                  .awcache
		input  wire [2:0]  f2h_AWPROT,     //                  .awprot
		input  wire        f2h_AWVALID,    //                  .awvalid	AXI4-Lite
		output wire        f2h_AWREADY,    //                  .awready	AXI4-Lite
		input  wire [4:0]  f2h_AWUSER,     //                  .awuser
		input  wire [7:0]  f2h_WID,        //                  .wid
		input  wire [31:0] f2h_WDATA,      //                  .wdata
		input  wire [3:0]  f2h_WSTRB,      //                  .wstrb
		input  wire        f2h_WLAST,      //                  .wlast
		input  wire        f2h_WVALID,     //                  .wvalid
		output wire        f2h_WREADY,     //                  .wready
		output wire [7:0]  f2h_BID,        //                  .bid
		output wire [1:0]  f2h_BRESP,      //                  .bresp
		output wire        f2h_BVALID,     //                  .bvalid
		input  wire        f2h_BREADY,     //                  .bready
		input  wire [7:0]  f2h_ARID,       //                  .arid
		input  wire [31:0] f2h_ARADDR,     //                  .araddr
		input  wire [3:0]  f2h_ARLEN,      //                  .arlen
		input  wire [2:0]  f2h_ARSIZE,     //                  .arsize
		input  wire [1:0]  f2h_ARBURST,    //                  .arburst
		input  wire [1:0]  f2h_ARLOCK,     //                  .arlock
		input  wire [3:0]  f2h_ARCACHE,    //                  .arcache
		input  wire [2:0]  f2h_ARPROT,     //                  .arprot
		input  wire        f2h_ARVALID,    //                  .arvalid
		output wire        f2h_ARREADY,    //                  .arready
		input  wire [4:0]  f2h_ARUSER,     //                  .aruser
		output wire [7:0]  f2h_RID,        //                  .rid
		output wire [31:0] f2h_RDATA,      //                  .rdata
		output wire [1:0]  f2h_RRESP,      //                  .rresp
		output wire        f2h_RLAST,      //                  .rlast
		output wire        f2h_RVALID,     //                  .rvalid
		input  wire        f2h_RREADY,     //                  .rready
		input  wire        h2f_lw_axi_clk, //  h2f_lw_axi_clock.clk
		output wire [11:0] h2f_lw_AWID,    // h2f_lw_axi_master.awid
		output wire [20:0] h2f_lw_AWADDR,  //                  .awaddr	AXI4-Lite
		output wire [3:0]  h2f_lw_AWLEN,   //                  .awlen
		output wire [2:0]  h2f_lw_AWSIZE,  //                  .awsize
		output wire [1:0]  h2f_lw_AWBURST, //                  .awburst
		output wire [1:0]  h2f_lw_AWLOCK,  //                  .awlock
		output wire [3:0]  h2f_lw_AWCACHE, //                  .awcache
		output wire [2:0]  h2f_lw_AWPROT,  //                  .awprot	AXI4-Lite
		output wire        h2f_lw_AWVALID, //                  .awvalid
		input  wire        h2f_lw_AWREADY, //                  .awready
		output wire [11:0] h2f_lw_WID,     //                  .wid
		output wire [31:0] h2f_lw_WDATA,   //                  .wdata	AXI4-Lite
		output wire [3:0]  h2f_lw_WSTRB,   //                  .wstrb	AXI4-Lite
		output wire        h2f_lw_WLAST,   //                  .wlast
		output wire        h2f_lw_WVALID,  //                  .wvalid	AXI4-Lite
		input  wire        h2f_lw_WREADY,  //                  .wready	AXI4-Lite
		input  wire [11:0] h2f_lw_BID,     //                  .bid
		input  wire [1:0]  h2f_lw_BRESP,   //                  .bresp	AXI4-Lite
		input  wire        h2f_lw_BVALID,  //                  .bvalid	AXI4-Lite
		output wire        h2f_lw_BREADY,  //                  .bready	AXI4-Lite
		output wire [11:0] h2f_lw_ARID,    //                  .arid
		output wire [20:0] h2f_lw_ARADDR,  //                  .araddr	AXI4-Lite
		output wire [3:0]  h2f_lw_ARLEN,   //                  .arlen
		output wire [2:0]  h2f_lw_ARSIZE,  //                  .arsize
		output wire [1:0]  h2f_lw_ARBURST, //                  .arburst
		output wire [1:0]  h2f_lw_ARLOCK,  //                  .arlock
		output wire [3:0]  h2f_lw_ARCACHE, //                  .arcache
		output wire [2:0]  h2f_lw_ARPROT,  //                  .arprot		AXI4-Lite
		output wire        h2f_lw_ARVALID, //                  .arvalid	AXI4-Lite
		input  wire        h2f_lw_ARREADY, //                  .arready	AXI4-Lite
		input  wire [11:0] h2f_lw_RID,     //                  .rid
		input  wire [31:0] h2f_lw_RDATA,   //                  .rdata	AXI4-Lite
		input  wire [1:0]  h2f_lw_RRESP,   //                  .rresp	AXI4-Lite
		input  wire        h2f_lw_RLAST,   //                  .rlast
		input  wire        h2f_lw_RVALID,  //                  .rvalid	AXI4-Lite
		output wire        h2f_lw_RREADY,  //                  .rready	AXI4-Lite
		output wire [14:0] mem_a,          //            memory.mem_a
		output wire [2:0]  mem_ba,         //                  .mem_ba
		output wire        mem_ck,         //                  .mem_ck
		output wire        mem_ck_n,       //                  .mem_ck_n
		output wire        mem_cke,        //                  .mem_cke
		output wire        mem_cs_n,       //                  .mem_cs_n
		output wire        mem_ras_n,      //                  .mem_ras_n
		output wire        mem_cas_n,      //                  .mem_cas_n
		output wire        mem_we_n,       //                  .mem_we_n
		output wire        mem_reset_n,    //                  .mem_reset_n
		inout  wire [31:0] mem_dq,         //                  .mem_dq
		inout  wire [3:0]  mem_dqs,        //                  .mem_dqs
		inout  wire [3:0]  mem_dqs_n,      //                  .mem_dqs_n
		output wire        mem_odt,        //                  .mem_odt
		output wire [3:0]  mem_dm,         //                  .mem_dm
		input  wire        oct_rzqin       //                  .oct_rzqin
	);

	generate
		// If any of the display statements (or deliberately broken
		// instantiations) within this generate block triggers then this module
		// has been instantiated this module with a set of parameters different
		// from those it was generated for.  This will usually result in a
		// non-functioning system.
		if (F2S_Width != 1)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					f2s_width_check ( .error(1'b1) );
		end
		if (S2F_Width != 0)
		begin
			initial begin
				$display("Generated module instantiated with wrong parameters");
				$stop;
			end
			instantiated_with_wrong_parameters_error_see_comment_above
					s2f_width_check ( .error(1'b1) );
		end
	endgenerate

	soc_system_hps_0_fpga_interfaces fpga_interfaces (
		.h2f_rst_n      (h2f_rst_n),      //         h2f_reset.reset_n
		.f2h_axi_clk    (f2h_axi_clk),    //     f2h_axi_clock.clk
		.f2h_AWID       (f2h_AWID),       //     f2h_axi_slave.awid
		.f2h_AWADDR     (f2h_AWADDR),     //                  .awaddr
		.f2h_AWLEN      (f2h_AWLEN),      //                  .awlen
		.f2h_AWSIZE     (f2h_AWSIZE),     //                  .awsize
		.f2h_AWBURST    (f2h_AWBURST),    //                  .awburst
		.f2h_AWLOCK     (f2h_AWLOCK),     //                  .awlock
		.f2h_AWCACHE    (f2h_AWCACHE),    //                  .awcache
		.f2h_AWPROT     (f2h_AWPROT),     //                  .awprot
		.f2h_AWVALID    (f2h_AWVALID),    //                  .awvalid
		.f2h_AWREADY    (f2h_AWREADY),    //                  .awready
		.f2h_AWUSER     (f2h_AWUSER),     //                  .awuser
		.f2h_WID        (f2h_WID),        //                  .wid
		.f2h_WDATA      (f2h_WDATA),      //                  .wdata
		.f2h_WSTRB      (f2h_WSTRB),      //                  .wstrb
		.f2h_WLAST      (f2h_WLAST),      //                  .wlast
		.f2h_WVALID     (f2h_WVALID),     //                  .wvalid
		.f2h_WREADY     (f2h_WREADY),     //                  .wready
		.f2h_BID        (f2h_BID),        //                  .bid
		.f2h_BRESP      (f2h_BRESP),      //                  .bresp
		.f2h_BVALID     (f2h_BVALID),     //                  .bvalid
		.f2h_BREADY     (f2h_BREADY),     //                  .bready
		.f2h_ARID       (f2h_ARID),       //                  .arid
		.f2h_ARADDR     (f2h_ARADDR),     //                  .araddr
		.f2h_ARLEN      (f2h_ARLEN),      //                  .arlen
		.f2h_ARSIZE     (f2h_ARSIZE),     //                  .arsize
		.f2h_ARBURST    (f2h_ARBURST),    //                  .arburst
		.f2h_ARLOCK     (f2h_ARLOCK),     //                  .arlock
		.f2h_ARCACHE    (f2h_ARCACHE),    //                  .arcache
		.f2h_ARPROT     (f2h_ARPROT),     //                  .arprot
		.f2h_ARVALID    (f2h_ARVALID),    //                  .arvalid
		.f2h_ARREADY    (f2h_ARREADY),    //                  .arready
		.f2h_ARUSER     (f2h_ARUSER),     //                  .aruser
		.f2h_RID        (f2h_RID),        //                  .rid
		.f2h_RDATA      (f2h_RDATA),      //                  .rdata
		.f2h_RRESP      (f2h_RRESP),      //                  .rresp
		.f2h_RLAST      (f2h_RLAST),      //                  .rlast
		.f2h_RVALID     (f2h_RVALID),     //                  .rvalid
		.f2h_RREADY     (f2h_RREADY),     //                  .rready
		.h2f_lw_axi_clk (h2f_lw_axi_clk), //  h2f_lw_axi_clock.clk
		.h2f_lw_AWID    (h2f_lw_AWID),    // h2f_lw_axi_master.awid
		.h2f_lw_AWADDR  (h2f_lw_AWADDR),  //                  .awaddr
		.h2f_lw_AWLEN   (h2f_lw_AWLEN),   //                  .awlen
		.h2f_lw_AWSIZE  (h2f_lw_AWSIZE),  //                  .awsize
		.h2f_lw_AWBURST (h2f_lw_AWBURST), //                  .awburst
		.h2f_lw_AWLOCK  (h2f_lw_AWLOCK),  //                  .awlock
		.h2f_lw_AWCACHE (h2f_lw_AWCACHE), //                  .awcache
		.h2f_lw_AWPROT  (h2f_lw_AWPROT),  //                  .awprot
		.h2f_lw_AWVALID (h2f_lw_AWVALID), //                  .awvalid
		.h2f_lw_AWREADY (h2f_lw_AWREADY), //                  .awready
		.h2f_lw_WID     (h2f_lw_WID),     //                  .wid
		.h2f_lw_WDATA   (h2f_lw_WDATA),   //                  .wdata
		.h2f_lw_WSTRB   (h2f_lw_WSTRB),   //                  .wstrb
		.h2f_lw_WLAST   (h2f_lw_WLAST),   //                  .wlast
		.h2f_lw_WVALID  (h2f_lw_WVALID),  //                  .wvalid
		.h2f_lw_WREADY  (h2f_lw_WREADY),  //                  .wready
		.h2f_lw_BID     (h2f_lw_BID),     //                  .bid
		.h2f_lw_BRESP   (h2f_lw_BRESP),   //                  .bresp
		.h2f_lw_BVALID  (h2f_lw_BVALID),  //                  .bvalid
		.h2f_lw_BREADY  (h2f_lw_BREADY),  //                  .bready
		.h2f_lw_ARID    (h2f_lw_ARID),    //                  .arid
		.h2f_lw_ARADDR  (h2f_lw_ARADDR),  //                  .araddr
		.h2f_lw_ARLEN   (h2f_lw_ARLEN),   //                  .arlen
		.h2f_lw_ARSIZE  (h2f_lw_ARSIZE),  //                  .arsize
		.h2f_lw_ARBURST (h2f_lw_ARBURST), //                  .arburst
		.h2f_lw_ARLOCK  (h2f_lw_ARLOCK),  //                  .arlock
		.h2f_lw_ARCACHE (h2f_lw_ARCACHE), //                  .arcache
		.h2f_lw_ARPROT  (h2f_lw_ARPROT),  //                  .arprot
		.h2f_lw_ARVALID (h2f_lw_ARVALID), //                  .arvalid
		.h2f_lw_ARREADY (h2f_lw_ARREADY), //                  .arready
		.h2f_lw_RID     (h2f_lw_RID),     //                  .rid
		.h2f_lw_RDATA   (h2f_lw_RDATA),   //                  .rdata
		.h2f_lw_RRESP   (h2f_lw_RRESP),   //                  .rresp
		.h2f_lw_RLAST   (h2f_lw_RLAST),   //                  .rlast
		.h2f_lw_RVALID  (h2f_lw_RVALID),  //                  .rvalid
		.h2f_lw_RREADY  (h2f_lw_RREADY)   //                  .rready
	);

	soc_system_hps_0_hps_io hps_io (
		.mem_a       (mem_a),       // memory.mem_a
		.mem_ba      (mem_ba),      //       .mem_ba
		.mem_ck      (mem_ck),      //       .mem_ck
		.mem_ck_n    (mem_ck_n),    //       .mem_ck_n
		.mem_cke     (mem_cke),     //       .mem_cke
		.mem_cs_n    (mem_cs_n),    //       .mem_cs_n
		.mem_ras_n   (mem_ras_n),   //       .mem_ras_n
		.mem_cas_n   (mem_cas_n),   //       .mem_cas_n
		.mem_we_n    (mem_we_n),    //       .mem_we_n
		.mem_reset_n (mem_reset_n), //       .mem_reset_n
		.mem_dq      (mem_dq),      //       .mem_dq
		.mem_dqs     (mem_dqs),     //       .mem_dqs
		.mem_dqs_n   (mem_dqs_n),   //       .mem_dqs_n
		.mem_odt     (mem_odt),     //       .mem_odt
		.mem_dm      (mem_dm),      //       .mem_dm
		.oct_rzqin   (oct_rzqin)    //       .oct_rzqin
	);

endmodule
